### ISSUE TITLE
Variables + aggregations not working in all cases

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#1007]
After going through many different user workflows for leapfrog, I found that the following cases aren't working with variables and aggregations.

_NOTE: 
I didn't test all of them (only top and clusterMode), this was specific to types of category maps that a user would want to make._

### Top
The most complex use would be something like:

```
@cat: $cause_descrip
@value: 10
@ramp: prism

color: ramp(top(@cat,@value),@ramp)
```

[MAP EXAMPLE](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiZmlyZV9wZXJpbWV0ZXJzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiXG5AY2F0OiAkY2F1c2VfZGVzY3JpcFxuQHZhbHVlOiAxMFxuQHJhbXA6IHByaXNtXG5cbmNvbG9yOiByYW1wKHRvcChAY2F0LEB2YWx1ZSksQHJhbXApXG4iLCJmIjp7ImxuZyI6MCwibGF0IjoyLjg0MjE3MDk0MzA0MDQwMWUtMTR9LCJnIjowLjk1NDE5NjI4OTkyODg4NDMsImgiOiIiLCJpIjoiZGF0YXNldCJ9)

The following don't work:

Attribute as variable:
```
@cat: $cause_descrip
color: ramp(top(@cat,10),prism)
```
Number of "buckets" as variable:
```
@value: 10
color: ramp(top($cause_descrip,@value),prism)
```

### ClusterMode

Attribute as variable not working:
```
@cat: $cause_descrip
@ramp: vivid
color: ramp(clusterMode(@cat),@ramp)
```

**Comment by Captain-Oski** [comment]
May I add this factorization : 
Viz: 
```
            @varOpacity: 0.1
            @varColor: rgb(255, 213, 9)
            color: opacity(@varColor,@varOpacity)
```
Event : 
```
$color.onchange = () => {
                viz.variables.varColor = $color.value`
            }
```

return : 

```
carto-vl.min.js:6 Uncaught (in promise) Error: opacity(): invalid first parameter 'color'
expected type was 'color', actual type was 'category'
```

Thank you.

**Comment by elenatorro** [comment]
Hi 👋 Could you test the map you've shared again? ([here](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiZmlyZV9wZXJpbWV0ZXJzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiXG5AY2F0OiAkY2F1c2VfZGVzY3JpcFxuQHZhbHVlOiAxMFxuQHJhbXA6IHByaXNtXG5cbmNvbG9yOiByYW1wKHRvcChAY2F0LEB2YWx1ZSksQHJhbXApXG4iLCJmIjp7ImxuZyI6MCwibGF0IjoyLjg0MjE3MDk0MzA0MDQwMWUtMTR9LCJnIjowLjk1NDE5NjI4OTkyODg4NDMsImgiOiIiLCJpIjoiZGF0YXNldCJ9))

I think we fixed it recently and works in the master branch. I've tested it and it seems to work fine, but let me know if I'm wrong.

Also, about your example @Captain-Oski. I tested the viz in master branch and works fine ✨ we'll do a release with the changes soon. However, a quick note about how to change the color:

You're code:

```js
$color.onchange = () => {
    viz.variables.varColor = $color.value
}
```

The way to change a viz property is by using `blendTo` as follows:

```js
$color.onchange = () => {
    viz.variables.varColor.blendTo($color.value)
}
```

**Comment by elenatorro** [comment]
Current status:

**Top**
* Using variables in expressions: fixed in master

**clusterMode**
* Already solved in this open PR https://github.com/CartoDB/carto-vl/pull/1281
