### ISSUE TITLE
Avoid `const feature = event.features[0];` in examples

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#1014]
Although using `        const feature = event.features[0];` is useful in some situations, I've seen many reports of "bugs" in CVL because of this.

We should probably remove that code from every example. Iterating the list in every case.

**Comment by rochoa** [comment]
I just checked the examples and this looks OK now. There are still some examples using `event.features[0]` but they are always checking there is at least one feature.
