### ISSUE TITLE
Datasets for the guides

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#1020]
It would be super nice to have some datasets to showcase different functionality in the CVL guides. Since they are intended for that, it would be better if the name of categories (if any) are in English, and if the content can be interesting to a big audience.

I'm searching for 4 kinds of datasets:
- [x] Numeric dataset to showcase classification and `linear`. I think that a population density would be the best here. Right now I'm using `pop_density_points`. I think that a higher-resolution dataset would be better. If the dataset contained more outliers would be good too since I want to talk about them and mitigations.
- [x] Category dataset. I imported and started using `uk_elections` (you can find it in `cartovl` account). I think it is a good one for showcasing ramp with categories in general, including `top` and `buckets.
- [x] Numeric dataset to showcase bubble-maps. In contrast with the first one, this should have fewer features or few features with a high property value. I thought of using an earthquake dataset, but the Richter scale is not the best to talk about how you should probably use `sqrt`. Solved with the railroad accidents one.
- [x] Category dataset to showcase multiple images (`ramp` with images).  Between the already existing one with the different cities and the new one of the railroad accidents this is solved.
- [x] Line dataset to showcase styling property adaptation to different geometry types. I'm writing an example to showcase that with `ne_10m_populated_places_simple` and `world_borders`. I think that a similar dataset (but of lines) that made sense to view at zoom level 0 would be perfect for this.

**Comment by makella** [comment]
@davidmanzanares 

I want to do a more thorough search in the morning for numeric datasets, but also don't want to hold you up, so here are some suggestions to get started:

For detailed population density I think is going to be hard to find... I know there are raster sources out there (actually, the `pop_density_points_` is a raster that I converted to vector a long time ago). I started downloading some Eurostat grids with pop density, the file size in 1GB..

Speaking of Eurostat, there seems to be a lot of data available for different themes (I will look through more tomorrow, but could be worth a browse)
https://ec.europa.eu/eurostat/data/database

for numeric/bubble maps _and/or_ category dataset to show multiple images, I think you can use this dataset that shows train accidents from 2016:
https://cartovl.carto.com/dataset/dot_rail_safety_data

for category map, this one is pretty simple POI's for one park in Denver:
https://team.carto.com/u/mamataakella/dataset/wash_park_poi

or tree types in the city of Vancouver, Canada:
https://cartovl.carto.com/dataset/vancouver_trees

**Comment by makella** [comment]
wind turbine data:
https://eerscmap.usgs.gov/uswtdb/

**Comment by makella** [comment]
this refers to the Eurostat population grid data but looks to be vector... didn't read through completely to see if there is a link and/or methodology:
https://citygeographics.org/2016/12/26/global-urban-constellations/

**Comment by makella** [comment]
traffic volume data for California:
http://www.dot.ca.gov/trafficops/census/

**Comment by davidmanzanares** [comment]
Thanks!

The numeric dataset "to showcase classification and linear" is not critical since the `pop_density_points` is ok I guess.

However, I'm now looking for a line dataset, I'll update the initial comment with it.

**Comment by makella** [comment]
would the traffic volume dataset work referenced above?

**Comment by davidmanzanares** [comment]
I think we are ok now , thx!
