### ISSUE TITLE
Use the `cartovl` account only

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#1035]
copy `river_directions_upper_co` from Mamata's account into the `cartovl` account

**Comment by VictorVelarde** [comment]
copy `circuito_del_jarama` from rochoa's account into `cartovl`

**Comment by VictorVelarde** [comment]
Oh!, I see... I had completely missed the editor as I was just looking for `username:` & `user:`in my review. Thx!

**Comment by rochoa** [comment]
I already opened a couple of PR. The first one is about exposing the examples' users so no one face that situation again.
