### ISSUE TITLE
clusterMode is broken

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#1038]
See http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfMTBtX3BvcHVsYXRlZF9wbGFjZXNfc2ltcGxlIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJjb2xvcjogcmFtcChjbHVzdGVyTW9kZSgkbmFtZSksIGJvbGQpIiwiZiI6eyJsbmciOjMzLjMyNzMxNTM1NDgyOTU4LCJsYXQiOjIuODQyMTcwOTQzMDQwNDAxZS0xNH0sImciOjEuMDU1MjgyNDE1MDQzMTk4NSwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoiZGF0YXNldCJ9

**Comment by VictorVelarde** [comment]
@davidmanzanares It looks like this should be closed, right?

**Comment by davidmanzanares** [comment]
Yes, sorry
