### ISSUE TITLE
Don't force babel usage everywhere

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#1039]
For debugging, babel is a problem since the generated code is sometimes not relatable to the original one and makes debugging very difficult.

![babel](https://user-images.githubusercontent.com/1692175/46662800-ac4fc800-cbbc-11e8-962b-0a55f9d4b0df.png)

**Comment by rochoa** [comment]
How easy is to disable it in your local environment?

**Comment by davidmanzanares** [comment]
On top of that, unit test times have increased from 3.7 seconds to 13.6 seconds

**Comment by VictorVelarde** [comment]
We have removed babel from build:dev

**Comment by davidmanzanares** [comment]
This is still happening when using `build:watch` and in `gh-pages`

**Comment by VictorVelarde** [comment]
@davidmanzanares:
* `build:watch` just uses the development mode, without babel, as it was before (PR https://github.com/CartoDB/carto-vl/pull/1044 reverted that AND also fixed `devtool` param with 'source-map'). what's the error it presents?
* with "gh-pages" do you refer to `ghpublish` task? it uses inside `yarn build` which launches both dev and min builds... what is expected from the build:dev?

**Comment by davidmanzanares** [comment]
Hmu...

Maybe I was in an outdated branch that didn't get your commits yet, sorry.
