### ISSUE TITLE
Add source.reload() function

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#1051]
CARTO VL sources of type `windshaft` (Dataset, SQL) are able to change. For example, a new row is inserted into the table, the rows are updated, deleted, etc.

So if you want to update your layer, the current way to do this with the current API is using the `layer.update()` function with a new source:

```js
const source = new carto.source.SQL(`SELECT * FROM table WHERE ...`);
const viz = new carto.Viz(`... `);
const layer = new carto.Layer('id', source, viz);
```
```js
layer.update(new carto.source.SQL(`SELECT * FROM table WHERE ...`));
```

A better (and more efficient) approach would be to `reload` the current source. This should invalidate cache and reload the dataframes:

```js
layer.source.reload();
```

**Comment by rochoa** [comment]
@Jesus89,

You don't need to create a new source, you can reuse your existing source and it will pickup the latest changes.

```js
const source = new carto.source.Da(`SELECT * FROM table`);
const viz = new carto.Viz();
const layer = new carto.Layer('layer', source, viz);
// ...
layer.update(source)
```

**Comment by rochoa** [comment]
With the `reload` approach, If you are sharing the same source in different layers, it's not clear what you should expect.

With:
```js
const source = new carto.source.Dataset(`table`);

const viz = new carto.Viz();
const layer = new carto.Layer('layer', source, viz);

const vizAgg = new carto.Viz('resolution: 16');
const layerAgg = new carto.Layer('layer-agg', source, viz);
```

What do you expect when executing the following code?
```js
layerAgg.source.reload()
```

Feel free to reopen if you consider other use-cases, but the one you described is pretty much covered with that, and the intention is clear.

**Comment by Jesus89** [comment]
Hi. This is simply syntax sugar. For example, if I want to reload the source (because the table has changed) I must do:

```js
this.myLayer.update(this.myLayer.source);

// instead of

this.myLayer.source.reload()

// or even

this.myLayer.reload()

// which is simply cleaner and more intuitive
```

The case of "sharing" the source is not exactly an issue because the source is not shared, but cloned. So `layerAgg.source.reload()` affects only `layerAgg`.

**Comment by rochoa** [comment]
> The case of "sharing" the source is not exactly an issue because the source is not shared, but cloned. So layerAgg.source.reload() affects only layerAgg.

That's an implementation detail. And I, as a library user, should not be aware of that.

**Comment by VictorVelarde** [comment]
I like the idea of `myLayer.reloadSource()`
