### ISSUE TITLE
Create a viz with a filter and after change the filter type

### ISSUE THREAD

**Issue by padawannn** [CartoDB/carto-vl#1067]
If you create a layer with a filter like this:

`const viz = new carto.Viz(`
      filter: eq($sov0name, 'Mexico')
    `);`

And when the layer is loader you change  the filter like this:
`viz.filter.blendTo(
        s.and(
          s.gte(s.prop('pop_max'), 1),
          s.lte(s.prop('pop_max'), 10000000)
        )`

All features disappear and you need to navigate on the map so that they appear again

The example:
[add-layer.html.zip](https://github.com/CartoDB/carto-vl/files/2482931/add-layer.html.zip)

**Comment by rochoa** [comment]
I tested this back to version v0.9.1, it was failing with that version. It's fixed since version v0.10.0 and it also works OK in the v1.0.0 release.

Otherwise, feel free to reopen.
