### ISSUE TITLE
Clustering of a variable returns a bad error message

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#1068]
See https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibWFkcmlkX2xpc3RpbmdzICIsImIiOiIiLCJjIjoiY2FydG92bCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiICAgIEBjYXRlZ29yaWVzOiB2aWV3cG9ydEhpc3RvZ3JhbSgkbmVpZ2hib3VyaG9vZF9ncm91cCwgMSwgMTIpLFxuICAgIEByb29tVHlwZTogKCRyb29tX3R5cGUpIFxuICAgIEBhdmVyYWdlUHJpY2U6IHZpZXdwb3J0QXZnKCRwcmljZSlcbiAgICBcbiAgICB3aWR0aDogNSwgIFxuICAgIGNvbG9yOiByYW1wKGNsdXN0ZXJNb2RlKEByb29tVHlwZSksIFBSSVNNKSxcbiAgICBzdHJva2VXaWR0aDogMC4xLCBcbiAgICAiLCJmIjp7ImxuZyI6LTMuNzAyODYyNjMzOTc0MTc3NywibGF0Ijo0MC40MTc5Mjc2NDIzNDM0N30sImciOjEyLjY3MTMxNTgxMTY2MTM1NSwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoiZGF0YXNldCJ9

Keep in mind that this is just a lack of a proper check and error throwing, the case cannot be supported logically because variables must be accessible from JS and you cannot mix clustered and unclustered accesses to the same property

As reported by @ramiroaznar

**Comment by rochoa** [comment]
If instead of using the variable, you use the column again:

```
@categories: viewportHistogram($neighbourhood_group, 1, 12)
@roomType: $room_type
@averagePrice: viewportAvg($price)

width: 5,  
color: ramp(clusterMode($room_type), PRISM)
strokeWidth: 0.1 
```

You get the right error message: `CartoValidationError: [Incorrect value]: Incompatible combination of cluster aggregation usages ([{"type":"aggregated","op":"mode"}]) with unaggregated usage for property 'room_type'`.

**Comment by elenatorro** [comment]
Closing cause it's been fixed in this PR https://github.com/CartoDB/carto-vl/pull/1281
