### ISSUE TITLE
Filtering outliers automatically

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#108]
We could add something like: filtering: outliers($price) to automatically remove outliers based on some conditions (eg.: max 10% of the sample and features outside the two times the standard deviation)

**Comment by rochoa** [comment]
You can do this by using, for instance, `globalPercentile()`. E.g. `filter: between($pop_max, globalPercentile($pop_max, 10), globalPercentile($pop_max, 90))`.
