### ISSUE TITLE
Animations never sleep!

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/carto-vl#1102]
For an `Animation`, [`isAnimated`](https://github.com/CartoDB/carto-vl/blob/master/src/renderer/viz/expressions/Animation.js#L115) returns always true, even while `_paused`.

If we fix that (`this.paused` -> `this._paused`), then paused animations don't resume (with `play`) until some other change occurs, because in the `Layer` `render`, the [checking of `isAnimated()`](https://github.com/CartoDB/carto-vl/blob/master/src/Layer.js#L414-L416) for refreshing is ineffective, as `render` stops being called when animation is paused.

Also, when the update is forced by changing the map zoom or calling `map.triggerRepaint()`, the animation jumps to where it would have been if not paused. It seems the progress adjustment fails if animation hasn't been  receiving `_setTimestamp` while paused.

**Comment by davidmanzanares** [comment]
I think that technically this is not a bug, it is something that it is pretty close to becoming a bug.

Right now, with the `this.paused -> this._paused` the animation never sets the render into the `idle` state. This is not desired behavior, and I agree this could be changed.

Once we change that, we will need to inform the `Layer` on `Animation.play()` to request a new animation frame. This can be done by calling the Animation inherited method `notify()`. This should work, but I don't know if it is overkill and if it will create a performance regression.

For all of these reasons, I would change `Animation.isAnimated` to return always true. And in the future fix this properly (calling notify and checking it works as expected, or adding a new lightweight notify-like method).

**Comment by jgoizueta** [comment]
OK, I already [set it to true](https://github.com/CartoDB/carto-vl/pull/991/files#diff-94085fcffacdd5d83bb78d4682a11e2bR56) so what I'd do know is:

* clarify the documentation of isAnimated
* add new public methos `paused` or `isPaused` (`return this._paused`)

**Comment by VictorVelarde** [comment]
Just for completeness, a new isPlaying() method has been added here: https://github.com/CartoDB/carto-vl/pull/1161

**Comment by VictorVelarde** [comment]
IMO This can be closed after merging the new approach in https://github.com/CartoDB/carto-vl/pull/1170:
* `isAnimated` will keep returning always 'true'
* 'isPlaying' will be dynamic
* a paused animation will not raise an 'updated event' 
* no 'jump' will happen on playing again a paused animation.

**Comment by VictorVelarde** [comment]
Animations will definitively have a rest after the work in #1190... 💤
