### ISSUE TITLE
Clipping/resolution issue with polygon stroke

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#1107]
To test the issue open the jsfiddle and play with the zoom.

https://jsfiddle.net/qk13vn2d/

![](https://user-images.githubusercontent.com/2227572/47732033-a9993d80-dc65-11e8-9288-81fb287d1a7f.png)

**Comment by rafaelfernandezgis** [comment]
Hi @Jesus89, any update on this issue? We're facing the same problem in ours polygons:

![captura de pantalla de 2018-11-02 10-14-03](https://user-images.githubusercontent.com/6051197/47905760-286dc080-de88-11e8-922b-885066574c3e.png)

Thanks!

**Comment by Jesus89** [comment]
Hi @rafaelfernandezgis.

I'm currently not working on VL. I'll ping the team to check the status of the issue :wink:

**Comment by Jesus89** [comment]
Update: I have tested version `0.8.0` and seems to work fine. So this is a bug introduced in `0.9.0`.

https://jsfiddle.net/qk13vn2d/

**Comment by rafaelfernandezgis** [comment]
We're working on `0.9.1` indeed.
Thx!

**Comment by rochoa** [comment]
The commit 07a3052d0587beff5345a4e7dfc2bd200dad60ba introduces this regression.

**Comment by rafaelfernandezgis** [comment]
Thx for having a look at this @rochoa. Hopefully it was fixed soon.

**Comment by rochoa** [comment]
We just released v0.10.0 fixing this issue. Could you double-check it's working in your case?

**Comment by rafaelfernandezgis** [comment]
It works like a champ:
![captura de pantalla de 2018-11-03 19-49-18](https://user-images.githubusercontent.com/6051197/47956232-a8d41480-dfa1-11e8-9cc7-0d908b2ba05c.png)

Thanks @Jesus89 @VictorVelarde @davidmanzanares @rochoa

**Comment by VictorVelarde** [comment]
Hi @Jesus89 
I can't reproduce the problem yet. I have updated your first fiddle with v1.0 [here](https://jsfiddle.net/Lwh5p7dx/) and It looks like that the stroke is fine. 

Could you please attach another example / configuration displaying the problem?

**Comment by Jesus89** [comment]
:thinking: I can not reproduce it either today :S 

If I found it again I'll generate a reproducible example.

Closing this.

**Comment by VictorVelarde** [comment]
Thx, maybe it could be a problem just with the geometry of a precise feature...
