### ISSUE TITLE
Rethink the use of "infinity" for classified legends

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#1110]
I am making a choropleth map and adding a legend.

With the classified legend, we can overwrite `Infinity` to a custom value but instead of `Infinity` can the defaults be set to the min and max values in the data? It is pretty difficult to customize out-of-the-box. 

Also, the values don't really go to infinity...

I understand that if I was an application developer, that I would probably go in and customize each item in the legend list to my exact specifications. But for people (like me!) who just want and out-of-the-box CARTO VL styled legend I think we can do some pretty simple changes to make them useful as is.

## Example
I am making a map of percent of the population in SF w/ a Master's degree with **5 class quantiles**.

By default, this is what I get:

<img width="290" alt="screen shot 2018-10-30 at 11 48 18 am" src="https://user-images.githubusercontent.com/1566273/47738911-ce77bb80-dc39-11e8-914a-bfd38cc76c13.png">

I get that I can customize it. But even when I overwrite "Infinity" and change some of the style, you can see it still isn't ideal (notice the `-` for the first class, etc.):

<img width="293" alt="screen shot 2018-10-30 at 11 51 12 am" src="https://user-images.githubusercontent.com/1566273/47739389-e26fed00-dc3a-11e8-93cf-570eaad1edda.png">

## Proposal
Ideally for a classed map, it would be nice to have either:

Option 1:
- the first class `<($keyMin)` 
  - `<0.05`
- the last class `>($keyMax of previous class)`
  - `>0.22`

Option 2:
- the first class `<($keyMin)`
  - `<0.05`
- the last class `($keyMin) - ($keyMax)`
  - `0.22 - 0.75` (or whatever the max value of the attribute is)

cc @davidmanzanares

**Comment by davidmanzanares** [comment]
We could change the implementation, although it is not trivial when there are corner cases (when the max/min values cannot be computed, which happens in several cases).

However, for your case, it is possible to simply have `<0.05` just by changing application code without CVL development.

In fact, the problem you are experiencing is due to the usage of `-` as a separator. I think that other separator should be used, not just because of Infinity, but because it would be problematic with negative numbers too.

**Comment by makella** [comment]
ok, sounds good. 

>However, for your case, it is possible to simply have <0.05 just by changing application code without CVL development.

I'm still not sure how to do this... can you show me how? Every time I try to modify, the `-` keeps showing.

**Comment by davidmanzanares** [comment]
Sure!

**Comment by VictorVelarde** [comment]
I guess this should be closed, right @makella?

**Comment by makella** [comment]
yep!
