### ISSUE TITLE
CARTO VL appears twice in Docs

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#1124]
Go to https://carto.com/developers/carto-vl/ and check the `Docs` dropdown.

![](https://user-images.githubusercontent.com/2227572/48012834-31c68980-e123-11e8-9315-5d963c3ff1bb.png)

The first one points to `https://carto.com/developers/carto-vl/v0.9.1` and the second one to `https://carto.com/developers/carto-vl/`.

**Comment by davidmanzanares** [comment]
That's clearly a feature :joy:

**Comment by VictorVelarde** [comment]
Fixed in prod 🚀
