### ISSUE TITLE
Provide a way to configure or disable aggregation

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/carto-vl#1142]
There are some situations where it'd nice to be able to change aggregations from the client:
- Easier testing during development.
- The performance of certain maps is harmed by using aggregations. As the smart backend isn't yet able to discriminate between good and bad aggregations, having the ability to disable it from the client would be a nice workaround in the meantime.

This can done by setting `aggregation: X` in the mapConfig. To disable it: `aggregation: false`.

**Comment by rochoa** [comment]
This should be addressed at the same time as https://github.com/CartoDB/carto-vl/issues/1054.

**Comment by Algunenano** [comment]
Stale
