### ISSUE TITLE
Zoom to feature by Id

### ISSUE THREAD

**Issue by RominaMartin** [CartoDB/carto-vl#1144]
Hello,

I've been trying to make zoom to a feature, either by a `FeatureEvent` or directly by the feature ID. I understand I can do it with the `FeatureEvent` by obtaining the event coordinates and play with it but I'm not so sure on how to accomplish by doing it with the Feature ID. 

Is there any way to obtain a feature bounding-box or coordinates?

Again, I apologize for the inconvenience.

**Comment by VictorVelarde** [comment]
Hi @RominaMartin 

Right now the only way to make zoom to a feature is using the coords within a `FeatureEvent`. 

We are working in providing a more precise 'getCentroid' method to the features, but they will have to be selected first, either by an `Interactivity` event or by `viewportFeatures`.
