### ISSUE TITLE
Fix hurricane example

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/carto-vl#1147]
As reported by @Algunenano there is oversimplification in this example (hurricane-harvey), which generates some visual artifacts.

We should look at MapsAPI. In the short term, we can just set the zoom to `7.01` instead of `7` in the example, so it will load tiles from zoom 8 instead of zoom 7.

**Comment by rochoa** [comment]
https://github.com/CartoDB/carto-vl/pull/1148 should fix this one.

**Comment by rochoa** [comment]
As we already released CARTO VL v1.1, which includes https://github.com/CartoDB/carto-vl/pull/1148, this is already fixed.

### Before
![before](https://user-images.githubusercontent.com/45346/51533678-d95e7880-1e43-11e9-8c45-c333d7296b1a.png)

### After
![after](https://user-images.githubusercontent.com/45346/51533683-dd8a9600-1e43-11e9-8cd4-f1afd00d0a69.png)


This was reported when we did the [CARTO VL v1.0 announcement blog post](https://carto.com/blog/carto-vl-vector-mapping-launch/), you can check the hurricane example over there is already fixed.
