### ISSUE TITLE
Clarify css use in guides

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/carto-vl#1150]
As per https://gis.stackexchange.com/questions/302864/how-to-run-basic-setup-carto-vl it looks like the style url has not been replaced for an absolute one. 

But also, it looks like we might need some indications on setting a basic CSS in the guides

**Comment by csubira** [comment]
Yes! As you said @inigomedina that URL should be replaced by an absolute, as it's done in **carto.js** with `<script src="../../../dist/public/carto.js"></script>` here:
https://github.com/CartoDB/developers/blob/master/grunt-tasks/carto-js/string-replace-guides.js#L18

However, I checked in **cartoVL** grunt task for replacements in guides and there is not anything like it: https://github.com/CartoDB/developers/blob/master/grunt-tasks/carto-vl/string-replace-guides.js
My guess is that adding a similar pattern it should be fixed for now. 
Then, as both of you mentioned, maybe add extra indications if needed or think about any other solution for the near future.

**Comment by inigomedina** [comment]
Nice, @csubira. I handle it.

**Comment by inigomedina** [comment]
I've already added the fix to the grunt tasks list for replacements and deployed it to production: https://carto.com/developers/carto-vl/guides/getting-started/#all-together

**Comment by makella** [comment]
thank you!!!
