### ISSUE TITLE
viewportQuantiles doesn't seem to be behaving properly

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#1166]
I know this has come up a few times in the past and it seems to be happening again where viewportQuantiles doesn't seem right.

For example, I would expect [this map](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoic3BlbmRfZGF0YSIsImIiOiIiLCJjIjoiY2FydG92bCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDNcbmNvbG9yOiByYW1wKHZpZXdwb3J0UXVhbnRpbGVzKCRhbW91bnQsNSksc3Vuc2V0KVxuc3Ryb2tlV2lkdGg6IDAiLCJmIjp7ImxuZyI6Mi4yMDAwOTI5ODg3Mjk5MjA4LCJsYXQiOjQxLjM5NTIxMzYwNzIxNTkxfSwiZyI6MTAuMjc3MTI3NzUyMzE4MzMyLCJoIjoiRGFya01hdHRlciIsImkiOiJkYXRhc2V0In0=) which uses `viewportQuantiles` to be the same as [this map](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoic3BlbmRfZGF0YSIsImIiOiIiLCJjIjoiY2FydG92bCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDNcbmNvbG9yOiByYW1wKGdsb2JhbFF1YW50aWxlcygkYW1vdW50LDUpLHN1bnNldClcbnN0cm9rZVdpZHRoOiAwIiwiZiI6eyJsbmciOjIuMjAwMDkyOTg4NzI5OTIwOCwibGF0Ijo0MS4zOTUyMTM2MDcyMTU5MX0sImciOjEwLjI3NzEyNzc1MjMxODMzMiwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoiZGF0YXNldCJ9) which uses `globalQuantiles` since in both maps, all of the data points are in the view.

Zooming in on the `viewportQuantiles` map, you can see some variation if you zoom pan ([example](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoic3BlbmRfZGF0YSIsImIiOiIiLCJjIjoiY2FydG92bCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDhcbmNvbG9yOiByYW1wKHZpZXdwb3J0UXVhbnRpbGVzKCRhbW91bnQsNSksc3Vuc2V0KVxuc3Ryb2tlV2lkdGg6IDAiLCJmIjp7ImxuZyI6Mi4yMDQ2MzAzMjUxMTY1NjgsImxhdCI6NDEuNDAzMjUwOTMwMzU1NTR9LCJnIjoxNy41NTc0MTkwNzE1NzY0NjUsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==))

I think something may have changed because I remember when we first worked on the examples that [this map](https://carto.com/developers/carto-vl/examples/#example-style-by-number) was working... I'll open a PR to change all the style by number examples to `global`... using `viewport` in that context is confusing anyway.

**Comment by VictorVelarde** [comment]
The `viewportQuantiles` issue is a problem we can fix easily, but 👍 to use `global` versions for that example!
