### ISSUE TITLE
Import error v1.0.0 in a webpack & react project

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/carto-vl#1171]
As indicated by @mbforr:

### Description
Using `import carto from '@carto/carto-vl'` in a project (https://github.com/mbforr/isthmus-react/)
(added with `yarn add @carto/carto-vl`) --> `"@carto/carto-vl": "^1.0.0"` in package.json file

It **won't compile** when running with webpack producing this:

### The error is 
```
./node_modules/@carto/carto-vl/dist/carto-vl.js
Module parse failed: /Users/mbforr/Documents/matt/react/isthmus-react/node_modules/@carto/carto-vl/dist/carto-vl.js Unexpected token (15870:32)
You may need an appropriate loader to handle this file type.
|                 const dimensionStats = stats.dimensions[dimName];
|                 const dimType = adaptColumnType(dimensionStats.type);
|                 const { column, ...params } = dimension;
|                 if (properties[column].dimension) {
|                     throw new _errors_carto_maps_api_error__WEBPACK_IMPORTED_MODULE_6__["default"](`${_errors_carto_maps_api_error__WEBPACK_IMPORTED_MODULE_6__["CartoMapsAPITypes"].NOT_SUPPORTED} Multiple dimensions based on same column '${column}'.`);
 @ ./src/components/CARTOVLMap.js 35:15-41
 @ ./src/components/Page.js
 @ ./src/routers/AppRouter.js
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./src/app.js
```

**Comment by VictorVelarde** [comment]
Unexpected token (15870:32) corresponds to this line:
```const { column, ...params } = dimension;```

**Comment by elenatorro** [comment]
I think we discussed a similar problem in the past in this issue (https://github.com/CartoDB/carto-vl/issues/28), where we had a problem with the imports because the glsl compiler.

I've a question: Why aren't we transpiling the non-minified version of the library? Is it due to the bundle size? Because IMO, the user shouldn't need to add _extra_ settings to use a particular library. The _exclude:_ option shouldn't be a must to import our library.

In case we don't want to transpile the library and the users have to do this setup, we must include it in the documentation. 

What do you think?

**Comment by elenatorro** [comment]
About:
> In case we don't want to transpile the library and the users have to do this setup, we must include it in the documentation.

We'd have to include in the documentation not about how to use the _exclude_, but how to import the compiled library, which can be done as follows:

```js
import carto from 'path_to_node_modules/node_modules/@carto/carto-vl/dist/carto-vl.min.js';
```

**Comment by VictorVelarde** [comment]
Yes, that's another option, but I guess that most people would go first for `import carto from @carto`, without even reading the docs.

I aggree that distributing a non-babelified library can generate some confusion for common webpack configurations, cause most libraries are distributed already transpiled and most default configs. exclude node_modules. On the other hand, distributing a non-babelified copy, apart from the size, allows a much more flexible build.

All in all, I think that probably nowdays the first still beats the second, but maybe we could try to harmonize both options, defaulting to transpiled, and documenting the more advanced / less-common use.

**Comment by VictorVelarde** [comment]
The fix has already been merged to master. It will be available in the next release
