### ISSUE TITLE
Enhance filter examples/create guide on Dev Center

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/carto-vl#1172]
`filter` is a property quite important when dealing with widgets. So more docs about this property are needed:
* a guide explaining the concept, how it works
* I was not able to get to the reference of this property (searching in Developers with `ctrol+f` is hard cc @inigomedina ),
* there is [one basic example](https://carto.com/developers/carto-vl/examples/#example-filter-based-styling), but another more complex one (or two) would be great,
* I like how easy to understand is [@rochoa's code](https://gist.github.com/rochoa/d61774b4086c5ade34555455284f9a3b#file-app-js-L40) in this respect.

It would be great to have also a mixed doc/example in Airship.

cc @makella @VictorVelarde

**Comment by makella** [comment]
a first enhancement could be to make the filtering example more robust with a few different radio buttons for different kinds of filters in the examples section. We can also link to the reference from that example in the legend box text.

I will also spend some time thinking about a Guide that would be robust enough to demonstrate the use of filter in a variety of ways. Thinking here, that you can filter the data (SQL source) or filter the features in the browser (filter). We do a lot of explanation in the animation guide about filtering in that context, so it might be a matter of reworking content from there into a guide all about ways to filter data.

**Comment by VictorVelarde** [comment]
Most of the issues / doubts came from filtering the current viz using some kind of widget in the client (mostly an airship category widget to choose one or several categories). Regarding to the 'SQL source', we had some conversations regarding to 're-using' the same source to get server updates and that could fit into the current 'sources guide' (maybe just as a Note)

**Comment by makella** [comment]
ahhhh i see. 

Ok, so another layer of this then is maybe adding a section in the Widgets Guide to address this:
> Most of the issues / doubts came from filtering the current viz using some kind of widget in the client (mostly an airship category widget to choose one or several categories).

Or build off the category widget created in the Widgets Guide in a Filter with Widgets guide... (maybe?)

While still adding a few more meaningful options to the Filtering Example.

**Comment by ramiroaznar** [comment]
Yes. Helping common use cases (filtering by histogram bins, categories...) would be very useful.

**Comment by VictorVelarde** [comment]
In CARTO VL guides, I would try to illustrate how to update or reset a filter dinamically using simple controls (like an HTML Select with several options), to exemplify a simple 'selection updated' >> 'update filter' flow. 

For the specific 'airship widgets', I would expect a more detailed guide / explanation from the airship side (the general guides or the new 'airship-carto-vl-bridge' project)... and some links between both sides.

Pinging @ivanmalagon and @rochoa for suggestions on how to document these "integrations"

**Comment by rochoa** [comment]
As per our _offline_ conversation about the JS API _advanced_ guides, I would love to cover the `filter` property as part of them. It's really powerful when you combine variables in the String API with JS API and the application state.

**Comment by makella** [comment]
do we have a basic example floating around that I could take a look at?

**Comment by VictorVelarde** [comment]
As per our conversations, we're gonna start with more advanced examples, before considering a new guide: https://github.com/CartoDB/carto-vl/issues/1219

**Comment by makella** [comment]
@elenatorro and I will work on modifying [this example](https://carto.com/developers/carto-vl/examples/#example-viewport-category-widget) using an HTML selector to select by category and also add a selector to color by category (similar to what's in @rochoa example). This will show how to use filters on the data as well as symbology.

**Comment by makella** [comment]
@elenatorro for more details on what we could do for this example:

As @VictorVelarde mentions, the purpose is:

> to illustrate how to update or reset a filter dynamically using simple controls (like an HTML Select with several options), to exemplify a simple 'selection updated' >> 'update filter' flow.

So the biggest piece we want to highlight is how selecting something updates the filter and that it is all awesome and dynamic :)

For the example, let's go ahead and:
- use the rail accidents data and styling from [this map](https://carto.com/developers/carto-vl/examples/#example-point-legend)
- where there is the ability to turn on/off one or more categories 

thanks!

**Comment by elenatorro** [comment]
Merged 🚀
