### ISSUE TITLE
Example of choropleth legend

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/carto-vl#1178]
The closer legend we have for choropleth or color gradient maps [is this example](https://carto.com/developers/carto-vl/examples/maps/misc/legends/poly-legend-ma.html). But that is still kind of a "bullet point map". IMHO it would be very very useful to have a basic example building something like this:

![legend](https://user-images.githubusercontent.com/1566273/44549794-6d82b300-a6df-11e8-8d07-3e9452d3bf91.png)

**Comment by makella** [comment]
so VL provides the legend data, and you can style it however you want. the example that you point out is the polygon legend for VL. i'm not sure if @elenatorro has other insight to add here, but from my understanding, as the developer, you can take the legend information VL provides and style it how you want.

**Comment by makella** [comment]
@ramiroaznar going to close this on the VL side... I'm wondering if there are possibilities to do this with the data VL sends that is consumed by Airship legends (?). The other option is to modify the styling inside of your application.

**Comment by ramiroaznar** [comment]
Yes, maybe this is more an Airship issue/request. cc @ivanmalagon

**Comment by makella** [comment]
as a note, putting in the gradient legend example that @elenatorro made.. maybe we can add this to the examples with some class breaks. i think offering a couple of other styles will be good..

https://bl.ocks.org/elenatorro/d642e6c9a81d9261e9cdc382f5ff1a5a

**Comment by ramiroaznar** [comment]
Yes, please!

**Comment by elenatorro** [comment]
Nice! We can add it at least as an example without Airship as Mamata suggests.

**Comment by VictorVelarde** [comment]
Just a comment here. If we are going to use buckets for the classification in those examples, it would be great if the legends (or 'colorbars') could reflect those buckets, as in this: https://gka.github.io/palettes/#colors=lightyellow,orange,deeppink,darkred|steps=7|bez=1|coL=1

The gradient mode could be incorrectly interpreted as "all color steps in the bar are used"

**Comment by ramiroaznar** [comment]
Yes, sorry about my initial enthusiasm. I think we should show discrete color values, not a gradient.

**Comment by makella** [comment]
@VictorVelarde totally! thank you for pointing that out.

You bring up an excellent point. There are two versions:
- Gradient with meaningful stops labeled for interpolation through color
- A class-based legend with each class break colored and labeled (no gradient)

In Builder, we always did the gradient even though we didn't have maps other than classed so definitely take your point to avoid that pitfall!

Basically, I think the legends below, horizontal (modified to be a little more traditionally rectangular) with appropriate labeling:

Choropleth:
https://carto.com/developers/carto-vl/examples/#example-choropleth-legend
Unclassed choropleth (even though this is points not polygons so not really choropleth but unclassed):
https://carto.com/developers/carto-vl/examples/#example-unclassed-legend

That brings up the point too, that "choropleth" would be only for polygons. I can see times where you would want to use a similar style for points/lines, but we should think about those differently.

With regards to Airship, I did contribute a lot of information on a legends ticket. Could be good to look through to see what additional examples we could use (point and line classed map ideas in there)... one that comes to mind is point size, line size, etc. and the way @elenatorro and David set the legends up, we have them organized by geometry type and map type so we have a good foundation to build off of.

https://github.com/CartoDB/airship/issues/157
