### ISSUE TITLE
Incorrect layer updated events

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#1189]
With the changes in https://github.com/CartoDB/carto-vl/pull/1170, we have introduced a few regressions. The ones I'm aware:

1. The `updated` event is not fired when the viewport changes—it fires when a dataframe is added/removed.
1. The `updated` event is not properly fired after a `blendTo` operation. It looks like it's missing the last `updated` event. If you rely on that event to access the value of a histogram, you might not get final representation after the blendTo operation finishes.

**Comment by VictorVelarde** [comment]
Thx @rochoa and sorry for the inconveniences!

In the first case, it was a misunderstanding on restricting the `Layer:updated` event to just *dataframe updates*. So I'm gonna start with that case --> I have added a failing test to illustrate that **regression 1** and I'll fix it on any 'viewport' change, so it will allow recovering the last viewportFunctions values.

I'm also gonna extend / modify the catalog of 'updated' _events triggers_ here, indicating if they are implemented or not:

- [x] a) layer visibility has changed
- [x] b) viz has been updated
- [x] c) source has been updated
- [ ] d) viewport has changed (zoom, center, bearing or pitch) and that requires new dataframes or NOT
- [x] e) an animation isPlaying

Note: b), c), d) and e) require the layer to be visible to raise an 'updated' event
