### ISSUE TITLE
viz.blendTo and viz.reset methods

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/carto-vl#1210]
Instead of using something like:

```js
[...]
     const checked = e.detail;
      if (checked){
        viz.color.blendTo(`opacity(${color}, 0.6)`, delay);
        viz.strokeColor.blendTo(`${strokeColor}`, delay);
      } else {
        viz.color.blendTo(`opacity(${color}, 0.00001)`, delay);
        viz.strokeColor.blendTo(`opacity(${strokeColor}, 0.00001)`, delay);
      }
```

It would be great to have something like...

```js
[...]
     const checked = e.detail;
     checked 
        ? viz.reset() 
        : viz.blendTo({
          'color': opacity(${color}, 0.00001)`, 
          'colorStroke': `opacity(${colorStroke}, 0.00001)`}, delay);
```

cc @VictorVelarde @rochoa

**Comment by ramiroaznar** [comment]
That's a good question. I would say to the original state... but from a developer point of view, don't know if the previously known state makes more sense.

**Comment by rochoa** [comment]
That syntactic sugar could help in some cases, but as you see, it's not trivial to decide on the behaviour of a global `reset` as the lifecycle of the visualization could be constantly changing. If you start thinking about animations it's even more complicated.

As there is already an alternative, as described in this very same issue, I'm closing this.
