### ISSUE TITLE
Basemap features aren't getting labeled if feature is getting labeled

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#1211]
@VictorVelarde 

I'm noticing that if there is a feature getting labeled at the same location there is a basemap label, the basemap label is removed... 

For example, here, you will notice that Madrid isn't labeled:

<img width="608" alt="screen shot 2019-01-02 at 10 28 45 am" src="https://user-images.githubusercontent.com/1566273/50604059-f1f9f500-0e7a-11e9-84d0-62e00c63b7be.png">

Doing a little bit of checking it seems like this is Mapbox labeling behavior, but just want to check.

**Comment by makella** [comment]
hmmmm actually, now all of a sudden, I'm seeing the label for Madrid... weird. Closing for now will see if I can duplicate again.
<img width="543" alt="screen shot 2019-01-02 at 10 47 31 am" src="https://user-images.githubusercontent.com/1566273/50604334-d6dbb500-0e7b-11e9-94e9-83eb5103f5a7.png">

**Comment by VictorVelarde** [comment]
It looks like some kind of collision algorithm. Maybe that collision just happens at a certain zoom level. Not sure if there is any 'weight' or label 'priority' value that could be used from MGL side...
