### ISSUE TITLE
Test different Mapbox GL versions

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#1220]
As per our documentation, CARTO VL should work with any Mapbox GL version from v0.50.0. Originally, that was easy to claim because the v0.50.0 version was the only existing version matching that criteria. There are new versions of Mapbox GL that matches that promise, we even updated all our examples/documentation to v0.52.0 (see #1207).

Sometimes, Mapbox GL new versions bring breaking changes. We need to have some testing that validates the different versions work with CARTO VL. For instance, with the upgrade to v0.52.0, we skipped testing with v0.51.0, it should be OK, but we don't know it.

**Comment by VictorVelarde** [comment]
Related to https://github.com/CartoDB/carto-vl/issues/1206
