### ISSUE TITLE
Layer never loading in latest Win10 and Edge

### ISSUE THREAD

**Issue by Captain-Oski** [CartoDB/carto-vl#1241]
Hello everyone, 

Just to mention that I am not able to make CARTO-VL load any layer 

Tested on multiples URLs , CARTO-VL Examples , CARTO-VL Editor, localhost etc...

Microsoft EdgeHTML 18.17763
Microsoft Edge 44.17763.1.0

[Edge Screenshot from https://carto.com/developers/carto-vl/examples/#example-check-for-browser-support](https://gyazo.com/e4695ba1a83f0757311c4049d4c3af96)

Can you reproduce ? Thank you

**Comment by VictorVelarde** [comment]
Hi @Captain-Oski,

I can confirm the issue. I was able to reproduce it and it looks like it is related to the underlying WebGL implementation in Edge. We'll try to release a fix asap.

Thx for your collaboration reporting it!
