### ISSUE TITLE
Make aggregated values available for labels

### ISSUE THREAD

**Issue by ztephm** [CartoDB/carto-vl#1244]
Use case:
We want to make a cluster map. We can use our clusterCount function for that, for example:

```
const viz = new carto.Viz(`
  @c_count: clusterCount()
  
  color: red
  width: @c_count
  resolution: 16
`);
```

It's a common convention for cluster maps to be labeled with the number of features represented by the cluster marker:

![screen shot 2019-01-24 at 6 52 59 pm](https://user-images.githubusercontent.com/1779444/51716095-63a40980-2009-11e9-9b45-70ce6add1b5c.png)

However we can't use the clusterCount in a label.

Right now VL requires us to use an original dataset attribute for labels instead, like in this example:
https://carto.com/developers/carto-vl/examples/#example-point-labels

```
const viz = new carto.Viz(`
  @c_count: clusterCount()
  @v_features: viewportFeatures($poi_name)
  
  color: red
  width: @c_count
  resolution: 16
`);

....
const features = viz.variables.v_features.value;
...
"label_field": `${f.properties['poi_name']}`,

```

Can we create a way to use aggregated values for labels, so something like this would work?

```
const viz = new carto.Viz(`
        color: fuchsia
        width: 6
        strokeColor: white
        strokeWidth: 2
        filter: $major == "YES"
        @cc: clusterCount()
        @v_features: viewportFeatures($poi_name, @cc)
      `);
```

**Comment by elenatorro** [comment]
Hi @ztephm 👋 I added two examples in this PR https://github.com/CartoDB/carto-vl/pull/1259, but I'd like to know if there's another dataset we can use in order to have a better one. Thanks! ✨ 

![screenshot 2019-02-13 at 10 56 27](https://user-images.githubusercontent.com/3824953/52704840-c9890e80-2f81-11e9-97e2-f9a3cf7b8c44.png)


cc @makella

**Comment by ztephm** [comment]
Thanks, it looks great! 

Here's an open dataset of Montreal parking signs I used for a cluster map. Depending on the settings it can have clusters with numbers up to 3 digits—in the example it could be good to show clusters with 1-, 2- and 3-digit numbers:

[signalisation_rd_tt.zip](https://github.com/CartoDB/carto-vl/files/2862595/signalisation_rd_tt.zip)

Or you could just use Populated Places, @ramiroaznar did [a test](http://bl.ocks.org/ramiroaznar/f894d952df6bab0ede6b552e0465955b) a while ago that has clusters showing 2 and 3 digits depending on zoom:

[ne_10m_populated_places_simple.zip](https://github.com/CartoDB/carto-vl/files/2862609/ne_10m_populated_places_simple.zip)

**Comment by ramiroaznar** [comment]
Also, you can use [Gencat data](https://solutionscdb.carto.com/u/cdbsol-admin/tables/gecat_geodata) as I did in this example (not working because of the API Key)

https://bl.ocks.org/ramiroaznar/f856209982304290f1152828a7bf7f2b

**Comment by elenatorro** [comment]
Merged in master ✨ We'll have to document it properly and research how can we improve the labels visualization. Meanwhile, we've added a couple of examples 👍

**Comment by makella** [comment]
Before the final examples are ready, we want to look into a couple of additional functionalities with Mapbox GL labeling and also fine-tune the ones we have. @ztephm @ramiroaznar thanks for the datasets! Will take a look through!
