### ISSUE TITLE
Error in ramp with column name 'length'

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/carto-vl#1247]
As reported internally by @andy-esch an unexpected error is thrown when styling some lines with a ramp using a column named **length**. 

The error is:
`> RangeError: invalid array length`

This comes, for example, from a column in a SQL made with `ST_Length(the_geom::geography) as length` and then using `ramp($length, sunset)` in the viz. Using other column name works fine.

**Comment by andy-esch** [comment]
Hey @VictorVelarde, we have another issue seen first in CartoDB/cartoframes#533 that looks similar to what's above.

**Comment by andy-esch** [comment]
To add to the last comment a bit more, we can reproduce in cartoframes that if interactivity is enabled for a column called `length`, then we get the following error in the console:
`TypeError: legend.key[0].toFixed is not a function[Learn More]`

If the column name is changed to, for example, `length_` then the map renders as expected.

**Comment by andy-esch** [comment]
Nope, that previous comment is wrong -- that error was from something else. As far as I can tell, there is no error thrown.

Here's a reproducible output: https://bl.ocks.org/andy-esch/c74297f7fbedaae5c42cc48eab5cbc6c

Changing the `length` to `length_` will allow the map to render.

**Comment by VictorVelarde** [comment]
We'll check it out, but probably the best thing to do here is to detect those JS 'reserved words' in VL and raise a descriptive error

**Comment by Jesus89** [comment]
Fixed in #1410. It will be ready in the next patch release
