### ISSUE TITLE
Fix symbology for empty border between geometries in Hurricane Harvey example

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/carto-vl#1250]
Due to how small the geometries are and the snapping done to transform the geometries in the MVT format, the Hurricane Harvey example shows small holes / lines between some geometries:

![image](https://user-images.githubusercontent.com/664253/52268566-25c5b000-293c-11e9-90dd-593dc9e89915.png)

I've found an easy workaround, which is to style the stroke in the same way:
![image](https://user-images.githubusercontent.com/664253/52268625-4e4daa00-293c-11e9-99c6-39ab622adf94.png)

Full style:
```
color: opacity(ramp(linear($sum_qpf,1,120),temps),($e_totpop/$area_sqmi)/500)
filter: animation(linear($sum_qpf,144.5, 1.5),5,fade(0,100))+0.1
strokeWidth: 0.2 
strokeColor: opacity(ramp(linear($sum_qpf,1,120),temps),($e_totpop/$area_sqmi)/500)
```

What do you think @makella, does it makes sense to change the style?

**Comment by makella** [comment]
hiii @Algunenano yes, that is totally fine. I had thought of doing that before but didn't know if we wanted to investigate the rendering itself. 

I can make those changes.

thanks!!
mamata

**Comment by Algunenano** [comment]
> I had thought of doing that before but didn't know if we wanted to investigate the rendering itself.

This has to do with the resolution we use to extract geometries from the database. Before 1.1 we were using 256 and now we are using 2048, which improved things but in this map I keep seeing artefacts until I use 12-16k which 

We could increase the resolution but that'd mean more network transfer and more time to process the geometries. A nice solution for this map, since it's small but has a lot of tiny vertex, would be the one tile strategy (one single request with the biggest precision possible) but we don't have it yet :cry:

**Comment by makella** [comment]
All good! This definitely seems to be an edge case... the cartographic fix you mention is something that I've been doing on other polygonal maps (https://carto.com/developers/carto-vl/examples/#example-style-by-number) adding an outline really helps to smooth the appearance of contiguous, small, polygons whether the outline totally matches or is subtle like in the maps above.

As a side note, with raster, I would always use a similar trick. Using `polygon-gamma` to "close" the gaps in conjunction with some line compositing made for the smoothest looking contiguous polygons. 

Glad to hear about this part:

> Before 1.1 we were using 256 and now we are using 2048, which improved things but in this map I keep seeing artifacts until I use 12-16k 

I'll have to keep my resolution glasses on to see the impact of this change!! Awesome!!

**Comment by makella** [comment]
@Algunenano needed to update the hurricane map for the website (still have to update Dev Center one) but wanted to show you what adding the outline looks like... (maybe you already tried but just in case)

We'll have it updated for Dev Center next release

https://cartodb.github.io/carto-vl-maps/website/engine/hurricane-harvey.html

**Comment by Algunenano** [comment]
Looks great!

**Comment by makella** [comment]
fixed with today's release
