### ISSUE TITLE
Outline a guide for the use of global and viewport histogram

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#1266]
as @elenatorro pointed out, we don't have a guide for these topics, so we should start thinking about adding one. 

Related issues:
`globalHistogram` (issue: https://github.com/CartoDB/carto-vl/issues/1033, 
PR: https://github.com/CartoDB/carto-vl/pull/1262)

**Comment by makella** [comment]
@elenatorro and I reviewed her example. I will make one or two modifications PR here:
https://github.com/CartoDB/carto-vl/tree/1266-example-global-viewport-histogram

**Comment by elenatorro** [comment]
🚀
