### ISSUE TITLE
Add "options" parameter to getJoinedValues method in Histograms

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#1267]
## Context

Related with https://github.com/CartoDB/carto-vl/pull/1262

When using the `ramp` expression, you can use the `getLegendData` method to get all the ramp values. You can pass an **options object** to define:

* The number of samples you want to get (useful when you're using the `ramp` with a `linear` expression) -> 10 by default
* The label you want to use to name the 'Others' value. -> 'CARTO_VL_OTHERS' by default

When using a `histogram` expression, it's a common case to use it along with a `ramp` expression. And when you want to set a widget with the information from the `histogram` expression combined with the values from the `getLegendData` ramp method, you use `getJoinedValues` method as follows:

* We have this viz:

```js
const viz = new carto.Viz(`
  @histogram: globalHistogram($featurecla)
  color: ramp($featurecla, bold)
`);
```

* We get the color values:

```js
const colorValues = layer.viz.color.getLegendData().data;
```

* We get the histogram values

```js
const histogramValues = layer.viz.variables.histogram.getJoinedValues(colorValues);
```

As you see, we pass `colorValues` to `getJoinedValues` method. However, if set a different value to the 'others' label, then `getJoinedValues` method would not work properly because it does not allow custom options.

## Expected

We should pass an `options` parameter to `getJoinedValues` to work in a similar way it does for the `getLegendData` method.

## To Do

* Add `options` parameter to `getJoinedValues` method in the `Histogram` class
* Add specs for both `viewportHistogram` and `globalHistogram` expression
* Add integration test using `ramp` + `histogram` expressions

**Comment by VictorVelarde** [comment]
@elenatorro Is this still a blocked one or having GlobalHistogram allows to move on?

**Comment by elenatorro** [comment]
We can start working on that :) I wanted to start first with other tasks on the roadmap, but I'll do that ASAP
