### ISSUE TITLE
Avoid adding 'others' to legend data in buckets for categories

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#1273]
When you're using a ramp with a buckets expression and values are categories, if you'r buckets list contains all the categories in the dataset, it still adds the 'others' value to the data array returned in the `_getLegendData` method.

I remember we've already discussed this in the past and I think we kept it there for simplicity, but since a user had a problem with that I think maybe we should avoid adding the `others` value in this case.

What do you think?

**Comment by makella** [comment]
That makes sense to me... if all of the categories have been assigned, I definitely think we shouldn't have an others category returned for the legend.

If implemented, we will need to rework some examples, guides, etc. to account for that.

**Comment by Jonkat323** [comment]
Any update regarding this? I just encountered the issue again.

**Comment by elenatorro** [comment]
Hi 👋 There're other issues with higher priority at this moment. Since this is not a bug but a feature, meanwhile you can remove the 'others' from the legend. We'll update this issue as soon as we start with it. Thanks!

**Comment by elenatorro** [comment]
It was fixed for CARTOframes project. Please reopen it if this is still happening.
