### ISSUE TITLE
globalMIN/MAX not working on clusters

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#1275]
As seen in [this map](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibWF4aGlfMjAxODA3MDJmMDcyIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IkBjYTogY2x1c3RlckFWRygkdmFsdWUpXG5cbndpZHRoOiByYW1wKGxpbmVhcihAY2EsZ2xvYmFsTUlOKEBjYSksZ2xvYmFsTUFYKEBjYSkpLFsxMCwzMF0pXG5zdHJva2VXaWR0aDogMFxucmVzb2x1dGlvbjogMzJcblxuICAgICAgIiwiZiI6eyJsbmciOi04Ni40MTk0MDU1MTE5MDExMiwibGF0IjozOS45NTg2NTM0NzkyNTU4N30sImciOjMuMTUzMjkzNzU0NjMwNDE4MywiaCI6IlBvc2l0cm9uIiwiaSI6ImRhdGFzZXQifQ==), sizing or coloring clusters by globalMIN/MAX values throws an error.

@elenatorro looked into this, tested, and added a fix in this branch:
https://github.com/CartoDB/carto-vl/tree/1275-fix-global-aggregation-expressions

For the cluster labeling examples, I wanted to create an example where the symbol sizes don't change according to the viewport... trying to do that is what made us stumble upon this issue.

**Comment by makella** [comment]
in addition, global classification isn't working. for example:

`width: ramp(globalQuantiles(clusterCount(), 5), [5,50])`

but viewport classification does:

`width: ramp(viewportQuantiles(clusterCount(), 5), [5,50])`

**Comment by elenatorro** [comment]
🚀
