### ISSUE TITLE
More specifics about supported mobile browsers?

### ISSUE THREAD

**Issue by ztephm** [CartoDB/carto-vl#1284]
cc @makella @VictorVelarde - feel free to re-label this issue

Support received a request from a client mentioning that his examples were not working on mobile.

We've given him this resource:
https://carto.com/developers/carto-vl/support/browser-support/
& we have this example:
https://carto.com/developers/carto-vl/examples/#example-check-for-browser-support

* Is there a list of mobile browsers we do support? 
* Or given that VL uses advanced browser features, is there basic info we can give clients that is more mobile-specific?

**Comment by VictorVelarde** [comment]
Hi @ztephm 

What VL requires is:
    - a modern browser (chrome, firefox, safari...)
    - a good hardware (sorry, no old phones).
    - and WebGL1 + a WebGL extension called OES_texture_float.

Regarding to the last point, as it has been discussed in https://github.com/CartoDB/support/issues/1938, that doesn't cover some mobile devices. The statistics indicate the estimated support for 'smartphones' is:
  - [WebGL1](https://webglstats.com/webgl): 98%
  - [OES_texture_float](https://webglstats.com/webgl/extension/OES_texture_float): 69%

And the web page to test if CARTO VL is supported, in any device, is:
https://carto.com/developers/carto-vl/examples/maps/basics/browser-support.html

In any case, as this is going to be a recurrent topic, IMO we should tackle it from a more global perspective, so I'm pinging here @inigomedina and @ivanmalagon

**Comment by VictorVelarde** [comment]
Hi @ztephm 

What VL requires is:
    - a modern browser (chrome, firefox, safari...)
    - a good hardware (sorry, no old phones).
    - and WebGL1 + a WebGL extension called OES_texture_float.

Regarding to the last point, as it has been discussed in https://github.com/CartoDB/support/issues/1938, that doesn't cover some mobile devices. Check the statistics there.

And the web page to test if CARTO VL is supported, in any device, is:
https://carto.com/developers/carto-vl/examples/maps/basics/browser-support.html

**Comment by elenatorro** [comment]
Closing in favor of https://github.com/CartoDB/carto-vl/issues/1285

I think this is a good candidate for RT cc @CartoDB/rt-managers

**Comment by oriolbx** [comment]
Thanks @VictorVelarde  @elenatorro ! :)
