### ISSUE TITLE
Improve browser and mobile support page

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#1285]
Related issues:
* https://github.com/CartoDB/carto-vl/issues/1284
* https://github.com/CartoDB/support/issues/1938

We currently have this page to explain the browser support for the library https://carto.com/developers/carto-vl/support/browser-support/

However, we don't include information about support in mobile devices, although we provide a couple of useful links. We should add a bit more information about this. I would also add a **simple** table, which is a common thing in these cases.

Useful links:
* https://www.ichemlabs.com/1375
* https://paginas.fe.up.pt/~ruirodrig/pub/sw/webcgf/docs/#!/guide/webgl_on_mobile_platforms
* https://docs.unity3d.com/Manual/webgl-browsercompatibility.html

**Comment by ztephm** [comment]
@ztephm notify SB 21520692 when complete
