### ISSUE TITLE
Let users customize the string 'CARTO_VL_OTHERS'

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/carto-vl#1291]
As a user, if I use a `top` expression, or similar, I would like to be in control of what the string will be for the 'rest' values.

Right now the workaround is applying a map to the resulting data (histogram, for instance) and replacing it there, but I think it would be nice to solve the problem at the root.

**Comment by jorgesancha** [comment]
as discussed @rochoa

**Comment by elenatorro** [comment]
I think we can close this because the use case was for Airship bridges and it's being solved here https://github.com/CartoDB/airship/pull/606. 

If in we need or want to add it later, we can reopen it.
