### ISSUE TITLE
Timestamps: proper support for temporal maps (server-side)

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#130]
Related to https://github.com/CartoDB/renderer-prototype/issues/16

We have support for temporal maps by using numeric properties. However, we don't support native timestamp properties in the Windshaft client.

I think that a good enough implementation would automatically transform a timestamp property into a numeric one (transparently to the user).

I think that a good approach would be to download the minimum and maximum timestamps (as metadata). To later download (in the MVT tiles) the timestamp properties as numbers in the [0,1] range, where 0 means minimum timestamp, and 1 means maximum timestamp.

Since timestamps can have very high resolutions, but most of the times we don't need those, we should have a mechanism for aggregations. After implementing the naive version (without aggregations, setting the timestamp in `dimensions`), we could add new aggregation functions that only works with timestamps, for example: `HOUR(), DAY(), WEEK(), MIN(), SEC(), MSEC())`

**Comment by jgoizueta** [comment]
Interesting fact: Mapnik MVT don't support date/time columns: they're just omitted from the tile:

https://github.com/CartoDB/node-mapnik/blob/v3.6.2-carto/src/mapnik_vector_tile.cpp#L2561-L2593

As a work around we can cast to text `::text`, e.g. in the dimensions expressios

**Comment by rochoa** [comment]
Not a surprise, see https://github.com/CartoDB/Windshaft/issues/103#issuecomment-31860378.

**Comment by davidmanzanares** [comment]
What are the plans for this? https://github.com/CartoDB/renderer-prototype/issues/177 requires to solve this on Maps API or to apply the `::text` workaround

**Comment by davidmanzanares** [comment]
This is more important than we thought. The current approach is not browser independent. For example, this map works on Chrome but crashes on Firefox: https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidGFibGVfMDhfMjVfdG9fMDhfMzAiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IG9wYWNpdHkocmFtcChsaW5lYXIoJHFwZiwwLjAxLDEwKSxidXJneWwpLCRxcGYvMC43NSlcbmZpbHRlcjogdG9ycXVlKGxpbmVhcigkaXNzdWVfdGltZSx0aW1lKCcyMDE3LTA4LTI0VDIwOjE2OjIzWicpLFxuICAgICAgICAgICAgICAgdGltZSgnMjAxNy0wOC0zMVQyMDoyMzoyN1onKSksNSxmYWRlKDAuOSwwLjkpKSIsImYiOnsibG5nIjotOTYuMDQxMDExMjg3ODY1MSwibGF0IjozNC42NzgzNjQyMjgxOTM1N30sImciOjQuMDkzNTI0NzM0MDM0NDA0fQ==

This occurs because `Date.parse` is not well supported

**Comment by rochoa** [comment]
This would be a nice thing to combine with something like https://github.com/uber/kepler.gl/blob/get-started/docs/h-playback.md.

**Comment by jgoizueta** [comment]
Handling of date properties and maximising its precision is solved by #495 for Windshaft and GeoJSON sources. I'm closing this now and have open a new ticket #551 to deal with the remaining questions.
