### ISSUE TITLE
Improve JavaScript error messaging

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#1309]
* Related issues: https://github.com/CartoDB/carto-vl/issues/743
* Related project: CARTOFrames

Context
---

In order to provide a better error feedback, specially for CARTOFrames, we need to test how errors are sent, identify how can we improve them and then implement the required changes.

**Comment by jorgesancha** [comment]
@kukukaka Could we have a chat about this one? Also related to: https://github.com/CartoDB/cartoframes/issues/599

**Comment by elenatorro** [comment]
🚀
