### ISSUE TITLE
Legend icons have a wrong size

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#1342]
- https://carto.com/developers/carto-vl/examples/maps/guides/add-legends/step-8.html
- https://carto.com/developers/carto-vl/examples/#example-image-legend

![](https://user-images.githubusercontent.com/2227572/57123242-68ebbf80-6d81-11e9-9869-2b51c7ca2b32.png)

This could be fixed by using: `-webkit-mask-size: cover;`. But maybe removing the size from the SVG (width, height) could be a solution too.

**Comment by VictorVelarde** [comment]
I'm going for the css fix for the next release

**Comment by Jesus89** [comment]
Fixed: https://github.com/CartoDB/carto-vl/pull/1364
