### ISSUE TITLE
Memory Exhausted for ramps with lots of items

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/carto-vl#1356]
Related tickets:

https://github.com/CartoDB/carto-vl/issues/1227
https://github.com/CartoDB/carto-vl/issues/103

Fiddle: http://jsfiddle.net/d8m3qgz9/3

When styling with a ramp that has lots of inputs, CARTO VL will crash reporting that memory is exhausted.

The example in the jsfiddle uses markers but there's no difference if you use color.

**Comment by VictorVelarde** [comment]
It looks like this is unrelated to textures & those tickets. More details in the PR

**Comment by VictorVelarde** [comment]
Done in v1.3.0
