### ISSUE TITLE
Does globalHistogram for a category field work on a sample?

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/carto-vl#1358]
Some doubts have arisen about the internals of this expression, when using a category (string) field.

cc/ @padawannn

**Comment by VictorVelarde** [comment]
It doesn't although the expression is currently limited to a maximum number of 32768 categories (what should fit most cases)

**Comment by VictorVelarde** [comment]
Have a look at this example for more details:

 - Using this [viz with vancouver_trees](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidmFuY291dmVyX3RyZWVzIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJjb2xvcjogYmx1ZVxud2lkdGg6IDFcbnN0cm9rZUNvbG9yOiB0cmFuc3BhcmVudFxuQGhnOiBnbG9iYWxIaXN0b2dyYW0oJGdlbnVzX25hbWUpIiwiZiI6eyJsbmciOi0xMjMuMDkwNzY5MzU0MDI2OTcsImxhdCI6NDkuMjM4OTE4NTEwNDAxNDV9LCJnIjoxMC41MDY3OTA4ODY1NDcwMzcsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==)

- This is the [underlying request to Maps API for metadata](https://cartovl.carto.com/api/v1/map?api_key=default_public&client=vl-1.2.6&config=%7B%22buffersize%22%3A%7B%22mvt%22%3A1%7D%2C%22layers%22%3A%5B%7B%22type%22%3A%22mapnik%22%2C%22options%22%3A%7B%22sql%22%3A%22SELECT%20%5C%22genus_name%5C%22%2C%5C%22cartodb_id%5C%22%2C%5C%22the_geom_webmercator%5C%22%20FROM%20vancouver_trees%20%22%2C%22aggregation%22%3A%7B%22columns%22%3A%7B%7D%2C%22dimensions%22%3A%7B%22genus_name%22%3A%7B%22column%22%3A%22genus_name%22%7D%7D%2C%22placement%22%3A%22centroid%22%2C%22resolution%22%3A1%2C%22threshold%22%3A1%7D%2C%22vector_extent%22%3A2048%2C%22vector_simplify_extent%22%3A2048%2C%22dates_as_numbers%22%3Atrue%2C%22metadata%22%3A%7B%22geometryType%22%3Atrue%2C%22columnStats%22%3A%7B%22topCategories%22%3A32768%2C%22includeNulls%22%3Atrue%7D%2C%22dimensions%22%3Atrue%2C%22sample%22%3A%7B%22num_rows%22%3A1000%2C%22include_columns%22%3A%5B%22genus_name%22%2C%22cartodb_id%22%5D%7D%7D%7D%7D%5D%7D) which reads as
```
https://cartovl.carto.com/api/v1/map?api_key=default_public&client=vl-1.2.6&config={"buffersize":{"mvt":1},"layers":[{"type":"mapnik","options":{"sql":"SELECT \"genus_name\",\"cartodb_id\",\"the_geom_webmercator\" FROM vancouver_trees ","aggregation":{"columns":{},"dimensions":{"genus_name":{"column":"genus_name"}},"placement":"centroid","resolution":1,"threshold":1},"vector_extent":2048,"vector_simplify_extent":2048,"dates_as_numbers":true,"metadata":{"geometryType":true,"columnStats":{"topCategories":32768,"includeNulls":true},"dimensions":true,"sample":{"num_rows":1000,"include_columns":["genus_name","cartodb_id"]}}}}]}
```

- That executes this [code in Maps API](https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/utils/query-utils.js#L84-L93) which in this particular case is:
```sql
 SELECT genus_name AS category, COUNT(*) AS frequency
   FROM (SELECT genus_name, cartodb_id, the_geom_webmercator FROM vancouver_trees) AS __cdb_query
 GROUP BY genus_name ORDER BY 2 DESC
 LIMIT 32768
```

- So there is a limit in the **number of categories**, with `LIMIT`, but not the records that feed them (the `__cdb_query` itself).

- The frequencies for the first 32768 categories are good to rely on.

**Comment by padawannn** [comment]
So I'm understanding that globalHistogram will return all categories, with their frequency,  while they are less than 32768, right ? Yes, this works for most cases.
