### ISSUE TITLE
Fix globalQuantiles expression when getting legend data

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#1370]
From https://github.com/CartoDB/cartoframes/issues/724

Context
=== 

`globalQuantiles` expression when used in a `ramp` is not returning values properly. Here there are the cases in the internal editor. Open the console and run `layer.viz.color.getLegendData()` to debug:

* Case 1: [Points example](http://localhost:8080/examples/editor/#eyJhIjoidG9ybmFkb3NfMTk1MF8yMDE3IiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogN1xuc3Ryb2tlV2lkdGg6IDBcbmNvbG9yOiByYW1wKGdsb2JhbFF1YW50aWxlcygkbG9zcywgNSksIHB1cnBvcikiLCJmIjp7ImxuZyI6LTEwMS4yMTYxNTMxMjU3ODg4OCwibGF0Ijo0Mi45Nzg2NTA5MTkzNTc2NX0sImciOjMuMTkxODg0MzI4OTAwMDcxNiwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoiZGF0YXNldCJ9) 

Legend data:
```
[-Infinity, Infinity]
[-Infinity, 0.001]
[0.001, 2]
[2, 4]
[4, Infinity]
```

* Case 2: [Lines example](http://localhost:8080/examples/editor/#eyJhIjoidXNfcHJpbWFyeXJvYWRzX2FjY2lkZW50c18yMDE1IiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogN1xuc3Ryb2tlV2lkdGg6IDBcbmNvbG9yOiByYW1wKGdsb2JhbFF1YW50aWxlcygkY291bnQsIDUpLCBwdXJwb3IpIiwiZiI6eyJsbmciOi0xMDEuMjE2MTUzMTI1Nzg4ODgsImxhdCI6NDIuOTc4NjUwOTE5MzU3NjV9LCJnIjozLjE5MTg4NDMyODkwMDA3MTYsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==)

Legend data:

```
[-Infinity, Infinity]
[-Infinity, Infinity]
[-Infinity, Infinity]
[-Infinity, 1]
[1, Infinity]
```

**Comment by Jesus89** [comment]
I would be nice that instead of Infinity or -Infinity, it returned the global min/max to have more meaningful legends.

**Comment by elenatorro** [comment]
I like this idea, I was thinking about how to implement it for the rest of classifiers.
