### ISSUE TITLE
Support LineString and Polygon in MVT decoder

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#138]
`api/client/windshaft`

**Comment by VictorVelarde** [comment]
There are two functions that already deal with this: `decodeLines` and `decodePolygons`at `mvt/feature-decoder`. See here: https://github.com/CartoDB/carto-vl/blob/25261d7afbbe1c6d54f789bc2a37d7481202b778/src/client/mvt/feature-decoder.js#L11
