### ISSUE TITLE
Windshaft-carto-vl docker image is broken

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#1411]
Context
======

We're using a **custom** windshaft docker image for the CARTO VL e2e tests. Due to some last changes, we've had to add a little modification when setting the express router, as we can see in this PR https://github.com/CartoDB/carto-vl/pull/1403

We need to update the docker image properly to fit the last changes.

- Docker configuration:  [/test/acceptance/docker](https://github.com/CartoDB/carto-vl/tree/master/test/acceptance/docker)
- Developers guide about [e2e tests](https://github.com/CartoDB/carto-vl/blob/master/DEVELOPERS.md#acceptance-tests-e2e-tests)
- Example of a [failing build in Circle CLI](https://circleci.com/gh/CartoDB/carto-vl/22406)

**Comment by elenatorro** [comment]
Although I've been able to rebuild the docker images and fix some errors, I'm still having issues when configuring the database. I'm removing the `rt-frontend` label for now, we need help from backend team to fix this issue cc @VictorVelarde @alrocar

**Comment by alrocar** [comment]
I don't know much about that Docker image, how can we reproduce the issue/where's the Dockerfile?

**Comment by elenatorro** [comment]
The only documentation I've found about how to build the images is in the [DEVELOPERS](https://github.com/CartoDB/carto-vl/blob/master/DEVELOPERS.md#acceptance-tests-e2e-tests) guide, the way to reproduce it is to run the e2e tests (which are the ones that are failing in CI). The Dockerfile and the docker configuration is in the [/test/acceptance/docker](https://github.com/CartoDB/carto-vl/tree/master/test/acceptance/docker) directory in CARTO VL.

**Comment by alrocar** [comment]
The PR is back to 🍏 

Assigning back to @elenatorro for acceptance.

**Comment by elenatorro** [comment]
Merged 🚀
