### ISSUE TITLE
Blog map issue

### ISSUE THREAD

**Issue by StevePIsaac** [CartoDB/carto-vl#1413]
Hey team! 

It seems that this CARTO VL map on one of our recent blog posts isnt working. 
https://carto.com/blog/retail-revenue-prediction-data-science/

Any help would be appreciated! cc: @makella

**Comment by elenatorro** [comment]
Fixed by @makella ✨

For these kind of visualizations, instead of using personal accounts for generating the final result, it'd be great to use a common account that anyone can access in case there's a failure 👍
