### ISSUE TITLE
Questions about backend support

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/carto-vl#144]
CartoGL will need some backend support (changes in existing features like aggregation and possibly new features).

This is to discuss some decisions about the desing of this API and the implications for the styling language and rendering logic.

## Preliminaries

Cartogl is concerned with two **API**s in relattion to data handling:

* Its internal API: renderer <-> data providers (clients: Windshaft, GeoJSON,..)
* The CARTO backend (Windshaft)

For the latter we currently suffer from some kind of mismatch, but we'll need to live with it for the time being:

* The tiler API is designed to create maps (multiple layers, styles, widgets, ...)
* But cartogl needs just a data service (metadata, aggregation, filtering, ...)

(I think it's good to have this mismatch in mind for future evolution of the APIs)

These are the current renderer unfullfilled needs from the backend API:

* Dimensions (using quick undocumented hack)
* Filtering (server side unaggregated data is filtered/clienter side aggregated data, and manipulates SQL queries
* Metadata (using SQL API)
* Sampling (done with SQL API now)
* Time columns: *disappear* in MVT; should be normalized, aggregated into units; not handled in renderer currently
  (only simple ordinals are used as time)
* Normalization/encoding of categories and times (should it be provided by the server?)

## Issues

I think it's dimensions and filtering where we should take some decisions first. I see the other stuff (metaata, sampling and normalization) mostly independent of these questions.

### Dimensions

Currently using the hack that basically allows building the GROUP BY clause with arbitrary expressions.
Arbitrary expressions haven't been used, though, except very recently for casting time columns to text (so they pass through Mapnik MVTs).

Currently, column references (style properties) can appear either inside aggregation functions (possibly multiple times with different functions) or they are used *naked*. In the latter case they're added to dimensions (i.e. to the GROUP BY).

In most usual cases this doesn't seem to be a problem: aggregation is quick and the size of the results not too big, but in principle, aggregating for numeric, time or text columns with many distinct values could be a problem both in performance and results size.

The *logical*/*consistent* API for aggregation would allow only these kind of dimensions:
* Category (numerical or text columns with few distinct values)
* Time column + unit of aggregation (year, month, day, hour, ...)
* Numerical column + range set (break points for classification)

Then, to use anything outside these cases for styling, e.g. a continuous temperature value, we'd need to omit aggregation (so no other property could be aggregated, and the dataset wouldn't be reduced spatially).

So we would have to quite different options for rendering a map:

Using aggregation:

* Large datasets are not a problem
* Aggregation functions can be used, except for categories
* Multiple different aggregation functions can be used with same column
* To use a non-category numeric column ranges must be applied (so no continuous ramps)
* Units must be applied to time columns to use them in styles

 Not using aggregation:

* Large datasets can be a problem (maximum size of dataset?)
* No aggregation function can be used in any style function
* Any column can be used in styles including continuous values (ramps)

So, the complication is mostly to support non-category text and numbers; the first is problably useful for labels so we could obviate it now. Then, a possible way to simplify the situation would be to have an implicit AVG aggregation whenever a numeric property is used, which is not a category or explicitly ranged.

An another thing: who decides which is a category? It could be fixed by the server/metadata (based on stats of distinct values) or it could be definable by the styles (but that may be dangerous).

#### Style language

If we require (or at least allow) units for time dimensions and ranges to discretise numeric dimensions, how would that reflect in the style language? I see two options:

Declare units/ranges to be used with a property

```
time_units: @temperature, hour
ranges: @age, 20, 30, 60
```

Wrap every use of the property:

```
width: Time(@temperature, hour)
width: Ranged(@age, 20, 30, 60)
```

> If we could bend the syntax a little I would go for `@temperature[hour]`
> and `@age[20,30,60]` in those cases.

Also, this ranges/classification stuff can be confusing for the user, since we already have ramps, etc.
(note that ramps have continuous values between break points; ranges have only a discrete set of values).

### Filtering

When data is aggregated there are two kinds of filtering we may wish to apply to the data:
* pre-aggregation (SQL-WHERE conditions)
* post-aggregation (SQL-HAVING conditions)

Both can have applications when styles, consider this, where we have lots of temperatures for different places and times:

```
color: ramp(AVG(@temperature), tealrose)
```

Then filtering the aggregated data would reduce the number of aggregated points to focus only on places where it freezes most of the time.

```
filter: AVG(@temperature) < 0
```

But filtering the data before aggregation would instead reduce a lot the original data but produce probably more results (most places freeze at some time). Here we would fucus on the average temperatures when not freezing:

```
filter: @temperature < 0
```

Currently the renderer inconsistently applies filters to the aggregated data in the client when the dataset is not too large and requires the server to filter the data before aggregation in other cases.

The post-aggregation filtering can be performed either in the client or server, but the pre-aggregation filters can only applied at the server.

Supporting both kinds of aggregation will be a little messy:
* The user must understand the differences
* The rendering library has to request data again every time thatpre-aggregation filters change. For other filters it can choose when to do so.

Also, post-aggregation filters fit naturally in the aggregation API of the tiler:
we can add a filters property where we can assign conditions to the aggregated columns defined, e.g.

```javascript
{
  columns: {
    avg_temp: AVG(temperature)
  },
  filters: {
    avg_temp: {
      max: 0.0
    }
  }
}
```

Or perhaps

```javascript
{
  columns: {
    avg_temp: AVG(temperature)
    filter: { max: 0.0 }
  }
}
```

> Now, what about filters on dimensions? Where does it fit in the API? Here pre or post-agregattion should yield the same results, so that's just an implementation detail.

But it's less clear where pre-aggregation filtering fits.
For queries (rather than datasets) it could be intrdouced in the SQL.

We already have some filtering in the Maps API, to support widgets:
* Some widgets have filtering parameters; the values for these parameters are not included in the MapConfig, but provided as a separate parameter for map instantiation and for requesting dataviews.
* The internal map configuration we keep stores three forms of each data query, with different combinations of widget filters applied.

Adding additional filtering parameters in layers (that would have to be integraged to all the queries handled in the MapConfig) feels to me like a hack very specific for the use of carto.gl, and will introduce some complications when widgets are also present.

## Decisions, decisions

We should choose our options in this decision tree (unless someone comes with something different):

* Can we keep the current hack of allowing any column in dimensionss?
  * Yes, we always use aggregation, so everything's simple with styles. There's no question of pre/post aggregation; adding filters to the aggregation API (for both columns and dimensions) would suffice.
  * No, we should use proper dimensions. Then, can we always have aggregation?
    * Yes, using implicit AVG. As before filters are needed only for aggregation, so we're happy chaps.
    * No, we must support the non-aggregation case to use smooth numeric values (so more complexity in the styles/renderer). Now, can be live with only after-aggregation filtering?
      * Yes!, any pre-aggregation filtering could be done in the source query.
      * No, we want it all!!

**Comment by jgoizueta** [comment]
A couple of things I've been forgetting:

* The renderer must support the non-aggregated (in the backend) case, because for example polygons cannot be aggregated with the tiler API
* The client does pre-aggregation filtering (when data is not aggregated in the server) and the client may also re-aggregate the data in some cases

**Comment by davidmanzanares** [comment]
Nice report!

I'm clearly in favor of keeping the existing `dimensions`, as you've said it was created as a "quick undocumented hack", but that doesn't mean it is intrinsically a hack. I feel the opposite way actually. Keeping `dimensions` simplifies the API, client code and server code by not differencing between aggregation and not aggregation without avoiding use cases.

For example, the idea of diving a continuous numeric property can probably achieve much better results than having the property on dimensions. But I think that 90% of the times, `dimensions` is going to be good enough, and we avoid the problem of exposing the discretization to the user. For the 10%, we can have expressions to do exactly that, and we can choose to do it transparently in some cases where by looking at the style we can infer the breakpoints.

I think there three main issues with the current `dimensions`: 

- It allows for arbitrary expressions. As you've said, cartogl isn't abusing that feature, and I think it would be better to disallow arbitrary expressions, just like aggregation only allows for columns.
- It was a quick, undocumented feature developed as a hack. This is a current problem, but it is not inherent to the dimensions concept. Of course, we shouldn't we depending on this kind of feature too long, so we must choose to fully support dimensions or to deprecate it.
- Performance when the property can have many values (numeric properties and some timestamps). I wouldn't expect such a dramatic performance cost. I expect that the cost of this is an unnecessary sort per grid-cell results, not so bad I hope. Apart from this, the result size would be big, but if that is a problem we may want to add your idea of discretizing a continuous numeric property with a new aggregation function on Maps API (with the respective expression on cartogl).

**Comment by jgoizueta** [comment]
Now, since we must support non-aggregated backend data (at least for polygons, it probably for small datasets), and we also want to use aggregation to be able to handle large datasets efficiently, the questions I see now are:

Do we want the library to decide automatically when to use aggregation? (note that in some cases, as for polygons, this is dictated by the backend) Otherwise, how can the user, i.e. the style language control aggregation?

When not using backend aggregation I assume the library will perform aggregation in the client when required. The client could filter before or after aggregation. Should the user have control of this?

When using aggregation, 
* Should we apply implicit AVG to non-category properties without an explicit aggregation?
* Should we only apply filters after aggregation?
