### ISSUE TITLE
Implement "flat-corner" for line rendering

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#185]
For little angles the sinus is also little and therefore the corner vertices may increase a lot. This is not a desired behavior:

![selection_089](https://user-images.githubusercontent.com/2227572/37584566-51ff5354-2b56-11e8-8683-adb2e95f577b.png)

A solution is to add a limit for the angle and then "crop" the corner. Inkscape (the vector graphics editor) applies the following criteria.

![line-flat-vertex](https://user-images.githubusercontent.com/2227572/37584314-4759b238-2b55-11e8-8c5f-319e4f7c3aff.gif)

**Comment by makella** [comment]
@jesus I am wondering if a line artifact that I am noticing is a result of this as well.

It appears at a few zooms and then disappears.

It might be a little hard to see, but it is the diagonal line in this image:

<img width="392" alt="screen shot 2018-03-19 at 2 26 11 pm" src="https://user-images.githubusercontent.com/1566273/37620495-07d324b4-2b82-11e8-9ad0-34fb189f3d58.png">

Here is a gif of zooming in/out so you can see when it appears (I try and point to it with my cursor a few zooms in):

![line-artifact](https://user-images.githubusercontent.com/1566273/37620570-39984790-2b82-11e8-8ca7-bb045ad1be57.gif)

**Comment by Jesus89** [comment]
Hi @makella!

Yes, those lines  may be related to this issue. It makes sense that they appear when zooming in/out. Thanks.

**Comment by rochoa** [comment]
@makella, do you mind taking a bit of time to test this? 🙏

**Comment by makella** [comment]
yesss! will provide some feedback today

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/carto-vl/pull/219
