### ISSUE TITLE
Add local and global maximum, minimum and average value functions

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#19]
Add: ~globalMax(), globalMin(), globalAvg(), viewportMax(), viewportMin() and viewportAvg()~

And ~globalPercentile($property, 99) and viewportPercentile(....)~

All functions are done, but viewport ones only work with points and global ones don't take filters into account.

Example: `viewportMax($amount)` should return the maximum amount present in the current viewport, evaluation of the function should be done automatically by the Core Renderer each time the map is panned or zoomed in or out.

**Comment by davidmanzanares** [comment]
Example (be sure to zoom in):

https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiOGExNzRjNDUxMjE1Y2I4ZGNhOTAyNjRkZTM0MjYxNDA4N2M0ZWYwYyIsImMiOiJkbWFuemFuYXJlcy1kZWQxMyIsImQiOiJjYXJ0by1zdGFnaW5nLmNvbSIsImUiOiJ3aWR0aDogc3FydCgkYW1vdW50LzUwMDApKjEwKih6b29tKCkvNDAwMCswLjAxKSoxLjVcbmNvbG9yOiBvcGFjaXR5KGhzdigwLCAoKCRhbW91bnQvdmlld3BvcnRNYXgoJGFtb3VudCkpKSwxKSwgMC43KSIsImYiOnsibG5nIjoyLjE3LCJsYXQiOjQxLjM4fSwiZyI6MTN9

cc: @makella

**Comment by makella** [comment]
@davidmanzanares !!!!

LOOOOK! Yay!

Proportional symbols! where we can control the max symbol size (in this case 75)!!!

https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoiY291bnR5X3BvaW50c193aXRoX3BvcHVsYXRpb25cbiIsImIiOiI0ZDIxMjM3NTM4NmJhZjFhMDliYjgyNjA4YzY0ODIxODhkYTNhNWIwIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJjYXJ0by5jb20iLCJlIjoid2lkdGg6ICAgNzUqc3FydCgkZXN0aW1hdGVfdG90YWwpL3NxcnQodmlld3BvcnRNYXgoJGVzdGltYXRlX3RvdGFsKSlcbmNvbG9yOiBvcGFjaXR5KGhzdigwLjczLDAuNjksMC44OSksMC44KVxuc3Ryb2tlV2lkdGg6IDJcbnN0cm9rZUNvbG9yOiBoc3YoMC43MywwLjY5LDEpXG5cblxuXG5cbiIsImYiOnsibG5nIjotOTguMzM2NzQ3MjMyNDIwOTgsImxhdCI6NDUuMzg0MTE1NDEwMDQ0N30sImciOjMuMzUwMjYxNzUxNzE3MDMyM30=

And BCN example with `$amount`
https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiOGExNzRjNDUxMjE1Y2I4ZGNhOTAyNjRkZTM0MjYxNDA4N2M0ZWYwYyIsImMiOiJkbWFuemFuYXJlcy1kZWQxMyIsImQiOiJjYXJ0by1zdGFnaW5nLmNvbSIsImUiOiJ3aWR0aDogNTAqc3FydCgkYW1vdW50KS9zcXJ0KHZpZXdwb3J0TWF4KCRhbW91bnQpKVxuY29sb3I6IG9wYWNpdHkocmFtcCgkY2F0ZWdvcnksYm9sZCksMC43KVxuc3Ryb2tlQ29sb3I6IHJhbXAoJGNhdGVnb3J5LGJvbGQpXG5zdHJva2VXaWR0aDogMVxuIiwiZiI6eyJsbmciOjIuMTcwNDAzMjQ1OTQ3NDU0NywibGF0Ijo0MS40MDUzODc4MDUyMTEzNX0sImciOjEzLjQ0MDgxNzc2NTczMTA5NH0=

buuut, why doesn't this work?

https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoicG9wX2RlbnNpdHlfcG9pbnRzIiwiYiI6IjRkMjEyMzc1Mzg2YmFmMWEwOWJiODI2MDhjNjQ4MjE4OGRhM2E1YjAiLCJjIjoibWFtYXRhYWtlbGxhIiwiZCI6ImNhcnRvLmNvbSIsImUiOiJ3aWR0aDogem9vbSgpXG5jb2xvcjogcmFtcCh2aWV3cG9ydE1JTigkZG4pLCB2aWV3cG9ydE1BWCgkZG4pLHN1bnNldClcblxuXG5cbiIsImYiOnsibG5nIjo2Ny4wNzcwNzUzMDMyMTIwNCwibGF0IjoyNy4xMDg0MzkxMjc4NTMzODd9LCJnIjoyLjEzMTA5NDU4NTM1MTc1NzN9

**Comment by makella** [comment]
@davidmanzanares OH!!

I think I got it, right?

https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoicG9wX2RlbnNpdHlfcG9pbnRzIiwiYiI6IjRkMjEyMzc1Mzg2YmFmMWEwOWJiODI2MDhjNjQ4MjE4OGRhM2E1YjAiLCJjIjoibWFtYXRhYWtlbGxhIiwiZCI6ImNhcnRvLmNvbSIsImUiOiJ3aWR0aDogem9vbSgpXG5jb2xvcjogcmFtcChsaW5lYXIoJGRuLHZpZXdwb3J0TUlOKCRkbiksdmlld3BvcnRNQVgoJGRuKSksc3Vuc2V0KVxuXG5cblxuIiwiZiI6eyJsbmciOjE1LjY1NTQzNjk4ODUwNzk3MiwibGF0IjoyNy40MjcxMjgyNDY4NTc2Nzd9LCJnIjowLjY2OTAwOTgxNDkzNjcwNTJ9

**Comment by davidmanzanares** [comment]
Yes! You totally got it!

**Comment by davidmanzanares** [comment]
Global operators are done too: https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibW5tYXBwbHV0byIsImIiOiIiLCJjIjoiZG1hbnphbmFyZXMiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiByYW1wKGxpbmVhcihsb2coJG51bWZsb29ycyksIDEgbG9nKGdsb2JhbE1heCgkbnVtZmxvb3JzKSkpLCBFYXJ0aCkiLCJmIjp7ImxuZyI6LTczLjk4MDg4ODk5Mzc1MzkyLCJsYXQiOjQwLjc0MDkxMzMzOTY1MzV9LCJnIjoxMi4wNTgyMTg4MzM0NjM0OTd9

**Comment by makella** [comment]
NICE! Will try it out!!

**Comment by rochoa** [comment]
@makella, can you help us testing this one? 🙏

**Comment by davidmanzanares** [comment]
I just discovered why this wasn't closed, the support is for points only.

**Comment by makella** [comment]
I revisited the point examples, and tested AVG in addition to MIN/MAX. 

Looks good to me!

**Comment by davidmanzanares** [comment]
Completed by https://github.com/CartoDB/carto-vl/pull/364
