### ISSUE TITLE
Maps API error control

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#210]
Right now we are not checking that Maps API success on instantiation. This means that when there is a problem the client tries to download tiles from with an `undefined` layergroupID.

We should control this error condition.

**Comment by davidmanzanares** [comment]
Situations:

- [ ] Invalid username. The server returns HTTP 302 redirecting to http://carto.com/noneuser.html . Should the API be changed? I would expect a 4xx not a 3XX. Moreover this finally fails with a `Response for preflight is invalid (redirect)`
- [ ] invalid apiKey with a public dataset: defaults to public one. Is this expected? or an error should be thrown?
- [ ] invalid apiKey with a private dataset. The server returns a 403 with an error in a JSON. I think we should check for a 403, and output an error with "invalid apikey..." in that case.
- [ ] styling with property names that don't exist. The server returns a 404 with an error like: `{"errors":["column \"wadus\" does not exist"]...`. I think we should use that error message and just retransmit it (wrapping it accordingly).

**Comment by elenatorro** [comment]
After reading the different tasks we should start next, I think this one is highly related with:

* **Unify API Promises/Error management** https://github.com/CartoDB/carto-vl/issues/342
* **Use factory instead constructor to create layers** https://github.com/CartoDB/carto-vl/issues/321

In my opinion, we could solve this one along with #342.

#321 would be blocked until it gets solved. 
What do you think? cc @rochoa

**Comment by davidmanzanares** [comment]
I've rechecked the previous situations since there have been some Maps API changes:
Situations:

- [ ] Invalid username. The server returns HTTP 302 redirecting to http://carto.com/noneuser.html . Should the API be changed? I would expect a 4xx not a 3XX. Moreover, this finally fails with a `Response for preflight is invalid (redirect)`
- [ ] invalid apiKey with a public dataset: Maps API returns an error that we should control
- [ ] invalid apiKey with a private dataset: Maps API returns an error that we should control
- [ ] styling with property names that don't exist. The server returns a 404 with an error like: `{"errors":["column \"wadus\" does not exist"]...`. I think we should use that error message and just retransmit it (wrapping it accordingly).

I'm going to start working on the last 3 situations, the first situation will require work from Maps API if we decide to change the public API (which I think we should).

**Comment by rochoa** [comment]
About the first one, as we are using _subdomains_ is not that easy. The request is not even routed to the Maps API. As there is no valid entry for the subdomain, it redirects to the mentioned URL, which is the one returning a 404 error.

**Comment by davidmanzanares** [comment]
Thanks for your help! #903 fixed everything
