### ISSUE TITLE
Add columns/aggregations  to the source definition

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/carto-vl#252]
Related to #61

Define the columns (including aggregated columns) to be requested from the data source in the Source definition, as a second parameter in the constructor.

Columns present in the data are needed for:
* use as style properties
* use in interactivity (present in feature objects)

Currently columns/aggregations are implicitly defined by the style definitions.
Aggregations are defined, with automatically generated alias when properties appear inside aggregation functions.

Any column to be used in interactivity should be defined in the source.
Column can be aggregated by defining an aggregation function and an alias for the result.
A property may appear with multiple aggregations, but if a property appears aggregated it cannot appear without aggregation.

To facilitate the creation of simple maps, columns used in styles without aggregation need not to be defined in the source: any property that appears in a style will automatically be added to the source if not present.

To avoid breaking existing maps style aggregation functions will also be maintained for the time being.
We could do this:
* if `AGGR(@property)` is used (AGGR an aggregation function), then check the source for an alias to it and use the alias; otherwise add it to the source with an automatically generated alias.

## Format of the column definitions

We already have a JSON spec to define aggregated columns in the MAPs API:
https://carto.com/docs/carto-engine/maps-api/tile-aggregation/#columns
We can base this on that, but here we also need to define columns without aggregation;
here's some options to do so:

### Separate properties for columns and aggregations

```javascript
{
    columns: ["category1", "category2"],
    aggregated_columns: {
      "value": {
          "aggregate_function": "avg",
          "aggregated_column": "value"
      },
      "total": {
          "aggregate_function": "sum",
          "aggregated_column": "value"
      }
}
```

### Single object

```javascript
{
    "category1": {
        "column": "category1"
    },
    "category2": {
        "column": "category2"
    },
    "value": {
        "aggregate_function": "avg",
        "aggregated_column": "value"
    },
    "total": {
        "aggregate_function": "sum",
        "aggregated_column": "value"
    }
}
```

### Single object, less verbose (=Maps API aggregation.dimensions)

```javascript
{
    "category1": "category1",
    "category2": "category2",  
    "value": {
        "aggregate_function": "avg",
        "aggregated_column": "value"
    },
    "total": {
        "aggregate_function": "sum",
        "aggregated_column": "value"
    }
}
```

### Abbreviated array

```javascript
["category1", "category2", ["value", "avg", "value"], ["total", "sum", "value"]]
```

### Abbreviated array with expressions

```javascript
["category1", "category2", "value=avg(value)", "total=sum(value)"]
```

## Implementation notes

The implementation of this feature should be based on the `filters` branch to avoid too many conflicts. There's a couple of interesting bits already there:
* [Check if aggregation is needed but not available](https://github.com/CartoDB/renderer-prototype/blob/filters/src/client/windshaft.js#L199)
* [Aggregation alias handling](https://github.com/CartoDB/renderer-prototype/blob/filters/src/core/schema.js#L44-L58)

##  Actions

- [x] Define source constructor parameters and format for column/aggregations definitions
- [x] Implement handling of columns/aggregations in the source.
- [x] implement merging of properties and aggregation references in styles into source columns
- [x] Instantiate the map with all the columns/aggregations

**Comment by Jesus89** [comment]
I like this one: 

```js
{
    columns: ["category1", "category2"],
    aggregations: {
      "value": {
          "function": "avg",
          "column": "value"
      },
      "total": {
          "function": "sum",
          "column": "value"
      }
}
```

I have a question @jgoizueta. Can we use the column name as alias for the agg? I think we should force the user to use aliases != column names.

**Comment by Jesus89** [comment]
Using this format:

```
{
    columns: ["category1", "category2"],
    aggregated_columns: {
      "value": {
          "aggregate_function": "avg",
          "aggregated_column": "value"
      },
      "total": {
          "aggregate_function": "sum",
          "aggregated_column": "value"
      }
}
```

We could add sugar in the future

**Comment by jgoizueta** [comment]
As per our talk (@Jesus89 @IagoLast & me):
We'll go with the first option now:

```javascript
{
    columns: ["category1", "category2"],
    aggregated_columns: {
      "value": {
          "aggregate_function": "avg",
          "aggregated_column": "value"
      },
      "total": {
          "aggregate_function": "sum",
          "aggregated_column": "value"
      }
}
```

Because it's the closer to what we probably need internally. That way we get to implement it quickly and find out possible problems/limitations.
If we see another format is preferable for users (e.g. the last with expressions, because it's more consistent with the styling language) we can add a translation from it later (as long as we haven't gone public yet)

A nice thing about this format is that we can extend it easily, e.g. to add other aggregation parameters, such as placement.
