### ISSUE TITLE
Spiky Looking Polygons

### ISSUE THREAD

**Issue by michellemho** [CartoDB/carto-vl#281]
Ran into some spiky-looking polygons while experimenting with using CARTO VL locally. When zoomed out, the polygons look OK. However, upon zooming in, the polygons start looking oddly spiky. However, when I use the renderer-prototype examples UI, it seems to look OK. Any ideas what's happening?

**From zoomed out, looks ok**
![image](https://user-images.githubusercontent.com/12551177/38568134-e35e213e-3cb5-11e8-83e0-6bd9a9567dab.png)

**Now zoomed in... spiky polygons**
![image](https://user-images.githubusercontent.com/12551177/38568155-efb3be8a-3cb5-11e8-8569-e4d0ca8bdfd2.png)

**Looks okay in CARTO builder**
![image](https://user-images.githubusercontent.com/12551177/38568165-f65c5954-3cb5-11e8-9030-8b9386675f93.png)

**Looks okay in the renderer-prototype examples**
[Link to renderer-prototype example](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoiYWxscGx1dG9uZXdfbV9jIiwiYiI6IiIsImMiOiJjYXJ0b3VyYmFuZGVtbyIsImQiOiJodHRwczovL2NhcnRvdXJiYW5kZW1vLmNhcnRvLmNvbSIsImUiOiJjb2xvcjogaHN2KCR6b25lZGlzdDEsIDAuNywgMS4pXG4iLCJmIjp7ImxuZyI6LTc0LjAyMzk1NDkzMDE2MzQ4LCJsYXQiOjQwLjY1OTQ5MTY4NTg3ODY2fSwiZyI6OC44NzQ1OTY1Mzk5NTE5N30=)
![image](https://user-images.githubusercontent.com/12551177/38569055-53167c04-3cb8-11e8-8562-5acdf3887606.png)

**The code**
```
<!DOCTYPE html>
<html>
<head>
  <title>Single layer | CARTO</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <!-- Include CARTO GL JS -->
  <script src="../dist/carto-gl.js"></script>
  <!-- Include CARTO Mapbox GL JS fork -->
  <script src="../vendor/mapbox-gl-dev.js"></script>
  <!-- Include Mapbox GL CSS -->
  <link href="../vendor/mapbox-gl-dev.css" rel="stylesheet" />
  <style>
    body { margin: 0; padding: 0; }
    #map { position: absolute; height: 100%; width: 100%; }
  </style>
</head>
<body>
  <div id="map"></div>
  <script>
    // Create a mapbox basemap
    const map = new mapboxgl.Map({
      container: 'map',
      style: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
      center: [-73.935242,40.730610],
      zoom: 12,
      pitchWithRotate: false,
      dragRotate: false,
      touchZoomRotate: false
    });

    map.dragRotate.disable();

    // Login into your CARTO account
    carto.setDefaultAuth({
      user: 'cartourbandemo',
      apiKey: 'none'
    });

    // Set the source of your data
    const source = new carto.source.Dataset('allplutonew_m_c');
    // Set the look and feel of your data
    const style = new carto.Style(`
        color: hsv($zonedist1, 0.7, 1.)
    `
    );
    // Create a new layer
    const layer = new carto.Layer('layer', source, style);
    // Add the new layer to the map
    layer.addTo(map, 'watername_ocean');
  </script>
</body>
</html>
```

**Comment by Jesus89** [comment]
Hi @michellemho I have deployed the latest master changes into gh-pages.

- Could you try again [the example in gh-pages](https://cartodb.github.io/carto-vl/example/mapbox.html#eyJhIjoiYWxscGx1dG9uZXdfbV9jIiwiYiI6IiIsImMiOiJjYXJ0b3VyYmFuZGVtbyIsImQiOiJodHRwczovL2NhcnRvdXJiYW5kZW1vLmNhcnRvLmNvbSIsImUiOiJjb2xvcjogaHN2KCR6b25lZGlzdDEsIDAuNywgMS4pXG4iLCJmIjp7ImxuZyI6LTc0LjAyMzk1NDkzMDE2MzQ4LCJsYXQiOjQwLjY1OTQ5MTY4NTg3ODY2fSwiZyI6OC44NzQ1OTY1Mzk5NTE5N30=)?
- Could you update your master branch, `yarn build`, and try again the example in local?

Btw, could you attach the following information?
- Computer info: OS version, Graphics card
- Browser information

Thanks!

**Comment by michellemho** [comment]
Thanks @Jesus89 !

Computer info: OS X 10.11.6 (15G18013)
Graphics Card: Intel HD Graphics 5000
Browser: Version 65.0.3325.181 (Official Build) (64-bit)

I checked in the gh-pages and it looks okay again.

I couldn't run `yarn build`, any ideas? Here's the error:
```
yarn run v1.3.2
warning ../package.json: No license field
$ yarn build:dev && yarn build:min
warning ../package.json: No license field
$ webpack --config webpack/webpack.config.js
Hash: 4963b7e615eeed65e00b
Version: webpack 3.11.0
Time: 1276ms
          Asset    Size  Chunks                    Chunk Names
    carto-vl.js  561 kB       0  [emitted]  [big]  main
carto-vl.js.map  621 kB       0  [emitted]         main
   [2] ./src/core/style/functions.js 10.6 kB {0} [built]
  [11] ./src/client/rsys.js 4.77 kB {0} [built]
  [12] ./src/core/style/expressions/animate.js 1.84 kB {0} [built]
  [13] ./src/api/source/base.js 586 bytes {0} [built]
  [14] ./src/core/style/expressions/blend.js 2.61 kB {0} [built]
  [29] ./src/api/setup/auth-service.js 1.91 kB {0} [built]
  [30] ./src/api/setup/config-service.js 1.21 kB {0} [built]
  [31] ./src/api/layer.js 11.1 kB {0} [built]
  [32] ./src/api/style.js 12.1 kB {0} [built]
  [34] ./src/api/map.js 3.87 kB {0} [built]
  [35] ./src/index.js 1.27 kB {0} [built]
  [60] ./src/api/source/geojson.js 12.6 kB {0} [built]
  [72] ./src/api/source/dataset.js 2.38 kB {0} [built]
  [88] ./src/api/source/sql.js 2.77 kB {0} [built]
  [94] ./src/api/interactivity.js 9.45 kB {0} [built]
    + 80 hidden modules

ERROR in ./src/api/layer.js
Module not found: Error: Can't resolve 'mitt' in '/Users/mho/proj/renderer-prototype/src/api'
 @ ./src/api/layer.js 1:0-24
 @ ./src/index.js

ERROR in ./src/api/interactivity.js
Module not found: Error: Can't resolve 'mitt' in '/Users/mho/proj/renderer-prototype/src/api'
 @ ./src/api/interactivity.js 1:0-24
 @ ./src/index.js

ERROR in ./src/api/integrator/mapbox-gl.js
Module not found: Error: Can't resolve 'mitt' in '/Users/mho/proj/renderer-prototype/src/api/integrator'
 @ ./src/api/integrator/mapbox-gl.js 1:0-24
 @ ./src/api/layer.js
 @ ./src/index.js
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Jesus89** [comment]
Hi @michellemho.

Thanks for the information.

You have some missing node modules. Try:

```
yarn cache clean
yarn
```

And then

```
yarn build
```

NOTE: you can use also `yarn serve` to serve the web in 127.0.0.1:8080, open the "Interactive example" and try the same map.

**Comment by michellemho** [comment]
Update: Once I change from `carto-gl.js` to  `carto-vl.js`, and remove `carto.Style` and use `carto.Viz` everything looks good! I was trying to run an old example. Thanks @Jesus89 for the help!
