### ISSUE TITLE
Video loop of examples for CARTO Locations Madrid talks

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/carto-vl#290]
From @jorgesancha:

> since a few of us will be showing CARTO VL stuff at Locations, we should probably do a 30s-60s video loop that showcase Carto VL rendering with different maps. Basically, a mix of the maps Mamata and David have been working on

@davidmanzanares @makella can you send me links to examples I could use to make that video? @makella Don't sweat it with the details 😛 Showing the capabilities is more than enough for the sake of this loop!

**Comment by makella** [comment]
yes! let me spend some time getting a variety of maps to show the capabilities... i'll send here in about a hour.. is that ok?

**Comment by arianaescobar** [comment]
More than ok! Thank you :)

**Comment by makella** [comment]
to start, here is the denver buildings animation:

two variations for you to choose from:
https://cartodb.github.io/carto-vl/example/mapbox.html#eyJhIjoiU0VMRUNUICogRlJPTSBwYXJjZWxzIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImZpbHRlcjogKCggIHRvcnF1ZShsaW5lYXIoJGNjeXJibHQsIDE4NzMsIDIwMTgpLCAyMCwgZmFkZSgwLCAxMDAwMDApKSAgKzAuMSAgICkgYW5kIG5lcSgkY2N5cmJsdCwgMCkpXG5jb2xvcjogcmFtcChsaW5lYXIoKCR0b3RhbF92YWx1LyRhcmVhICksIDAsIChnbG9iYWxQZXJjZW50aWxlKCR0b3RhbF92YWx1LCA5OSkpLzEwMDAgICAgKSAgLCBhZ19zdW5zZXQpIiwiZiI6eyJsbmciOi0xMDQuOTc2Nzk5MzUyMjM1NSwibGF0IjozOS43NDA0NTE0NDAxNjEzNjV9LCJnIjoxMy44MTA5NTAzOTI5NzEzMzd9

The link to the gh-pages: https://cartodb.github.io/carto-vl/example/mapbox.html#eyJhIjoiU0VMRUNUICogRlJPTSBwYXJjZWxzIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImZpbHRlcjogKCggIHRvcnF1ZShsaW5lYXIoJGNjeXJibHQsIDE4NzMsIDIwMTgpLCAyMCwgZmFkZSgwLCAxMDAwMDApKSAgKzAuMSAgICkgYW5kIG5lcSgkY2N5cmJsdCwgMCkpXG5jb2xvcjogcmFtcChsaW5lYXIoKCR0b3RhbF92YWx1LyRhcmVhICksIDAsIChnbG9iYWxQZXJjZW50aWxlKCR0b3RhbF92YWx1LCA5OSkpLzEwMDAgICAgKSAgLCB0ZW1wcykiLCJmIjp7ImxuZyI6LTEwNC45NjY1NDE3NjY2MjQxOCwibGF0IjozOS43MzgwODUxMzMzNjE2MzZ9LCJnIjoxMi4xMjk3MzI4NzY4MDQ2NDR9

**Comment by davidmanzanares** [comment]
I just deployed to `gh-pages` `master` with a fullscreen button and the cielab interpolation

**Comment by makella** [comment]
Rivers in the US (takes a few to load 2 milliion lines):

https://cartodb.github.io/carto-vl/example/mapbox.html#eyJhIjoicml2ZXJfZGlyZWN0aW9uc19jb3B5IiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBzcXJ0KCRzdHJhaGxlci8yKVxuY29sb3I6IG9wYWNpdHkocmFtcChsaW5lYXIoJGF6aW11dGgsMCw2KSxwcmlzbSksJHN0cmFobGVyLzEwKSIsImYiOnsibG5nIjotOTAuNjc5MjYyMzg5MjE3MDYsImxhdCI6MzYuOTE3Mjk5NTMxNjk4NDl9LCJnIjo0fQ==

**Comment by makella** [comment]
Taxi drop-off and pick-ups:

https://cartodb.github.io/carto-vl/example/mapbox.html#eyJhIjoibnlfYm9yb3VnaHNfd2l0aF90YXhpIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImZpbHRlcjogICB0b3JxdWUobGluZWFyKCR0aW1lLCB0aW1lKCcyMDEzLTAxLTAxVDAwOjAwOjAwWicpLHRpbWUoJzIwMTMtMDEtMjFUMDA6MjU6NTJaJykpLCA0MCwgZmFkZSgwLCAwLjMpKVxud2lkdGg6IDNcbmNvbG9yOiByYW1wKCR0eXBlLFtyZ2IoMjU1LCAwLCAyNTUpLHJnYigwLDI1NSwyNTUpXSlcblxuXG5cbiIsImYiOnsibG5nIjotNzMuOTc5NzY5NTk3NzE2MzEsImxhdCI6NDAuNzI2OTc1NDAzOTgwMTA2fSwiZyI6MTIuNTA4ODA0NTk1MjU2MDgyfQ==

**Comment by rochoa** [comment]
@arianaescobar, can we consider this as done?

**Comment by arianaescobar** [comment]
yass
