### ISSUE TITLE
set a good default style

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#297]
Replace the current default style by something less ugly :slightly_smiling_face:

UPDATE:

**Points**

```
width: 7
color: #EE4D5A
strokeWidth: 1
strokeColor: #FFF
```

**Lines**

```
width: 1.5
color: #4CC8A3
```

**Polygons**

```
color: #826DBA
strokeWidth: 1
strokeColor: #FFF
```

**Comment by makella** [comment]
As a first pass, what we could do is assign the same default symbology to points, lines, and polygons that we currently have in Builder. 

When Voyager was released, we went through a significant exercise of testing a LOT of combos and coming up with default colors that could be "seen" over the three different basemap types and between each other. This will also keep things "familiar".

The basics:

#### Polygons
`color: #826dba`
[EXAMPLE](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0byIsImIiOiIiLCJjIjoiZG1hbnphbmFyZXMiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiAjODI2ZGJhXG4iLCJmIjp7ImxuZyI6LTczLjk4OTE1Mzc0MTU5MzIxLCJsYXQiOjQwLjczNzgyNzE5NzA4MDM4fSwiZyI6MTMuNDY1NTAyMTA5MDExODd9)

#### Lines
```
color: #4cc8a3
width: 1.5
```
[EXAMPLE](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidnRfYW5udWFsX2F2ZXJhZ2VfZGFpbHlfdHJhZmZpY19hYWR0XzIwMTYiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6ICM0Y2M4YTNcbndpZHRoOiAxLjVcbiIsImYiOnsibG5nIjotNzMuMjM4NDkwNzA2Mjk5MSwibGF0Ijo0NC40NjQwNjc4NjY2NjgxOX0sImciOjYuNzA0MjgwNjI2MjYyODU0fQ==)

#### Points
```
width: 7
color: #ee4d5a
strokeWidth: 1
strokeColor: #fff
```
[EXAMPLE](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiA3XG5jb2xvcjogI2VlNGQ1YVxuc3Ryb2tlV2lkdGg6IDFcbnN0cm9rZUNvbG9yOiAjZmZmIiwiZiI6eyJsbmciOjIuMTcsImxhdCI6NDEuMzh9LCJnIjoxM30=)

In terms of "smarter" behavior there are some things I'd like to explore when time permits:

+ Marker size depending on the density of data... more data = smaller points, less data = larger points
  + similarly, thinking about good defaults that could take advantage of `zoom()`. But the value we use would depend largely on the density of points... for example using something like the styling below, the points disappear at small zooms.
  ```
  width:  0.001 * zoom()
  color: #ee4d5a
  strokeWidth: 0.0001 * zoom()
  strokeColor: #fff
  ```
+ If/when we have the capabilities to detect the basemap
  + basemap dependent symbology (automatically do the `inverse(cartocolor)`)
  + for light basemaps, use a light outline, for dark, a dark basemap

**Comment by Jesus89** [comment]
I think it is a good idea to use the same cross-basemap default style, and in the future add the logic for multiple default styles.

Since we are sharing properties for all the geometries we cannot have the same default styles:
- color: points & lines & polygons
- width: points & lines
- strokeColor: points & polygons
- strokeWidth: points & polygons

So... with this and the default Builder style in mind, what default values should we set in these properties? @arianaescobar @makella

**Comment by arianaescobar** [comment]
Would it take too much time to stop sharing properties between all the geometries?

**Comment by Jesus89** [comment]
It's easy to implement, but the point is that this is a decision for the spec (https://github.com/CartoDB/carto-vl/issues/55).

**Comment by davidmanzanares** [comment]
But we could change the defaults based on the geometry type though.

**Comment by arianaescobar** [comment]
> But we could change the defaults based on the geometry type though.

That's what we want :)

**Comment by makella** [comment]
are we all good here to set defaults based on geometry type?

**Comment by makella** [comment]
Now that we have strokes for polygons (🎉) we can update the default to:

```
color: #826dba
strokeWidth: 1
strokeColor: #fff
```
[EXAMPLE](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0byIsImIiOiIiLCJjIjoiZG1hbnphbmFyZXMiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiAjODI2ZGJhXG5zdHJva2VXaWR0aDogMVxuc3Ryb2tlQ29sb3I6IHdoaXRlXG5cbiIsImYiOnsibG5nIjotNzMuOTkyMzQxNDc5ODY4NCwibGF0Ijo0MC43MzI0MDEyOTA0NDYwMzV9LCJnIjoxMy42MTcyMjYwNTUxODY3NDgsImgiOiJEYXJrTWF0dGVyIn0=)

**Comment by Jesus89** [comment]
OK. So the final default values would be the following (taking into account the opacity), right?

**Points**

```
width: 7
color: opacity(#EE4D5A, 0.9)
strokeWidth: 1
strokeColor: #FFF
```

**Lines**

```
width: 1.5
color: #4CC8A3
```

**Polygons**

```
color: opacity(#826DBA, 0.9)
strokeWidth: 1
strokeColor: opacity(#FFF, 0.5)
```

NOTE: I have seen that opacity in strokeColor for polygons doesn't look good because the line rendering for the stroke is too simple so we could use strokeColor without opacity instead.

**Comment by Jesus89** [comment]
@arianaescobar I looked at the current implementation in Builder: https://github.com/CartoDB/cartodb/blob/master/spec/lib/carto/styles/geometry_spec.rb

**Comment by makella** [comment]
@Jesus89 that is a model that we followed that has always happened in builder (slight opacity to points and polygons)

for our purposes, don't worry, we can just assign the colors with no opacity

**Comment by Jesus89** [comment]
Perfect. I'm going to update the main ticket to introduce the final defaults :)

**Comment by Jesus89** [comment]
Closed by #373

**Comment by makella** [comment]
@Jesus89 

This might be known, but definitely something that we need everyone to look at for their maps.

If there has been no `strokeWidth` already defined, every point feature on maps are showing with a white outline.

-  I'm assuming the same for polygons
- and the same for marker width
- and anywhere else these properties aren't explicity defined

I can understand that this is complex, so maybe we can talk through a little.

In the meantime, everyone should add the `strokeWidth:0` and other properties to their maps.

Some examples:
https://carto.com/developers/carto-vl/examples/#example-animated-dataset

**Comment by makella** [comment]
great!
