### ISSUE TITLE
Hex is broken

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#298]
https://cartodb.github.io/carto-vl/example/mapbox.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiAzXG5jb2xvcjogaGV4KCdGMDAnKSIsImYiOnsibG5nIjoyLjE3LCJsYXQiOjQxLjM4fSwiZyI6MTN9

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/carto-vl/pull/300
