### ISSUE TITLE
Create a list of what has changed since the MVT blog post

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/carto-vl#318]
@namessanti asked us on April 10th was has changed since [this post](https://carto.com/blog/using-mvt-in-carto/) in order to understand this project better. We told him we would prepare a list for him or/and whoever has that same doubt.

**Comment by arianaescobar** [comment]
We made this list quickly on the spot, but someone should review it and probably add/remove stuff. Sharing it so we don't have to start from a blank canvas.  

- Styling language
- How much data on the map is rendered on the client that doesn’t have to go to the backend 
- Filter on the client
- Animation of several columns 
- New interactivity
- The interaction between user and tech (API)
- That users don’t have to use Mapbox anymore

**Comment by namessanti** [comment]
@makella @arianaescobar this is a good start. The big thing is nailing what the message is for users. We already announced vectors in CARTO in the post Ari mentions above - are we announcing improvements to this? Or are announcing a net-new method/library/UI of using this? Both?

Can we go a bit more in depth about these changes?
