### ISSUE TITLE
Use factory instead constructor to create layers

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/carto-vl#321]
# WIP

Related with https://github.com/CartoDB/carto-vl/issues/342

summary
--- 

With our current api, to create a Layer object  you need the following:

```js
const layer = new carto.Layer('layer0', source, viz);
```

The problem is that Layer is an async object! To get a fully functional layer you need:

- A valid webgl context
- A request to the server

Technically speaking, the request to the server is made in the [update](https://github.com/CartoDB/carto-vl/blob/master/src/api/layer.js#L109) function.

The update function:
- waits for the webglcontext
- requests metadata to the server
- requests data to the server
- Listens for viz changes
- Compiles the new shaders

This function is called in the layer constructor so when we create a layer the layer is not really `ready`  but we have a dummy object that started several requests.

This can lead to multiple concurrence issues, in fact all the layer code is kinda smelly because of this.

Problems
---

- should we improve the usage of a promise to detect the webgl context?
- should we use a factory returning a layerPromise instead a weird async-constructor?

**Comment by davidmanzanares** [comment]
To be honest, this is one of the things that, if we could go back and change then, I would.

However, I think we should close this now.

If we notice that the cost of not changing this is greater than the cost of a breaking API change we should re-open.
