### ISSUE TITLE
For discussion the use of "filter:" for conditions and animations

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#329]
@davidmanzanares 

Are there specific reasons that `filter` is the styling property to filter data and to animate? I find that a little confusing but understand that there might be some reasons that I am not aware of.

For example, in [this map](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0byIsImIiOiIiLCJjIjoiZG1hbnphbmFyZXMiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiByYW1wKGxpbmVhcihsb2coJG51bWZsb29ycyksIDIsIDQpLCB0ZW1wcylcbmZpbHRlcjogYmV0d2VlbigkbnVtZmxvb3JzLCAxMCwgMTIwKSIsImYiOnsibG5nIjotNzMuOTgzNTMzNDQzODA2MzIsImxhdCI6NDAuNzQ3OTc2NzUxMzI3fSwiZyI6MTIuNTYyOTM2MzA1NDQ4NjgyfQ==), using `filter` makes sense to me for the operation that we are after:
`filter: between($numfloors, 10, 120)`

On the other hand, `filter` isn't intuitive for me for animations. Can we simply say `animate:`?

I could also see cases where you would want to do a filter on the data and then animate the results. 

Also, I can't remember off the top of my head, but I know there is another way to define conditionals, like `if value is this then apply this style, else go to default`.

From my perspective, it seems like there are logical groupings of operations and putting them inside of other operations is feeling a little overwhelming.

**Comment by rochoa** [comment]
@makella, after more people using this, do you consider this is a problem yet?

**Comment by makella** [comment]
@rochoa I would like to understand better how we would animate and filter....

After going through the animation guide, I understand that `filter` returns a `1` or a `0` and that is the filter that `torque` animates on.

I can definitely see where people would want to 1) filter a subset of the data and then 2) animate the filter.

I haven't tried an example (because I'm not exactly sure how to approach) so it would be helpful to see that and then comment further.

thanks!

**Comment by davidmanzanares** [comment]
You can just combine filters (including `torque`) with boolean operators like: `and`, `or`, `not`.

For example: https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0b19udWxsZGF0ZXMiLCJiIjoiIiwiYyI6ImNhcnRvdmwiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiByYW1wKGxpbmVhcihsb2coJG51bWZsb29ycyksIDIsIDQpLCB0ZW1wcylcbnN0cm9rZUNvbG9yOiBvcGFjaXR5KHdoaXRlLCAwLjUpXG5maWx0ZXI6ICB0b3JxdWUoJGJ1aWx0X3RpbWUsIDUsIGZhZGUoMCwgMTAwMCkpICBhbmQgJHNoYXBlX2FyZWEgPiAyMDAwMCIsImYiOnsibG5nIjotNzMuOTgzNTMzNDQzODA2MzIsImxhdCI6NDAuNzQ3OTc2NzUxMzI3fSwiZyI6MTIuNTYyOTM2MzA1NDQ4NjgyLCJoIjoiRGFya01hdHRlciJ9

**Comment by makella** [comment]
ok, so if I want to do the slight visibility of the filtered data (not the entire dataset), what would i do?

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0b19udWxsZGF0ZXMiLCJiIjoiIiwiYyI6ImNhcnRvdmwiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiByYW1wKGxpbmVhcihsb2coJG51bWZsb29ycyksIDIsIDQpLCB0ZW1wcylcbnN0cm9rZUNvbG9yOiBvcGFjaXR5KHdoaXRlLCAwKVxuZmlsdGVyOiAgKHRvcnF1ZSgkYnVpbHRfdGltZSwgNSwgZmFkZSgwLCAxMDAwKSkgIGFuZCAkc2hhcGVfYXJlYSA+IDIwMDAwKSswLjIiLCJmIjp7ImxuZyI6LTczLjk4MzUzMzQ0MzgwNjMyLCJsYXQiOjQwLjc0Nzk3Njc1MTMyN30sImciOjEyLjU2MjkzNjMwNTQ0ODY4MiwiaCI6IkRhcmtNYXR0ZXIifQ==

**Comment by davidmanzanares** [comment]
Yes, you can also use them in combination with `blend` to not only modify the opacity but to assign arbitrary color expressions to the filtered and the unfiltered features:

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0b19udWxsZGF0ZXMiLCJiIjoiIiwiYyI6ImNhcnRvdmwiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiBibGVuZChncmV5LFxuICAgICAgICAgICAgIHJhbXAobGluZWFyKGxvZygkbnVtZmxvb3JzKSwgMiwgNCksIHRlbXBzKSxcbiAgICAgICAgICAgICB0b3JxdWUoJGJ1aWx0X3RpbWUsIDUsIGZhZGUoMCwgMTAwMCkpICBhbmQgICRzaGFwZV9hcmVhID4gMjAwMDBcbilcbnN0cm9rZUNvbG9yOiBvcGFjaXR5KHdoaXRlLCAwKVxuIiwiZiI6eyJsbmciOi03My45ODM1MzM0NDM4MDYzMiwibGF0Ijo0MC43NDc5NzY3NTEzMjd9LCJnIjoxMi41NjI5MzYzMDU0NDg2ODIsImgiOiJEYXJrTWF0dGVyIn0=

**Comment by makella** [comment]
ok, so this is the first time i'm seeing `torque` outside of `filter`! need to wrap my head around this. and the `blend` first time seeing that too.

why are all the buildings showing in your example and not just the filtered ones with the gray blend?

**Comment by davidmanzanares** [comment]
Because I'm not filtering by torque, I'm using torque as the conditional parameter of a `blend` expression.

`blend(A, B, torque(...))` means:
- Output `B` for the features that pass the `torque` expression
- Output `A` for the features that don't pass the `torque` expression
- Output the interpolation between `B` and `A` for the expressions that are under the `torque` fade.

But, as I wrote in the example, you can mix torque with other filters there too. So, in my example I'm saying:
- Output `grey` for the features that don't pass the `torque` and the `$shape_area > 20000` condition
- Output the ramp for the features that do pass both conditions.
- Output the interpolation between grey and the ramp color when the `$shape_area > 20000` is passed and the `torque` expression returns a value between `0` and `1` (the fade in and the fade out).

Hope I clarified it, but feel free to ask more :slightly_smiling_face:

**Comment by makella** [comment]
ok, this was a while back and I read through again and don't need to pursue this further since we haven't seen anyone having difficulties with the syntax!
