### ISSUE TITLE
Using MGL fork

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#333]
Now we are using the MGL forked bundle directly in this repo (`vendor` directory). It is a pain to update the bundle manually and also the `@carto/mapbox-gl` package. We can optimize this.

In carto-vl we use MGL in the tests (render, user, e2e) and the examples.

For the tests, we should use our MGL fork as a devDependency. For the examples, we should use our published MGL package (https://github.com/CartoDB/carto-vl/pull/270).

In our fork we should keep the `master` branch updated, so we need to create a `carto` branch with our PR merged and the package name updated. For our releases, I would use the original version + `-N` for our updates. Note: do not forget to generate the dist before doing a release.

**Comment by IagoLast** [comment]
+1

**Comment by Jesus89** [comment]
Closed by #339
