### ISSUE TITLE
Tests are broken on Retina displays

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#336]
As reported by @rochoa 

Could you take a look @IagoLast ?

**Comment by IagoLast** [comment]
3 Render tests are broken:


|Test| actual|expected|diff|
| --- |:-----:|:---------:|:---:|
| color/named|![reference_out](https://user-images.githubusercontent.com/2657897/39191196-b93be130-47d6-11e8-99fb-11d7d710d358.png)|![reference](https://user-images.githubusercontent.com/2657897/39191212-c3fffc82-47d6-11e8-8b3c-e039873cc196.png)|![diff](https://user-images.githubusercontent.com/2657897/39191232-cbdf8c10-47d6-11e8-83b4-8a094d1e3760.png)
| ramp/custom-category-others |![reference_out](https://user-images.githubusercontent.com/2657897/39191319-fedab040-47d6-11e8-945a-890b19eaeae9.png)|![reference](https://user-images.githubusercontent.com/2657897/39191334-048f0f5e-47d7-11e8-86b1-14ee235b4037.png)|![diff](https://user-images.githubusercontent.com/2657897/39191376-1de962c4-47d7-11e8-8613-ddb455e4e256.png)
|ramp/custompalette|![reference_out](https://user-images.githubusercontent.com/2657897/39191459-45bbd3e0-47d7-11e8-8946-0369b59dc0d1.png)|![reference](https://user-images.githubusercontent.com/2657897/39191474-4bd43cd6-47d7-11e8-9c36-ed6ad88421d0.png)|![diff](https://user-images.githubusercontent.com/2657897/39191478-4f11c224-47d7-11e8-85cf-340773ecf683.png)

**Comment by rochoa** [comment]
Running the tests in my retina laptop I get:

```
  Render tests:
    1) /collection-point/color
    ✓ /collection-point/default (1445ms)
    2) /collection-point/strokeColor
    3) /collection-point/strokeWidth
    4) /collection-point/width
    ✓ /color/cielab (1457ms)
    5) /color/hex
    ✓ /color/hsl (1498ms)
    ✓ /color/hsla (1477ms)
    ✓ /color/hsv (1480ms)
    ✓ /color/hsva (1479ms)
    ✓ /color/named (1494ms)
    6) /color/opacity
    7) /color/rgb
    ✓ /color/rgba (1487ms)
    8) /line-string/color
    ✓ /line-string/default (1520ms)
    ✓ /line-string/width (1539ms)
    ✓ /mgl-integration/lines (1490ms)
    9) /mgl-integration/multi-layer-inv
    10) /mgl-integration/multi-layer
    11) /mgl-integration/points
    ✓ /mgl-integration/polygons (1438ms)
    ✓ /mgl-integration/shared-sources (1506ms)
    12) /multi-line-string/color
    ✓ /multi-line-string/default (1475ms)
    ✓ /multi-line-string/width (1503ms)
    13) /multi-polygon/color
    ✓ /multi-polygon/default (1490ms)
    14) /point/color
    ✓ /point/default (1457ms)
    15) /point/strokeColor
    16) /point/strokeWidth
    17) /point/width
    18) /polygon/color
    ✓ /polygon/default (1490ms)
    ✓ /ramp/cartocolor-category-others (1490ms)
    ✓ /ramp/cartocolor-category (1499ms)
    19) /ramp/cartocolor-linear-opacity
    ✓ /ramp/cartocolor-linear (1490ms)
    20) /ramp/category-interpolation
    21) /ramp/custom-category-others
    22) /ramp/custompalette
    23) /ramp/custompalettefloat-fp32
    24) /ramp/custompalettefloat
    25) /regression/layer-update
    26) /regression/property-limits
    ✓ /regression/shared-sources (1568ms)
    27) /styling/linear
    28) /variables/multi-referenced
    29) /variables/simple
    30) /variables/two-aliases


  22 passing (1m)
  30 failing

```

**Comment by rochoa** [comment]
It's not related to the Retina display itself. The problem was with the color profile of my display. After changing from `Display P3` or `Color LCD` to `SD 170M-A` all the tests work.

**Comment by Jesus89** [comment]
IMO it should be nice for Mac developers to have the solution for this "issue" in the developer documentation. Maybe here: https://github.com/CartoDB/carto-vl/blob/master/test/integration/render/README.md
