### ISSUE TITLE
What is 'blend' and syntax question

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#353]
@davidmanzanares 
First, what is the recommended use for `blend()`? I'm not sure I'm understanding what it does or why someone would use it over another symbology method.

I am expecting that `blend` for something like point size or line width, would take my attribute, and ramp the values to my desired range of symbol sizes.

For example:
`width: blend(1,30,$amount)`

But that produces a homogeneous map:
+ [MAP](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgxLDMwLCRhbW91bnQpXG5jb2xvcjogcmFtcCgkY2F0ZWdvcnksIFBSSVNNKSIsImYiOnsibG5nIjoyLjE3NTQwMDkzNDMwNDIwNywibGF0Ijo0MS4zOTMxNzk2Mjg3NzcyOX0sImciOjE0Ljc5NzA2MDA3MTY0NTM0MiwiaCI6IkRhcmtNYXR0ZXIifQ==)

In order to see some variation, I have to know to perform another operation on my attribute:
`width: blend(1,30,$amount/1000)`
+ [MAP](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgxLDMwLCRhbW91bnQvMTAwMClcbmNvbG9yOiByYW1wKCRjYXRlZ29yeSwgUFJJU00pIiwiZiI6eyJsbmciOjIuMTc1NDAwOTM0MzA0MjA3LCJsYXQiOjQxLjM5MzE3OTYyODc3NzI5fSwiZyI6MTQuNzk3MDYwMDcxNjQ1MzQyLCJoIjoiRGFya01hdHRlciJ9)

But not all operations produce results:
`width: blend(1,30,sqrt($amount))`
+ [MAP](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgxLDMwLHNxcnQoJGFtb3VudCkpXG5jb2xvcjogcmFtcCgkY2F0ZWdvcnksIFBSSVNNKSIsImYiOnsibG5nIjoyLjE3NTQwMDkzNDMwNDIwNywibGF0Ijo0MS4zOTMxNzk2Mjg3NzcyOX0sImciOjE0Ljc5NzA2MDA3MTY0NTM0MiwiaCI6IkRhcmtNYXR0ZXIifQ==)

Second, I can see people getting confused with the syntax

For example, to use the "properly" one needs to write:

`width: blend(1,30,$amount/1000)`
+ [MAP](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgxLDMwLCRhbW91bnQvMTAwMClcbmNvbG9yOiByYW1wKCRjYXRlZ29yeSwgUFJJU00pIiwiZiI6eyJsbmciOjIuMTczODk0MDkwNDExOTc3MiwibGF0Ijo0MS4zOTQxMDQxNTA2Mzk2MDZ9LCJnIjoxMi45NzkzNDczODQ5NTMxNCwiaCI6IkRhcmtNYXR0ZXIifQ==)

But we also accept:
`width: blend($amount/1000,1,30)`
Which produces nothing interesting:
+ [MAP](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgkYW1vdW50LzEwMDAsMSwzMClcbmNvbG9yOiByYW1wKCRjYXRlZ29yeSwgUFJJU00pIiwiZiI6eyJsbmciOjIuMTc4NTY2MjI2NzEwMjQ1MiwibGF0Ijo0MS4zOTYzMzUxNjk1MTM0MX0sImciOjEyLjM1NDQ2Mjk2MjY5MjI2OSwiaCI6IkRhcmtNYXR0ZXIifQ==)

I feel like the second syntax is more in-line with other ways we define styling `$attribute`,`style`

**Comment by makella** [comment]
@davidmanzanares ok ok

the multi-zoom example refreshed my memory... `blend` is equivalent to `ramp`.
+ [MAP](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgxLDEwLGxpbmVhcigkYW1vdW50LDUwLDUwMCkpXG5jb2xvcjogcmFtcCgkY2F0ZWdvcnksIFBSSVNNKSIsImYiOnsibG5nIjoyLjE4NTg4OTk0NjE4ODgwODYsImxhdCI6NDEuMzg1NTEyNjIxOTQ1Njh9LCJnIjoxMy4zMDIwMDIyMzgxOTY4NjEsImgiOiJEYXJrTWF0dGVyIn0=)

I think we talked about the syntax ordering a while back... will it break something to have the syntax reordered 

from:
`width: blend(1,10,linear($amount,50,500))`

to:
`width: blend(linear($amount,50,500),1,10)`

**Comment by rochoa** [comment]
@makella, can we close this one?
