### ISSUE TITLE
zoom-based conditional styling question

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#354]
@davidmanzanares 

I'm wondering how to do zoom-based conditional styling.

Starting with this (which works)
```
color: 
ramp(
  linear(zoom(), 2^10, 2^12)*
  linear(sqrt($amount), 1, 100), redor
)
```

I'd like to build on to it to do something different from z14 - z18 so I just tried something that I knew would be incorrect but demonstrates what I want to do but not sure how to accomplish:

```
color: 
ramp(
  linear(zoom(), 2^10, 2^12)*
  linear(sqrt($amount), 1, 100)*
  linear(zoom(),2^14,2^18)*
  linear(sqrt($amount), 50, 500), redor
)
```
Or I tried this

```
color: 
ramp(linear(zoom(), 2^10,2^12)*linear(sqrt($amount), 1, 100),redor))
and
ramp(linear(zoom(),2^14,2^18)*linear(sqrt($amount), 50, 500),emrld))
```

Any suggestions?

**Comment by davidmanzanares** [comment]
The only way now, to do this for the color (for width there are other options I think) is `blend`. However, I wouldn't try to focus on this right now, since it probably needs more work from the development point of view :slightly_frowning_face:

**Comment by makella** [comment]
ohhh yes... width.

i think i have the geographica example you showed me... buuuut can you give me some sample syntax here so i can play around with it?

i need to understand blend better too

**Comment by makella** [comment]
ok, i found these from our convo! i'll get started here but i'm not sure why the first link isn't working


https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgyLCAxNiwgbGluZWFyKHpvb20oKSwgMCwgcG93KDIsIDE2KSAgKSlcbmNvbG9yOiByZ2JhKDAuOCwwLDAsMSkiLCJmIjp7ImxuZyI6Mi4xNTMzMDI5NTcyNzA3MzksImxhdCI6NDEuMzc3NTM4NDgxNDk3NTk1fSwiZyI6MTMuOTA5OTA4NTAwMjQyODc0LCJoIjoiRGFya01hdHRlciJ9

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgyLCAyMCwgbGluZWFyKHpvb20oKSwgcG93KDIsIDE0KSwgcG93KDIsIDE2KSAgKSAgICApXG5jb2xvcjogcmFtcChsaW5lYXIoem9vbSgpLCAyXjIsIDJeOCksIHByaXNtKSIsImYiOnsibG5nIjoyLjEyMTY3OTg0OTQ4NzAwOSwibGF0Ijo0MS4yOTI1MDI3NzE0NTg5MX0sImciOjEwLjI2NDYxMzgwMjI5MTM2NSwiaCI6IkRhcmtNYXR0ZXIifQ==

**Comment by davidmanzanares** [comment]
Yes, first link works, although the change of rgb [0,1] to [2,255] range made it quite difficult to see. Just change the color: https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgyLCAxNiwgbGluZWFyKHpvb20oKSwgMCwgcG93KDIsIDE2KSAgKSlcbmNvbG9yOiB3aGl0ZSIsImYiOnsibG5nIjoyLjE0NzM5NzY5NTcyNzcwNDYsImxhdCI6NDEuMzg4NTU5MTQxNDEwOTh9LCJnIjoxNi4wOTgzNzc0MDk1NzMxNSwiaCI6IkRhcmtNYXR0ZXIifQ==


`blend(x, y, m)` returns x when `m` is less or equal to 0, returns y when `m` is greater than or equal to 1, and when `m` is between 0 and 1, it will return the interpolation of `x` and `y` based on `m`.

**Comment by makella** [comment]
ugh didn't look at the details! `rgb` 🤦‍♀️  

perfect this will get me started thank youuuu

**Comment by rochoa** [comment]
Review after https://github.com/CartoDB/carto-vl/issues/690 is finished.

**Comment by makella** [comment]
closing this as #860 addresses this
