### ISSUE TITLE
Polygon simplification

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#365]
This might be a server-side issue where we are sending the polygons with too much simplification. Probably related to the fact that we based our simplification based on 256px tiles.

![simplification](https://user-images.githubusercontent.com/45346/39577211-f33ba7b0-4ee0-11e8-8155-8b190c572bb1.gif)

**Comment by rochoa** [comment]
Some conclusions after some tests, with the help of @jgoizueta.

My first assumption was that this was related to the [simplification we do in the Mapnik query](https://github.com/CartoDB/mapnik/blob/49cfb2ff383a204a757aa1906bb4d4fe5b6b707c/plugins/input/postgis/postgis_datasource.cpp#L777-L859). But it isn't.

## Using Postgis with no simplification 
I enabled `usePostGIS` to generate the MVT tiles using Postgis' `ST_AsMVT`, that fixed fixed the problem.

![postgis](https://user-images.githubusercontent.com/45346/39693769-753b7ea0-51e5-11e8-973c-a9f2ff8d0241.png)

### Issues with Postgis
1. The tile generation is very slow. Something to revisit as we are not doing any simplification, neither clipping the tiles. cc @rafatower 

2. I had to change CARTO VL polygon decoding as I was hitting `Invalid MVT tile: first polygon ring MUST be external` error. I did this change:
```diff
diff --git a/src/client/windshaft.js b/src/client/windshaft.js
index 8b28769c..af0e422f 100644
--- a/src/client/windshaft.js
+++ b/src/client/windshaft.js
@@ -414,7 +414,7 @@ export default class Windshaft {
             //if exterior
             //   push current polygon & set new empty
             //else=> add index to holes
-            if (isClockWise(geom[j])) {
+            if (!isClockWise(geom[j])) {
                 if (polygon) {
                     geometry.push(polygon);
                 }
```
cc @davidmanzanares 


## Mapnik disabling simplification
With the Postgis experiment in mind, I decided to remove all simplifications/clipping (`ST_Simplify`, `ST_RemoveRepeatedPoints`, `ST_ClipByBox2D`) in the Mapnik query and use `ST_AsBinary` instead of `ST_AsTWKB`. Ending with a query pretty similar to the one in Postgis' `ST_AsMVT`:

```sql
SELECT ST_AsBinary("the_geom_webmercator") AS geom,"cartodb_id" FROM (SELECT cartodb_id,the_geom,the_geom_webmercator FROM sa1_2016_aust_copy ) as cdbq WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(15651857.40789897 -5011823.070602437,16282921.51342139 -4380758.965080022)'::box3d, 3857)
```

![mapnik](https://user-images.githubusercontent.com/45346/39693527-9aea565e-51e4-11e8-827b-6edb1241e7cf.png)

However, the issue persists and the polygons are oversimplified. Either I'm doing something wrong or missing some configuration, or something must be going on in Mapnik itself. cc @rafatower 

BTW, look at the timing for the tile that was taking 17s in Postgis, here it takes 0.4s.

**Comment by jgoizueta** [comment]
Regarding the polygon orientation, which @ethervoid [also noticed](https://github.com/CartoDB/carto-vl/issues/279#issue-312955303)

MVT [requiers polygons to be CW](https://www.mapbox.com/vector-tiles/specification/#winding-order) **in screen coordinates**.

I think it might be either because:
* ST_AsMVT as other ST_As* functionts preserve internal orientation
* ST_AsMVT tries to normalize the orientation but does so in geographical space, ignoring the fact that MVT coordinates has the Y axis reversed (grows downwards) in respect to geography.

We can verify the first case by using `ST_ForcePolygonCCW` on the geometry.

In any case this has to be a bug in STAsMVT

**Comment by jgoizueta** [comment]
Note that in the example all geometries are consistently oriented CW in PostGIS, which is consistent with the case 1 above (ST_AsMVT not caring about orientation) and the observed orientation.

```sql
SELECT ST_IsPolygonCW(the_geom), ST_IsPolygonCCW(the_geom), count(*) FROM sa1_2016_aust_copy GROUP BY 1,2;
 st_ispolygoncw | st_ispolygonccw | count
----------------+-----------------+-------
 t              | f               | 12809
(1 row)
SELECT ST_IsPolygonCW(the_geom_webmercator), ST_IsPolygonCCW(the_geom_webmercator), count(*) FROM sa1_2016_aust_copy GROUP BY 1,2;
 st_ispolygoncw | st_ispolygonccw | count
----------------+-----------------+-------
 t              | f               | 12809
(1 row)
```

**Comment by rochoa** [comment]
@Algunenano pointed me to [tilelive-bridge's `opts.simplify_distance`](https://github.com/CartoDB/tilelive-bridge/blob/ec881cb9ac52113f895f23857430e2d434bb99a6/index.js#L278).

I did two quick tests and that seems to be the culprit. So not using any simplification in the SQL query, these are the results.

### opts.simplify_distance = 1

![simplify_distance-1](https://user-images.githubusercontent.com/45346/39742753-fb7022be-529e-11e8-8f10-d2f20aa72e9f.png)

### opts.simplify_distance = 0

![simplify_distance-0](https://user-images.githubusercontent.com/45346/39742764-0440b9a8-529f-11e8-8b4a-1967ac7a9e90.png)

**Comment by rochoa** [comment]
I'm considering this as done. The original problem is solved right now.

<img width="828" alt="screen shot 2018-07-10 at 11 58 52" src="https://user-images.githubusercontent.com/45346/42503337-b37644ae-8438-11e8-8526-9ffb234bab8a.png">

Some details about the other issues raised:
- The `Invalid MVT tile: first polygon ring MUST be external` is already fixed (https://github.com/CartoDB/carto-vl/pull/628) via https://github.com/CartoDB/carto-vl/pull/631.
- There is an existing effort on unifying the behaviour and having s imilar performance regarding Mapnik and ST_AsMVT, see https://github.com/CartoDB/Windshaft/pull/632.
