### ISSUE TITLE
I'd like to have events while the points are loading

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/carto-vl#367]
cc/ @davidmanzanares

**Comment by Jesus89** [comment]
Hi @piensaenpixel.

You can use the layer `loaded` event to check when the data is loaded:

```js
layer.on('loaded', () => {
});
```

Do you mean also events to check the process of the load?

**Comment by davidmanzanares** [comment]
@Jesus89 the `loaded` event is fired after a zoom in/out triggers the download of some tiles (and it fires when that download is completed)?

**Comment by davidmanzanares** [comment]
I checked the code and I can confirm that `loaded` is fired once, but, anyway, this may be enough for your use case, @piensaenpixel ... Is it or you want to have spinner even after the first load?
