### ISSUE TITLE
Quantiles defaults to viewport

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#368]
@davidmanzanares 

I am torn about this... in some ways I think it is good to show changes through zooming/panning but I think people will get confused as to why the colors are changing on their map with these actions.

In that case, viewport should be an option and not a default for quantiles.

What are your thoughts?

p.s. - this is based off of a conversation with Andy yesterday while he was testing. I didn't realize that we default to viewport for quantiles until he pointed it out.
<img width="595" alt="screen shot 2018-05-02 at 3 03 27 pm" src="https://user-images.githubusercontent.com/1566273/39588492-1732d51c-4eb9-11e8-8ba6-3ad4023db43b.png">

**Comment by davidmanzanares** [comment]
Yes, I think it would be better to have a `viewportQuantiles`. The question would be, from my point of view, if we have a `globalQuantiles` or just `quantiles` (as global). What do you think about this?

**Comment by davidmanzanares** [comment]
Addressed by https://github.com/CartoDB/carto-vl/pull/420
