### ISSUE TITLE
Bug in Multiple features example

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/carto-vl#387]
**Example:** https://carto.com/developers/carto-vl/examples/#example-muliple-features

<img width="1397" alt="screen shot 2018-05-09 at 18 40 06" src="https://user-images.githubusercontent.com/16247628/39827559-913a3f5e-53b8-11e8-942f-5681e29ecd20.png">

The pop-up is showing a bunch of countries by default and the whole interactivity is working strangely. Kinda hard to explain. Just play a bit with the example and you'll see what I mean.

**Comment by Jesus89** [comment]
Found that this was introduced in bac8b45040fdf009f410e237da328d46c5e396b4

**Comment by Jesus89** [comment]
Fixed by https://github.com/CartoDB/carto-vl/pull/395
