### ISSUE TITLE
Rename public method `eval` to a `.value` getter

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#403]
Right now to access to data-view like data like histograms, global and viewport aggs we do:
`const max = viz.variables.globalMaxLoss.eval()`
I think it would be more consistent to have:
`const max = viz.variables.globalMaxLoss.value`

It would be similar to:
`const featureMax = feature.variables.featureMaxLoss.value`

**Comment by davidmanzanares** [comment]
Fixed by #421

**Comment by IagoLast** [comment]
Not fixed, this was a preliminary refactor 😅
