### ISSUE TITLE
Multiple layers should use a single Maps API map instance

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#413]
Multilayer maps are using different map instances of Maps API when they should try to reuse maps. 

In some scenarios, this will improve the loading as it will request 1/n tiles for an n-layers map.

**Comment by davidmanzanares** [comment]
We talked off channel about supporting HTTP 2 in the backend to avoid implementing this.

**Comment by rochoa** [comment]
Although this approach presents some advantages—reducing the number of total requests for multiple layers maps—using a single layer per map has some other benefits:

1. Better cache per dataset/query: you will only get missed from the cache for the layer/dataset that changed. With multiple layers' MVT tiles, you have to get fresh tiles when one of the datasets/queries changes.
1. It's easier to reason about layers treated as separate entities: the API for sources and layers expose them as separate entities, bundling them into single requests presents some challenges with sync vs async code. For instance, in CARTO.js, there is another entity trying to hide that complexity to the library user. IMO, that fails to its purpose.
1. In the future, we can improve the situation of requesting too many tiles by working on the Just One Tile optimization issue https://github.com/CartoDB/carto-vl/issues/17.

With those reasons in mind, right now, I'm not inclined on implementing this.
