### ISSUE TITLE
Metadata inconsistency for time with no time zone columns

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/carto-vl#419]
For time columns with no time zone (timestamp, etc), casting it to text (as CartoVL does) produces no timezone information in the resulting text. This makes the parsing used to build a dataframe (JS Date.parse) to interpret it in the client's local timezone.

On the other hand the max/min values requested from the SQL API (or from the new Maps API metadata) do have zone information in the literal (due to the way [our PG client](https://github.com/CartoDB/node-cartodb-psql) converts to JSON?)

An example where this is a problem (it happened to me!) is using the `torque` function with a time property (with no TZ): `torque($timestamp, ...)`
Then the limits of the animation will be obtained from the metadata and will be shifted from the actual data by the local TZ difference (with UTC). (see [this example](https://bl.ocks.org/jgoizueta/2fbf74989a915521220a6e6d5965341c) and remove the ` with time zone` frpm the timestamp types)

Some possible solutions:
* Change casting of time types (in the client) so that it always includes a TZ (as happens with metadata)
* Reformat metadata results for time columns without time zone to remove the TZ (e.g. by casting the metadata values to text in the metadata query)
* Implement time casting in Maps API at the query level (we're considering either this or casting at MVT generation), apply same casting to metadata results-

**Comment by jgoizueta** [comment]
When #495 is integrated this won't be a problem, because the min/max in the metadata will be converted by the backend just like the data (to UTC epoch numbers) so there will be no inconsistency.

**Comment by jgoizueta** [comment]
This problem can be checked with [this example](https://github.com/CartoDB/carto-vl/pull/495/commits/99173876a67ee2757a152bb603d6d9de42755e37#diff-c6f0a7070f5200c2f8db706cd3782a7c) and having a locale with a timezone offset from UTC: For example I have a two hour offset in my computer, so there's a two hour shift of times in respect to the torque animation range and that causes a delay when animation reaches the end (right end of the line) until it appears again at the start (left end).

**Comment by jgoizueta** [comment]
This has been checked with #495 and the problem is solved there

**Comment by IagoLast** [comment]
fixed in https://github.com/CartoDB/carto-vl/issues/130
