### ISSUE TITLE
Add layer.removeFromMap() method

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#428]

**Comment by davidmanzanares** [comment]
Integrating CARTO VL with the upstream custom layers proposal would fix this

**Comment by Jesus89** [comment]
This is implemented as `layer.removeFrom(map)` in the branch https://github.com/CartoDB/carto-vl/pull/886

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/carto-vl/pull/886
