### ISSUE TITLE
feature request: hexa so hex values can be used with opacity

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/carto-vl#429]
Currently there are alpha versions of rgb, hsv, and hsl but I don't see a way to control the alpha for the hex value function. It would be really nice to have `hexa( hexadecimalColor, alpha )` in addition to `hex( hexadecimalColor )`

**Comment by Jesus89** [comment]
Hi @andy-esch!

You can now use alpha in hex with the following format:
- #000F
- #000000FF

Maybe we could improve the documentation to add this information clearer.

**Comment by andy-esch** [comment]
Oooh, nice I didn't know about controlling alpha with the last characters!

Out of curiosity, is not adding a `hexa` -- which would bring the color functions in parity for functionality -- a conscious choice?

**Comment by andy-esch** [comment]
By the way, when I do `color: hex(#5D69B100)` I get the following error:
```
Invalid viz: Error: hex(): invalid first parameter 'hexadecimalColor'
    '[object Object]' is not a string
```
Using just the hex value (without the `hex` function) works as expected.

**Comment by Jesus89** [comment]
Yep, we could add the function but I think using the last characters is OK for now. You could use the opacity function. Also, the String API does an implicit cast so you don' need to call the `hex` function in there.

JavaScript API

```js
const e = carto.expressions;
const viz = new carto.Viz({
  @color1: e.hex('#5D69B100')
  @color2: e.opacity(e.hex('#5D69B1'), 0)
});
```

String API

```js
const viz = new carto.Viz(`
  @color1: #5D69B100
  @color2: opacity(#5D69B1, 0)
`);
```

**Comment by rochoa** [comment]
@andy-esch, can we close this one based on the information provided by Jesus?

**Comment by andy-esch** [comment]
Yep, all good! Thanks Jesus!
