### ISSUE TITLE
remove "misc" section from examples

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#435]
@Jesus89 @arianaescobar 

just noticed that we have the "Misc" section showing in the dev center examples... can we remove?

thanks!

**Comment by makella** [comment]
actually, maybe the dev center hasn't updated so closing until it reflects our changes!

**Comment by Jesus89** [comment]
Hi @makella!

I recovered two examples that we use for the internal development. But these examples are not in the `examples.json` file so they are not exported. There are also other examples that we use internally but are not exported to the dev center so we are OK with that :)
