### ISSUE TITLE
Check that all the reference items follow the same example structure

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/carto-vl#448]
With the code blocks on the right instead of the left. 

For example, [buckets](https://carto.com/developers/carto-vl/reference/#cartoexpressionsbuckets) look like it's not following it properly.

**Comment by davidmanzanares** [comment]
The reason for that inconsistency is that the examples are interleaved with the explanation, and the explanation refers and explain the examples. Maybe it is explained in too much detail, though.

**Comment by rochoa** [comment]
@arianaescobar, can you give us more feedback on this one?

**Comment by arianaescobar** [comment]
My comment was regarding adding code blocks to the left side of the reference. We have an assigned space on the right that it's only for code and we should leverage that more. 

Like here
![screen shot 2018-06-11 at 10 22 27](https://user-images.githubusercontent.com/16247628/41220398-9064e8a0-6d61-11e8-8d7a-c4ea6e3c422c.png)

or here
![screen shot 2018-06-11 at 10 24 34](https://user-images.githubusercontent.com/16247628/41220428-ac065c60-6d61-11e8-9faa-f82a22fc1eb2.png)

I think the level of detail is fine @davidmanzanares, I just think we should use the right side of the layout more. 

Like we did here
![screen shot 2018-06-11 at 10 25 59](https://user-images.githubusercontent.com/16247628/41220537-017ec7f4-6d62-11e8-8f93-bf6537423674.png)

or here
![screen shot 2018-06-11 at 10 26 57](https://user-images.githubusercontent.com/16247628/41220543-04c72dac-6d62-11e8-8d00-b9a101e12e04.png)
