### ISSUE TITLE
Add live animation examples

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/carto-vl#464]
We should add some live examples to the animation guide, e.g.
TODO: real examples, like:

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidXNkbV9hbGxfMjAxOCIsImIiOiIiLCJjIjoiY2FydG9nbCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IG9wYWNpdHkocmFtcChidWNrZXRzKCRkbSwwLDEsMiwzLDQpLHBpbmt5bCksYmxlbmQoMC43LDAuOSxsaW5lYXIoJGRtLDAsMykpKVxuZmlsdGVyOiB0b3JxdWUobGluZWFyKCRkYXRlLHRpbWUoJzIwMTgtMDEtMDFUMDA6MDA6MDBaJyksdGltZSgnMjAxOC0wNC0yNFQwMDowMDowMFonKSksMTcsZmFkZSgyLDIpKSIsImYiOnsibG5nIjotODAuMjk1NTQxNzE1NDU0NDIsImxhdCI6MzUuODIzMjAxMzMyNTEwMTk1fSwiZyI6NS45NzQ2NzE4MTIxMDQzNDUsImgiOiJWb3lhZ2VyIn0=

The synthetic demonstration of torque in the guide could also be added as a live example, but I'm not sure it's worth.

**Comment by Jesus89** [comment]
I have updated the example to match the current API:

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidXNkbV9hbGxfMjAxOCIsImIiOiIiLCJjIjoiY2FydG9nbCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IG9wYWNpdHkocmFtcChidWNrZXRzKCRkbSxbMCwxLDIsMyw0XSkscGlua3lsKSxibGVuZCgwLjcsMC45LGxpbmVhcigkZG0sMCwzKSkpXG5maWx0ZXI6IHRvcnF1ZShsaW5lYXIoJGRhdGUsdGltZSgnMjAxOC0wMS0wMVQwMDowMDowMFonKSx0aW1lKCcyMDE4LTA0LTI0VDAwOjAwOjAwWicpKSwxNyxmYWRlKDIsMikpIiwiZiI6eyJsbmciOi0xMDAuNjY1NzQzNDM5ODQwMTgsImxhdCI6NDYuNjE0MTg5MzA4MDMyMDI0fSwiZyI6Mi42MTM1Mjg5MzczMjkzOTg2LCJoIjoiRGFya01hdHRlciJ9

**Comment by Jesus89** [comment]
cc @arianaescobar @makella

**Comment by makella** [comment]
@Jesus89 how can we make maps like this faster? it is taking a while to load...

**Comment by Jesus89** [comment]
All the spinner time we are waiting for the server response. So maybe we could simplify the time expressions to reduce the amount of data required for the visualization.

cc @davidmanzanares

**Comment by davidmanzanares** [comment]
The last example: https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidXNkbV9hbGxfMjAxOCIsImIiOiIiLCJjIjoiY2FydG9nbCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IG9wYWNpdHkocmFtcChidWNrZXRzKCRkbSxbMCwxLDIsMyw0XSkscGlua3lsKSxibGVuZCgwLjcsMC45LGxpbmVhcigkZG0sMCwzKSkpXG5maWx0ZXI6IHRvcnF1ZShsaW5lYXIoJGRhdGUsdGltZSgnMjAxOC0wMS0wMVQwMDowMDowMFonKSx0aW1lKCcyMDE4LTA0LTI0VDAwOjAwOjAwWicpKSwxNyxmYWRlKDIsMikpIiwiZiI6eyJsbmciOi0xMDAuNjY1NzQzNDM5ODQwMTgsImxhdCI6NDYuNjE0MTg5MzA4MDMyMDI0fSwiZyI6Mi42MTM1Mjg5MzczMjkzOTg2LCJoIjoiRGFya01hdHRlciJ9

Triggers a bug in the recently updated Maps API.

![bug-sampling](https://user-images.githubusercontent.com/1692175/40548673-aadec900-6035-11e8-9c8a-ff3fc7caa02c.png)

The problem, I think, is that the sampling is downloading the geometry data of the features, which, in this case is around 120 MB. This makes Maps API super slow (and slows down CARTO VL at init time a little bit too).

cc: @jgoizueta

**Comment by makella** [comment]
when you say simplify the time expression, do you mean reduce the time range?

here is a map that does that seeing the same problem
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidXNkbV9hbGxfMjAxOCIsImIiOiIiLCJjIjoiY2FydG9nbCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IG9wYWNpdHkocmFtcChidWNrZXRzKCRkbSxbMCwxLDIsMyw0XSkscGlua3lsKSxibGVuZCgwLjcsMC45LGxpbmVhcigkZG0sMCwzKSkpXG5maWx0ZXI6IHRvcnF1ZShsaW5lYXIoJGRhdGUsdGltZSgnMjAxOC0wMS0wMVQwMDowMDowMFonKSx0aW1lKCcyMDE4LTAyLTAxVDAwOjAwOjAwWicpKSw0LGZhZGUoMiwyKSlcbnN0cm9rZVdpZHRoOiAwIiwiZiI6eyJsbmciOi0xMDAuNjY1NzQzNDM5ODQwMTgsImxhdCI6NDYuNjE0MTg5MzA4MDMyMDI0fSwiZyI6Mi42MTM1Mjg5MzczMjkzOTg2LCJoIjoiVm95YWdlciJ9

And this is also happening on the Engine page when you go through the maps on there...
https://carto.com/engine/

**Comment by Jesus89** [comment]
I'm going to move this ticket back in the Kanban to create more animated examples in the future, but for this is separated from the current guides.

**Comment by jgoizueta** [comment]
@davidmanzanares: yes, removing the geometry from the sample was a pending thing, I'll open a ticket in Windshaft-cartodb to deal with the backend part

**Comment by jgoizueta** [comment]
Samples don't include geometry now, and the above example seems to be working
