### ISSUE TITLE
Too many ways to define opacity..

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#466]
@davidmanzanares 

I think we need to bring back the discussion of `opacity` as its own style property.

Now that we are in the process of explaining VL to people, it worries me a little that opacity needs [so much explaining](https://github.com/CartoDB/carto-vl/pull/462#pullrequestreview-123379014). In my opinion, opacity is equivalent to `color`, `width`, etc.

Right now, there are several ways to define opacity:

1.  using a color space: (rgba, hsla, etc.)
2. with a ramp: (`opacity(ramp($attribute.....),1)`
3. with blend: `blend(0.1,1,linear($attribute,.....))`
4. for animation: `filter: torque(linear($time,...,...)) + 1`

looking at the examples above, I want to bring back up the original conversation of bringing `opacity` out as a styling property that is equivalent to `color`, `width`, etc. 

My proposal is to have `opacity` and `strokeOpacity`.

Thoughts and reasons for/against?

cc @Jesus89 @arianaescobar

**Comment by davidmanzanares** [comment]
Personally, I don't think it's better, but, more importantly, it's a little bit too late for the Beta release. This is a major change, not just from an API point of view, but from the implementation point of view.

Regarding the current ways to define opacity, the method number 3 is not a way to change the opacity. So, we would have:

1. Using rgba/hsva... I think this is not very difficult, it is expected, and it is consistent with CSS.
2. opacity(color, 0.4) This is could be a little bit surprising, but I think it can be explained.
3. filter. This modifies the opacity, but that's an extra feature. This is intended for filtering, and it is used for filtering the viewport aggregations too.

If we had an `opacity` we would need to choose between two options:

- Keeping the current ways to define it. If we do that we should define how `opacity` interacts with a color who has an opacity. Will it override? will it multiply it? Will it throw an error?
- Removing the current ways to define it. If we do that we are removing the easy rgba/hsva functions and we are making difficult to make complex expressions like the multi-scale ones. Right now, if we want to mix 2 expressions for different zoom levels we would have something like:
`blend(rgba(...), hsva(...), linear(zoom(), ...))` If we remove the current support for opacity, we would need two blends with two linears, one for the color and one for the opacity

I understand that there has been some discussion in that guide, but I think that's more a developer discussion than a user discussion. Regarding the users, I can see how CartoCSS made some opacity changes easier, but in the long run, I think this is much more flexible with an acceptable, yet not free, cost.

**Comment by makella** [comment]
@davidmanzanares 

Thank you for the detailed response. I have more to say, but first question:

Why isn't number 3 a way to change opacity? We are ramping opacity based on an attribute value. It is like symbol size blending but for opacity.

I've used it on several occasions for example:
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoicHJlZGljdGlvbl90b3BfY29weSIsImIiOiIiLCJjIjoid3h1LWNhcnRvIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJjb2xvcjogb3BhY2l0eShyYW1wKGJ1Y2tldHMoJHByZWRpY3Rpb24sWzQwMDAsNDUwMCw1MDAwLDU1MDAsNjAwMF0pLCBbeWVsbG93LHJlZF0pLGJsZW5kKDAuMSwxLGxpbmVhcigkcHJlZGljdGlvbiw0MDAwLDgwMDApKSlcbnN0cm9rZVdpZHRoOiAwIiwiZiI6eyJsbmciOi03NC4wMjIzOTI1Nzk1NzY1NSwibGF0Ijo0MC43Mzk5OTY3MjYxMDA5MX0sImciOjExLCJoIjoiVm95YWdlciJ9

I can clearly see the variation in opacity so wondering what you mean.

**Comment by davidmanzanares** [comment]
Oh, I see your point, but, number 3 is the same as number 2: `opacity(SOME_COLOR_EXPRESSION, SOME_NUMERIC_EXPRESSION)`. In number 2 you have a literal like `0.5` and in number 3 you have an expression like `blend`), but you could have much more things, all of them are just usages of `opacity`.

**Comment by makella** [comment]
Yeah, exactly, the variety of usages for `opacity` that's kinda the whole thing I was thinking about when writing the initial issue.

I totally see your points particularly with multi-scale and my first reaction is to say, "well, that is also the case with color, width, etc."  but I definitely want to think through all of this more using the examples that you mention above to figure out all the use cases with tangible examples before responding more thoughtfully to your points. :)

In the meantime, why would we have [this example](https://carto.com/developers/carto-vl/reference/#cartoexpressionsopacity) in the reference where we are  using `rgba` for string and `opacity(rgb,0.5)` for the javascript example with the text saying "Equivalent to `s.rgba(0,0,255,0.5)`"

Why wouldn't we just use `rgba` in both examples?  Don't you think that further propogates the confusion?

**Comment by makella** [comment]
closing this for now. if needed, will re-open when appropriate.
