### ISSUE TITLE
Allow zooming in / zooming out in examples

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#482]
I understand we just wanted to disabled zooming by using the scroll wheel. However, users want to be able to play with zoom. We could add some buttons to solve this.

cc: @arianaescobar @makella

**Comment by makella** [comment]
ah! good idea.

totally agree.

**Comment by arianaescobar** [comment]
+1!

**Comment by makella** [comment]
from @pramsey 
Feedback: None of the examples includes a traditional +/- zoom tool in the map. Trial and error, I figured I could zoom in w/ a 2x click, but never figured out zoom out.

**Comment by davidmanzanares** [comment]
Fixed by #921
