### ISSUE TITLE
Add simulation time controls to torque

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/carto-vl#494]
In addition to the existing getSimTime I propose adding several functions to control simulation time:

* `pause()` would stop the animation; getSimTime() would freeze, returning the same value while torque is paused.
* `resume()` resume the animation (from the paused sim. time)
* `setSimTime(t)` advance the cycle to the specified simulation time

That would allow the users to implement UI controls for the animations

**Comment by davidmanzanares** [comment]
:+1:

I would add a `stop()` too.
