### ISSUE TITLE
[Firefox] `Error: invalid MVT date` using torque filter

### ISSUE THREAD

**Issue by skgsergio** [CartoDB/carto-vl#499]
Using `torque` filter with the dataset linked below you get the error `invalid MVT date` on Firefox when decoding MVT.

The same dataset and code works on Google Chrome.

## Versions
Firefox: 60.0.1
CARTO VL: 0.3.0 and 0.4.0

## Dataset
https://team.carto.com/u/sconde-carto/tables/lightning_1527964850/public

## Code
```javascript
     const map = new mapboxgl.Map({
       container: 'map',
       style: 'https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json',
       center: [-20, 35],
       zoom: 2,
       dragRotate: false
     });

     carto.setDefaultAuth({
       user: 'sconde-carto',
       apiKey: 'default_public'
     });

     const layer = new carto.Layer(
       'layer',
       new carto.source.Dataset('lightning_1527964850'),
       new carto.Viz(`
color: ramp(linear($mcg, 360, 0), ORYEL)
width: ramp(linear($mcg, 0, 360), [8, 7, 6, 5, 4, 3])
filter: torque($timestamp, 50, fade(0, 0.5))
       `));

     layer.addTo(map);
```

**Comment by IagoLast** [comment]
Once https://github.com/CartoDB/carto-vl/issues/130 is merged this issue should be fixed.

(This is because firefox has problems parsing dates as strings. The PR aims to send the dates as numbers instead)

**Comment by rochoa** [comment]
This duplicates https://github.com/CartoDB/carto-vl/issues/416
