### ISSUE TITLE
Humongous line renders on top of the map

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto-vl#506]
![cartovl bug](https://user-images.githubusercontent.com/1078228/41033656-a050744c-6987-11e8-9eb1-cfae6ec4c123.gif)

While zooming, a godzilla line crosses the screen. You can use the branch `line-bug` in [https://github.com/ivanmalagon/hackarto-vl/tree/line-bug](https://github.com/ivanmalagon/hackarto-vl/tree/line-bug) to reproduce it.

The data is private so be careful and nice.

Related: https://github.com/CartoDB/carto-vl/issues/185

**Comment by jgoizueta** [comment]
Hey RT people, I'll take care of this with the Carto VL team (we're busy fighting for who's solution to commit 😈 )

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/carto-vl/pull/219
