### ISSUE TITLE
Review performance on FF 60

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#507]
There seem to be some huge performance problems in FF 60 under Ubuntu 16.04

**Comment by IagoLast** [comment]
Tested in ffox 60.1 on my osx and I'm getting this warnings.

<img width="1406" alt="screen shot 2018-06-14 at 17 00 00" src="https://user-images.githubusercontent.com/2657897/41420357-84137cd4-6ff4-11e8-8d9f-02ac24a1ca34.png">


should we create a new issue?

**Comment by IagoLast** [comment]
also the . `styling/animation.html` is not working

**Comment by davidmanzanares** [comment]
The warnings are a known-issue, Mapbox GL developers complained about it to Firefox devs, and Firefox devs refuse to remove the warnings. My point of view on the root cause is that Firefox shouldn't show those warnings, so hopefully, they change the behavior.

About the `animation.html`, please, open a new issue with details.

**Comment by rochoa** [comment]
Feel free to open again if the issue persists.
