### ISSUE TITLE
Rendering artifacts between tiles

### ISSUE THREAD

**Issue by skgsergio** [CartoDB/carto-vl#510]
Rendering lines with opacity causes some regions with colors blended and, therefore, with a different alpha result.

As the regions are well defined areas seems that it is tiles olverlaping between them.

This is with my torque map:
<img width="760" alt="screen shot 2018-06-06 at 15 25 51" src="https://user-images.githubusercontent.com/186349/41041026-4a680038-699e-11e8-9d6a-f1a1277cd416.png">

And this is the same dataset without torque filter:
<img width="321" alt="screen shot 2018-06-06 at 15 27 59" src="https://user-images.githubusercontent.com/186349/41041029-4b77aeb0-699e-11e8-8f6a-eec6c8316496.png">

Source: https://gist.github.com/skgsergio/51d3527e9ebf4ee46bd7f6451cf7f825

**Comment by davidmanzanares** [comment]
I just found the problem, we are using a small buffer size, but we are only clipping polygons, not lines.
