### ISSUE TITLE
Default cursor doesn't help user notice interactive features

### ISSUE THREAD

**Issue by pramsey** [CartoDB/carto-vl#518]
As seen in the [interactivity example](https://carto.com/developers/carto-vl/examples/maps/guides/interactivity/popups.html) the default cursor is the "pan hand" which doesn’t change as it transits through the features. This (a) means there’s no affordance saying “hey, you could click here” and (b) the cursor doesn’t provide a good tight target showing exactly where the click will hit (the “pan hand” isn’t made for targeted clicking).

We could say "hey devs, this is a problem you all must fix", ala @jesusbotella 
```javascript
 const mapboxGLCanvas = document.querySelector('.mapboxgl-canvas');
    
    interactivity.on('featureEnter', featureEvent => {
      mapboxGLCanvas.style.cursor = 'pointer';
    });

    interactivity.on('featureLeave', featureEvent => {
      mapboxGLCanvas.style.cursor = 'default';
    });
```
Or maybe if there's a featureEnter event live the library could do it for the developer automagically.

**Comment by davidmanzanares** [comment]
Yes, I think that the magic solution would be the best option. Good snippet!

@arianaescobar @makella Do you agree on adding this behavior?

**Comment by IagoLast** [comment]
+1

**Comment by jesusbotella** [comment]
I do vote for the magic solution, especially because the event has a huge delay when you have so many polygons (as we did in our hackarto map), so the cursor is set after a few seconds of waiting and is not responsive at all.

**Comment by davidmanzanares** [comment]
Hmu... that delay shouldn't be of a few seconds. We know that the interactivity code is basically not optimized. But, we didn't run into performance problems. It would be good to have an example to test it, confirm it, and do the acceptance after a fix. Therefore, could you open a new ticket with that, including the code? Thank you @jesusbotella !

**Comment by IagoLast** [comment]
I dont like the idea of multiple events changing the style from a performance point of view. Maybe a static css overriding the mapbox default one and then let the user manually update the cursor on feature hover would be our best option. 

We can also give some magic:

```js
// Changes the cursor when the user moves the mouse over a feature, default: `false`
carto.dynamicCursor = true;
````

**Comment by IagoLast** [comment]
wops, I just realized we are going to need both events in every case... maybe it's time to think about some optimizations for the interactivity

**Comment by arianaescobar** [comment]
I completely agree. I actually asked @Jesus89 about this months ago and he told me it was a Mapbox limitation. But if we can make the cursor change as it should, let's definitely do it.

**Comment by pramsey** [comment]
OMG, I love that pointy hand.
