### ISSUE TITLE
Slightly confusing step in the Getting Started guide

### ISSUE THREAD

**Issue by kukukaka** [CartoDB/carto-vl#521]
Hi!

I started yesterday with some of the VL tutorials and I found a slightly confusing step in the Getting [Started guide](https://carto.com/developers/carto-vl/guides/getting-started/). It's very basic and easy to understand but I just wanted to share it as for a completely noob like me was not crystal clear at first.

In the step when the user defines the layer 
const layer = new carto.Layer('layer', source, viz);
layer.addTo(map);
there is a link to an example with the result where you can see the map with all the dots. But what the user gets at that point with the code examples is an empty map as the dots don't render until you declare viz, that is in the next section and that should be above it in the users code.

![screen shot 2018-06-07 at 10 25 11](https://user-images.githubusercontent.com/8354661/41087703-9cab6cfa-6a3d-11e8-8da1-123b2a94b27a.png)

Sorry, if I misunderstand something. Yesterday was my first try and the documentation was super helpful :)

**Comment by davidmanzanares** [comment]
Yes, I agree this is confusing. I think we could move the style definition to be above the layer definition.

cc: @IagoLast @arianaescobar

**Comment by arianaescobar** [comment]
@kukukaka thank you for the feedback!

@davidmanzanares What about moving the map example to the style definition instead? In my mental model, you can't define a style if you don't have a layer to style, so changing the order might make it confusing as well.

**Comment by davidmanzanares** [comment]
> What about moving the map example to the style definition instead?

What do you mean? :confused: 

I think of a style/viz as a requirement for creating the layer, which I think it's a common pattern.

However, I just spotted another problem, it says "Defining the style", but it should say "visualization".

**Comment by IagoLast** [comment]
IMO we should move the `defining the viz` step just before `defining the layer`

**Comment by davidmanzanares** [comment]
@arianaescobar Yes, I see what do you mean. Could we have a final section that summarizes it all, and says something like "with all those steps together you get this example map"?

**Comment by arianaescobar** [comment]
@davidmanzanares Yes, definitely! 

But if you guys are sure about reordering the steps, go ahead.

**Comment by IagoLast** [comment]
so... what do we do here?

**Comment by arianaescobar** [comment]
Move the viz step on top of the layer step and only keep the final example at the end.
