### ISSUE TITLE
Examples without legend in dev center

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/carto-vl#525]
None of the examples have a visual/color legend (they have only text) or a time slider for the animated maps. 

They look cool but it is difficult to understand what do they represent. 

For example: https://carto.com/developers/carto-vl/examples/#example-taxi-pickups

**Comment by davidmanzanares** [comment]
Blocked for https://github.com/CartoDB/carto-vl/issues/572

**Comment by rochoa** [comment]
Working on a time slider example will make more sense when we finish https://github.com/CartoDB/carto-vl/issues/551.

**Comment by VictorVelarde** [comment]
Why is this on CR? What's the next step?
Maybe we could split it in two parts: 
* legends
* time slider

**Comment by davidmanzanares** [comment]
I think I moved this because to leave it close to the legends issue, which it depends on. But there is nothing to CR yet, in fact the other PR was CR'ed and it's on development now

**Comment by elenatorro** [comment]
I agree with @VictorVelarde we should split this issue. The legends issue (https://github.com/CartoDB/carto-vl/issues/572) is on CR, I can take this one once it is merged.

**Comment by makella** [comment]
just to update here, we will have legend examples in the examples section that will include the ones that we've added in the guide as well as ones for other geometries/map types
