### ISSUE TITLE
Add syntax sugar for imageList expression

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#529]
Related with: https://github.com/CartoDB/carto-vl/pull/343

Now, when we define a set of sprites in order to pass them to a ramp, we use the following syntax:

```js
const viz = new carto.Viz(`
    symbol: ramp(buckets($pop_max, [1000000]), sprites([sprite('./marker_1.svg'), sprite('./marker_2.svg')]))
    symbolPlacement: align_bottom
`);
```

It would be nice to be able to avoid the `sprites` "method" and use the expression as follows:

```js
const viz = new carto.Viz(`
    symbol: ramp(buckets($pop_max, [1000000]), [sprite('./marker_1.svg'), sprite('./marker_2.svg')]))
    symbolPlacement: align_bottom
`);
```

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/carto-vl/pull/818
