### ISSUE TITLE
Buckets($count, 10) should throw with a good error message

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#530]
Buckets($count, 10) should throw with a good error message

**Comment by VictorVelarde** [comment]
@davidmanzanares is this $count related to `globalCount` / `viewportCount`? How the error message should look like?

**Comment by davidmanzanares** [comment]
Oops, sorry about the incomplete description. The problem is not the `$count`, that was just a placeholder, the problem was with `10` since buckets second parameter should be an array.

**Comment by VictorVelarde** [comment]
Done! 🚀
