### ISSUE TITLE
Guide for sprites

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#533]

**Comment by davidmanzanares** [comment]
Hey @makella I've stubbed (if that can be named a stub) the guide for sprites here: https://github.com/CartoDB/carto-vl/pull/655/files#diff-6e26cab6cbf3375643ba9142e990a2c3R1

The support for built-in sprites is in that PR too.

Let me know what you think

**Comment by makella** [comment]
great! will take a look!
