### ISSUE TITLE
Provide default sprites within CARTO VL

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#535]
I think we could add some sprites as CARTO VL constants, just like we include Cartocolors.

We should be careful though since it could increase the bundle size considerably. I think we should aim for less than 50KB gzipped (SVG wins).

I don't know if you already have a repo I can include as a dependency in the project and use it, or if those SVGs would be added directly to this repo.

**Comment by arianaescobar** [comment]
Huh... I'm not sure. Maybe we could use some of the sprites that we offer on Builder. 

@ivanmalagon are those icons on a particular repo we could include? If not, can you point me to where those files are so we can reuse them for VL? 

@davidmanzanares great idea btw :)

**Comment by makella** [comment]
Yes! great idea. The one thing that we will want to make sure is that we get updates of some of the icon libraries we are using (like Mapbox Maki). I know we have other sets in Builder. Many of them I don't think are used, but I definitely think we can come up with a set of the 20 most used icons (or something) and have that be a starting point for the VL offering.

**Comment by arianaescobar** [comment]
Yeah, I agree that we don't need to offer a huge amount of options. @makella we can decide together what those 20 icons should be about. 

It would be ideal to know which ones are the most used on Builder, but maybe we don't have that metric. Do we @ivanmalagon?

**Comment by arianaescobar** [comment]
Thank you @ivanmalagon! 

It would be fantastic if you could help us with that, @javitonino ✨

**Comment by davidmanzanares** [comment]
After having the set of sprites, we'll need to discuss the API for accessing them. I propose:
String API: `symbol: markerFill`
JS API:       `{symbol: s.sprites.markerFill}`

What do you think?

**Comment by arianaescobar** [comment]
`markerFill` being the name of the sprite?

**Comment by davidmanzanares** [comment]
Exactly

**Comment by arianaescobar** [comment]
LGTM. 

Although, how about just calling the fill version by the type name (`marker`, `flag`, `circle`, `triangle`...) and only adding the extra word for the outline version (`markerOutline`, `flagOutline` OR `markerStroke`, `flagStroke`)?

**Comment by davidmanzanares** [comment]
It sounds better. Although, at the same time, I'm worried about polluting too much the global namespace. It's not a problem for the JS version since there is a `sprites` namespace, but I didn't use one in the String version. This could be a problem since some of the sprites will have a really short name like `X`.

However, we could have the same namespace for the String API.

String API:
`symbol: sprites.marker` 
`symbol: sprites.markerOutline`

JS API:
`{symbol: s.sprites.marker}`
`{symbol: s.sprites.markerOutline}`

What do you think?

**Comment by davidmanzanares** [comment]
I just posted it, and I just remembered that we are already using `sprites` as the function name to be used with `ramp`. If we want to stick to `sprites` for this, we'll need to rename the other one or use syntax sugar (there is an issue with that).

**Comment by arianaescobar** [comment]
I don't think we should do that, the whole point of removing the `Fill` part was to make it shorter and simpler. `sprites.marker` is longer than `markerFill` haha

**Comment by davidmanzanares** [comment]
I see, could we rename the sprites with short names (or leave them out of the set)?

**Comment by arianaescobar** [comment]
Sure, we can definitely rename them :)

**Comment by arianaescobar** [comment]
@davidmanzanares 

bicycle
building
bus
car
circle
circleOutline
cross
flag
house
marker
markerOutline
plus
square
squareOutline
star
starOutline
triangle
triangleOutline

[sprites.zip](https://github.com/CartoDB/carto-vl/files/2163491/sprites.zip)
