### ISSUE TITLE
Viewport agg precision

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#536]
**Ongoing PR:** https://github.com/CartoDB/carto-vl/pull/635

We are currently checking if a geometry is in the viewport by checking if the bounding boxes of the geometry and the viewport collide.

However, this fails when bounding boxes collide but the geometry does not.

**Example:**

1. It works because both the geometry and the geometry's bounding box collide with the viewport.

![collision](https://user-images.githubusercontent.com/3824953/41974242-b59f4a44-7a17-11e8-9b5a-d4012b5ee77b.png)

2. It does not work because here the geometry does not collide with the viewport.
![no collision](https://user-images.githubusercontent.com/3824953/41974241-b573fc54-7a17-11e8-9cb8-71dc86c5345d.png)

**Comment by elenatorro** [comment]
Merged 🚀 great job, team!
