### ISSUE TITLE
User integration tests: too many active WebGL contexts

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#537]
If you open a chrome with `yarn test:user:watchc` you'll see `WARNING: Too many active WebGL contexts. Oldest context will be lost.`

**Comment by Jesus89** [comment]
Is this still happening?

**Comment by davidmanzanares** [comment]
This in particular seems to have been fixed, but there are many similar problems, I opened https://github.com/CartoDB/carto-vl/issues/846
