### ISSUE TITLE
Restructure source code directories

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#544]
The current directory structure doesn't make sense.

For example, we have the code for the Maps API in a `client/` directory separated from the `api/source/` folder, and we have the expressions under the `core/...` path (not in the `api/` path), which doesn't make any sense since 90% of the API is defined by the expressions.

**Comment by IagoLast** [comment]
lgtm but:

- what about `setup`, `interactivity`, `layer` and `map` ?
