### ISSUE TITLE
Lines style properties

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#55]
Minimum properties to support for line geometries:
 - [x] Width.
   - [x] Example.
 - [x] Fill-color.
   - [x] Example.
 - [x] Fill-opacity — do we want to separate fill from stroke opacity?
   - [x] Example.

Nice to have:
 - [ ] Stroke?

Known issues:
 - [x] https://github.com/CartoDB/renderer-prototype/issues/36.

cc @makella

**Comment by makella** [comment]
@rochoa 

so `Stroke..` properties are for polygon and point lines, right? And the remainder for line?

if so, I think your proposal covers the basics.

regarding the part about fill and stroke opacity I think it is a discussion worth having at all levels...
right now, we have opacity available in two ways... via the alpha channel `rgba, hsva, etc.` OR via the `color` property... `color: opacity(h,s,v),0.5`

another level of this is associating properties to their geometries. For example, `color` can be for points, lines, or polygons... with this way of doing things, we currently don't have the option to separate additional geometry-specific properties.

see more: 
https://github.com/CartoDB/renderer-prototype/issues/52

**Comment by rochoa** [comment]
Updated the minimum to remove "stroke".

**Comment by rochoa** [comment]
I would like to know what @davidmanzanares thinks about the opacity situation.

**Comment by davidmanzanares** [comment]
@rochoa The opacity situation is being discussed here: https://github.com/CartoDB/renderer-prototype/issues/52

Regarding " do we want to separate fill from stroke opacity?" that's already implemented, the thing is how we should do export that. In any case, that has little to do with lines, it is orthogonal to it.

The most problematic issue with lines is https://github.com/CartoDB/renderer-prototype/issues/36 
that one requires more than a few changes.

**Comment by rochoa** [comment]
I put "do we want to separate fill from stroke opacity?" in all different geometry types. Good to know the status, thanks.

The mentioned issue is already linked above.

**Comment by makella** [comment]
My only thought here is that when I think of `stroke` I think of an outline of an object... the stroke of a marker, the stroke of a polygon, the stroke around text... but to me a line is a different feature than an outline. 

Also, as noted in [this issue](https://github.com/CartoDB/renderer-prototype/issues/207) there are specific properties associated with a feature's stroke and I don't think those necessarily will transfer over to line geometries.

What about:

`linecolor` and `linewidth`?

**Comment by davidmanzanares** [comment]
> I  think of an outline of an object...

Yes, that's my point of view too.

> linecolor and linewidth?

I think the problem with those is that then, we should have `pointcolor`, `pointwidth`... to be consistent.

**Comment by Jesus89** [comment]
In vector graphic editors like Inkscape they use:

- `fill`: for the color
- `stroke`: for the line color
- `stroke-width`: for the line width
- `stroke-X`: for more line properties like join, dashed, etc

This is very related to the SVG format.
- Definition of a [circle](https://www.w3schools.com/graphics/svg_circle.asp)
- Definition of a [line](https://www.w3schools.com/graphics/svg_line.asp)
- Definition of a [polygon](https://www.w3schools.com/graphics/svg_polygon.asp)

Applied to our case, the most matching solution with the SVG in mind would be

```

**Comment by makella** [comment]
Personally, I like being explicit per geometry. Yes, styling properties can be shared, but in the future if we add additional styling capabilities some of them could be specific to a geometry type and so being explicit will provide us greater flexibility in those situations.

@Jesus89 I'm good with your suggestions with the exception of `point-radius` that kind of breaks the logic and will require people to remember something else. Also, I'm guessing in the future (like in the SVG doc) that we would support something like `point-height` so `point-width` vs. `point-radius` seems to go along better with that logic.

@davidmanzanares regarding your syntax (`linewidth` vs. `line-width`) is there a reason to do one or the other? I'm impartial but curious.

**Comment by rochoa** [comment]
Some agreements during our last meeting:
 - Rendering properties will follow camelCase notation, both, in String and JS APIs.
 - `width` for points and lines.
 - `color` to be used across all geometry types.
 - In polygons and points, we will use `strokeWidth`.
