### ISSUE TITLE
/examples/guides/interactivity/featureEnter.html is broken from a design point of view

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#554]
The point opacity is changed very very slightly on hover, it's almost imperceptible.

We should change the style :slightly_smiling_face:

**Comment by arianaescobar** [comment]
We definitely should. 

This is the map: https://carto.com/developers/carto-vl/examples/maps/guides/interactivity/featureEnter.html

It's on the Introduction to Interactivity guide. 

I can take a look later.

**Comment by makella** [comment]
PR:
https://github.com/CartoDB/carto-vl/pull/760

**Comment by makella** [comment]
done!
