### ISSUE TITLE
Sprite examples are broken from a design point of view

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#556]
I forgot about the design aspect of them on the sprite PR :sweat_smile:.

Here are the links:
https://cartodb.github.io/carto-vl/examples/expressions/sprite.html
https://cartodb.github.io/carto-vl/examples/expressions/sprite-ramp.html

The first one needs to show the usage of just a single sprite for every feature on the layer and the second one needs to show that you can use multiple sprites, assigning one sprite per category (of course you can have an "others" sprite).

I can try to push this with some help.

cc: @arianaescobar @makella

**Comment by arianaescobar** [comment]
Taking a look...

**Comment by arianaescobar** [comment]
This is my proposal: 

### Sprite
<img width="1440" alt="screen shot 2018-06-15 at 10 12 51" src="https://user-images.githubusercontent.com/16247628/41457751-e711f820-7084-11e8-9810-9169b5a9eafa.png">
<img width="1440" alt="screen shot 2018-06-15 at 10 13 04" src="https://user-images.githubusercontent.com/16247628/41457752-e72c5a3a-7084-11e8-84ed-44676c94e2cb.png">

```
width: (sqrt($pop_max) * 0.003)*zoom()
color: white
strokeColor: black
symbol: sprite('./marker.svg')
```

### Sprite ramp
<img width="1440" alt="screen shot 2018-06-15 at 10 13 15" src="https://user-images.githubusercontent.com/16247628/41457803-23138708-7085-11e8-83ed-0de7ea28af63.png">
<img width="1439" alt="screen shot 2018-06-15 at 10 13 26" src="https://user-images.githubusercontent.com/16247628/41457804-232c8a46-7085-11e8-98e2-ed8a22acb13a.png">

```
width: (sqrt($pop_max) * 0.003)*zoom()
color: ramp(linear($pop_max, 0, 10000000), prism)
strokeColor: black
symbol: ramp(buckets($pop_max, [1000000]), sprites([sprite('./marker.svg'), sprite('./star.svg')]))
symbolPlacement: align_bottom
```
