### ISSUE TITLE
Sprite images can not be loaded from different sources

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#557]
## Context

We do not support cross origin image loading. There is an example in this [gist](https://bl.ocks.org/elenatorro/739ff2c7cfff9deb1adbd20e06d2ef8d):

```js
const viz = new carto.Viz(`
      symbol: sprite('https://cartodb.github.io/carto-vl/examples/expressions/marker.svg')
`);
```

This issue was detected by @oriolbx when trying to use the `marker.svg` file we have in 'https://cartodb.github.io/carto-vl/examples/expressions/marker.svg'. 

The following error is shown:

![captura de pantalla 2018-06-15 a las 10 28 43](https://user-images.githubusercontent.com/3824953/41458751-c7668448-7087-11e8-9250-447cc7c03c32.png)

## Expected behaviour

We should allow users to load sprites from different sources.

## Solution

One possible solution that has already been tested is to set 'crossOrigin' property for images to 'anonymous' in the Sprite constructor:

```js
    this.image.onerror = reject;
    this.image.src = this._url;
    this.image.crossOrigin = 'anonymous';
```

**Comment by ztephm** [comment]
hi @elenatorro i see this was merged, but when we test this HTML:
[index.html.zip](https://github.com/CartoDB/carto-vl/files/2107635/index.html.zip)

which contains this svg:
[http://geopacific.org/carto/cartocss/triangle.svg](http://geopacific.org/carto/cartocss/triangle.svg)

we see the `tainted canvases may not be loaded` error:

![screen shot 2018-06-15 at 6 29 59 pm](https://user-images.githubusercontent.com/1779444/41491959-22fe9740-70ca-11e8-83dd-05f2c2821b2c.png)

Can you help us figure out if we should open a different issue? Thank you.

**Comment by davidmanzanares** [comment]
@elenatorro I think you fixed this, right?

**Comment by elenatorro** [comment]
Hi :) 

Yes, it is fixed. I have tested the URL @ztephm provided, and the problem is that if you want to use images from an external source, you have to ensure that it serves the assets with the headers properly set. 

If you replace the URL with this one https://cartodb.github.io/carto-vl/examples/expressions/marker.svg it works because, as it is shown in the screenshot, the header `Access-Control-Allow-Origin:` is set to `*`. 

<img width="273" alt="captura de pantalla 2018-06-18 a las 11 46 46" src="https://user-images.githubusercontent.com/3824953/41529484-9d13d5ca-72ed-11e8-835f-bf732a30f916.png">

If you want to use `.svg` images, you have to serve your assets with the header options configured to allow the "origin" to access the assets. There is more information about this [here](https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Access-Control-Allow-Origin). 

Hope it helps! :)

**Comment by ztephm** [comment]
thanks for the explanation @elenatorro ! closing
