### ISSUE TITLE
Add image example with real categories

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#560]
I think it would nice to have another sprite example similar to the ramp one but with real categories (not categories that comes from the classification of a numeric property).

cc: @arianaescobar @makella

**Comment by arianaescobar** [comment]
I'm sure @makella can help us with a beautiful example of that. But if you're too busy, let me know! I'm sure I can whip something up 🙃

**Comment by makella** [comment]
Are you referring to an example for the editor?

We'll need one for the Dev Center examples so what I'm thinking might be best is to wait until we get the icons from our top list added and then make a map that demonstrates the sprite functionality with the option of multiple marker types.

How does that sound?

**Comment by makella** [comment]
Or if we need a quick one, here is one where marker is colored by cause of fire and sized by acres burned

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiZmlyZV9wZXJpbWV0ZXJzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6ICRnaXNfYWNyZXMvMTAwMDAwKnpvb20oKVxuY29sb3I6IHJhbXAoYnVja2V0cygkY2F1c2UsWzEsMiwzLDQsNSw2LDcsOCw5LDEwLDExLDEyLDEzLDE0LDE1XSksIFByaXNtKVxuc3ltYm9sOiBzcHJpdGUoJy4uL2V4cHJlc3Npb25zL21hcmtlci5zdmcnKVxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTExNy43MzE4Nzc1OTQ1OTA3NCwibGF0IjozNi42ODYyNTc1ODYzODAxNX0sImciOjQuNzkxMDg1MjE4MjAxNzk4LCJoIjoiRGFya01hdHRlciJ9

**Comment by arianaescobar** [comment]
+1 to waiting for the markers

**Comment by makella** [comment]
@davidmanzanares I think we can close this now, right?

**Comment by davidmanzanares** [comment]
Sure!
