### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#565]
I think we should improve the Readme of the project since it is one of the first pages that a user could see of CARTO VL.

In general, we could be more end-user focused rather than CARTO VL developer focused. 

For example, I think we could "pitch" the library a little bit more, and stop mentioning some internals like "how to release a new version to the Carto CDN". Another example will be to provide links to the released versions on the CDN instead of displaying how to generate the documentation from the source code.

Also, we have a few static images with some example maps, we could set the image's links to the real maps.

cc: @arianaescobar @makella

**Comment by arianaescobar** [comment]
Sounds great! I like that way of thinking!

**Comment by makella** [comment]
+1!

We could probably take some language from all of the resources we have been compiling over the past few weeks.

I'll start looking through to see if there are some good starting points for the text part.

**Comment by davidmanzanares** [comment]
`CONTRIBUTORS.md`?

**Comment by IagoLast** [comment]
We already have a [CONTRIBUTING.md](https://github.com/CartoDB/carto-vl/blob/master/CONTRIBUTING.md) file, my idea was use this file to keep general guidelines and the DEVELOPERS.md with more specific topics but we can use CONTRIBUTING.md for all if you prefer
