### ISSUE TITLE
MVT Source Metadata definition

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#576]
Related to https://github.com/CartoDB/carto-vl/pull/487

We need to define a Metadata API for the new MVT source.

## Metadata usage

GeomType:
    - used for selecting style defaults

Column types:
    - Type checking on expression's _compile method

Min, Avg, Max, Sum:
    - Global agg expressions

Sample:
    - Global agg (Percentile) expression

Category count:
    - top() expression

## Proposal

Geomtype:
    - autodiscovery to simplify MVT usage
    - for windshaft, it's on the metadata, so we could speed up start-up time by pre-compaling the shaders before the first tile comes

Column types:
    - autodiscovery to simplify MVT usage
    - for windshaft, it's on the metadata, so we could speed up start-up time by pre-compaling the shaders

Min,Avg,Max,Sum, Sample and Category count:
    - for windshaft, it's on the metadata
    - for MVT, it's optional in the metadata, if it is not present and the user tries to use these functions => Error!

### Required changes

The MVT source should return the metadata once the first tile comes, layer should prepare the source to be able to produce tiles before waiting for the metadata.

decodeProperty should return string, number or undefined. When it returns other than undefined => check type, if undefined => set type on metadata

API for Metadata:
```
{
    properties: {
        wadusProperty: {
            max: 10,
            min: 5,
        },
        wadusCatPropertyName: {
            categories: {
                red: {count: 100},
                blue: {count: 12},
                green: {count: 3},
            }
        },
    },
    sample: [
        { wadusProperty: 6, wadusCatPropertyName: 'blue'},
        { wadusProperty: 7, wadusCatPropertyName: 'red'},
        { wadusProperty: 6, wadusCatPropertyName: 'blue'},
    ]
}
```

**Comment by jgoizueta** [comment]
On one hand I'd like to be able to manually define all the metadata when defining the MVT source (the user can know things we don't know, it would allow to have date properties as we have in GeoJSON, and we could optimize this case as you mention for Windshaft). On the other hand it's clear that the most common case is that the user has no clue/doesn't care so we need to support autodiscovery, and given that it would be a pain to support both (autodiscovery and manual metadata).

**Comment by jgoizueta** [comment]
I think the API is OK (sample is optional, and most users won't provide it)

How could we acomodate in it the info about date properties? (as we do in the GeoJSON)

**Comment by davidmanzanares** [comment]
Talking off-channel with @jgoizueta and @rochoa, we decided to not implement date properties in MVT right now.

**Comment by davidmanzanares** [comment]
Well... I was wrong, quite wrong.

Trying to autodiscover the types of the columns is a **bad idea™**. Since the MVT format doesn't provide the schema of the tile and since it doesn't provide any information for a value if it was `NULL` originally, we can try to autodiscover the types, but if the first tile contains few features and those features have `NULL` in all the values for a column we won't autodiscover that type, which will make the compilation crash.

I think there is no way to overcome this limitation and that we should force the user to set the type for all the properties that the user may use.

cc: @rochoa

**Comment by davidmanzanares** [comment]
Talking about bad ideas, using the category names as the keys in the JSON was another one since the keys of a JSON must be strings, and therefore, we wouldn't be able to differentiate the `null` value.

I guess one day I'll get it right:
```
{
    properties: {
        wadusProperty: {
            max: 10,
            min: 5,
        },
        wadusCatPropertyName: {
            categories: [
                {name: 'red', count: 100},
                {name: null, count: 12},
            ]
        },
    },
    sample: [
        { wadusProperty: 6, wadusCatPropertyName: 'blue'},
        { wadusProperty: 7, wadusCatPropertyName: 'red'},
        { wadusProperty: 6, wadusCatPropertyName: 'blue'},
    ]
}
```
