### ISSUE TITLE
Sprites with original color from asset

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#589]
Right now, all sprites' colour is overridden with the `color` property. That means that using a PNG file for, let's say, your supermarket brand will get always the default _red_ `color` property, which is far from ideal.

We should support maintaining the original colours from the asset somehow.

After talking with @davidmanzanares, we envision two options:

1. No override of the asset colour when the `color` property is not defined.
1. The `color` property to behave different in combination with the `symbol` property, being the default colour `white`. Furthermore, the `color` will apply a `multiply` operation, that's why we want to have white as the default colour, so you can control how to transform the original colour of the asset.

@makella, @arianaescobar, what do you think about this?

**Comment by makella** [comment]
@rochoa @davidmanzanares 

I'm not sure I understand this part... is there a visual example?

>The color property to behave different in combination with the symbol property, being the default colour white. Furthermore, the color will apply a multiply operation, that's why we want to have white as the default colour, so you can control how to transform the original colour of the asset.

**Comment by arianaescobar** [comment]
I'd say this is the best option 

> No override of the asset colour when the color property is not defined.

**Comment by davidmanzanares** [comment]
Fixed by https://github.com/CartoDB/carto-vl/pull/592
