### ISSUE TITLE
MVT source with too many attributes

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#591]
The MVT source—this might apply also to GeoJSON—should handle a lot (~500) of attributes. With our current approach, we don't take care of optimizing the attributes we use for the visualization, degrading the performance as the number of attributes grows.

We need to optimize the way we handle MVT tiles with more attributes than needed, being able to dynamically use just the ones required at any given moment.

**Comment by davidmanzanares** [comment]
![perf-too](https://user-images.githubusercontent.com/1692175/41925840-07aa4f46-796e-11e8-98c1-ecdea40cfa62.png)
Seems our guess was right, the bottleneck is the GPU upload
