### ISSUE TITLE
Desynchronizated torque layers

### ISSUE THREAD

**Issue by skgsergio** [CartoDB/carto-vl#599]
With the last beta release, my map with two torque layers that were in sync now shows desynced.

Both datasets have a timestamp column that has the same range:
`MIN(timestamp) = 2018-06-03T22:15:18Z`
`MAX(timestamp) = 2018-06-03T22:38:09Z`

The first dataset is just points and the second one is a bunch of lines in a `n lines:1 point` relation, all n lines for a point has the same timestamp.

In the following GIF you can observe the issue (top image) and the expected result (bottom image) that is the behavior of the previous beta release.

![output](https://user-images.githubusercontent.com/186349/41732670-ea4df10e-7581-11e8-961d-d3ff5aeb0f6f.gif)

Sorry for the videoconsole quality like GIF, but GitHub doesn't let me add images bigger than 10MB

## Version
The issue showed in `0.5.0-beta.3`
Last known working version was `0.5.0-beta.2`

## Example
https://skgsergio.github.io/cartovl/lightning-lines.without-hack.html

Code: https://github.com/skgsergio/skgsergio.github.io/blob/master/cartovl/lightning-lines.without-hack.html

**Comment by skgsergio** [comment]
I had a look the code and I discovered two fancy functions: `{get,set}SimProgress()`:

```
> console.log(lightnings_layer._viz.filter.getSimProgress() + '\n' + lines_layer._viz.filter.a.getSimProgress());
0.4117499999999316
0.40599806518554815
```

And setting the progress to 0 makes both torques to be in sync again 😃

```
> lightnings_layer._viz.filter.setSimProgress(0); lines_layer._viz.filter.a.setSimProgress(0);

> console.log(lightnings_layer._viz.filter.getSimProgress() + '\n' + lines_layer._viz.filter.a.getSimProgress());
0.030016666666667365
0.030033333333333634

> console.log(lightnings_layer._viz.filter.getSimProgress() + '\n' + lines_layer._viz.filter.a.getSimProgress());
0.8711999999999919
0.8712166666666591
```

**Comment by IagoLast** [comment]
Interesting issue, I guess we should think on a standard way to sync animations.

- At viz object level: `viz0.syncAnimation([viz1, viz2])`
- At layer level: `layer0.syncAnimation([layer1, layer2]);`

maybe this should be the default behaviour

cc @rochoa @elenatorro @davidmanzanares @Jesus89

**Comment by davidmanzanares** [comment]
We could automatically sync all the animations by having a global list of animations that still haven't been loaded and a list of loaded, yet waiting list:

1. When an animation is created it is pushed to the TODO list
2. When an animation is loaded it is removed from the TODO and it is pushed to the WAITING. if the TODO list is empty, play all the animations of the WAITING list, and empty that list.

**Comment by IagoLast** [comment]
so from the user point of view, the animations will be always synced right?

**Comment by davidmanzanares** [comment]
Not always, if they manually use stop/pause or if they add a layer after other layers have been loaded, then the animations won't be synched.

**Comment by IagoLast** [comment]
ummm so what we do in case we need to load 2 layers asynchronously and then synchronize the animations?

**Comment by davidmanzanares** [comment]
viz1.anim.setProgress(viz2.anim.getProgress())

**Comment by davidmanzanares** [comment]
As @skgsergio reported and I reproduced this regression has been re-introduced.
