### ISSUE TITLE
(Ab)using isStyleLoaded

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#604]
**ongoing PR**: https://github.com/CartoDB/carto-vl/pull/623

We use `isStyleLoaded` to decide when to load a layer. However, that might be `false` in some situations, e.g. using `fitBounds`, making the layer to not load, not even when the _flight_ finishes.

**Comment by elenatorro** [comment]
Hi @rochoa, how can I reproduce this error? Thanks!
