### ISSUE TITLE
Mapnik variables are broken

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#605]
Usage of `!scale_denominator!` crashes. I checked that the previous gh published version was doing fine, so this is a regression.

Maps API instantiation is slightly different:

![bug-var](https://user-images.githubusercontent.com/1692175/41773664-26d3c93c-761d-11e8-87c8-32281c508008.png)

The response is:
```
{"errors":["column \"scale_denominator\" does not exist"],"errors_with_context":[{"type":"unknown","message":"column \"scale_denominator\" does not exist"}]}
```

cc: @jgoizueta

**Comment by jgoizueta** [comment]
This is solved!
