### ISSUE TITLE
Guides for beta release

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#62]
We are going to create multiple placeholders with the contents to be covered:

- basics
  - what is CARTO VL?
  - what can I do with CARTO VL
  - how authentication works
- viz
   - what is a viz object ? 
     - supported properties
   - styling points
   - styling polygons
   - styling lines
   - colors
   - style by value   

cc @inigomedina @iagolast

**Comment by arianaescobar** [comment]
I'm going to close this one in favour of https://github.com/CartoDB/carto-vl/issues/362
