### ISSUE TITLE
Styling syntax structure: best practices

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#638]
The idea of best practices for formatting styling syntax has come up on several different occasions. As a visualization becomes more complex, so does the [readability of the syntax](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgxLFxuICAgICAgICAgICAgYmxlbmQoMTAsIDUwKmxpbmVhcigkYW1vdW50LHZpZXdwb3J0TUlOKCRhbW91bnQpLHZpZXdwb3J0TUFYKCRhbW91bnQpKSwgbGluZWFyKHpvb20oKSwgMl4xNCwgXG4gICAgICAgICAgICAyXjE2KSksXG4gICAgICAgICAgICBsaW5lYXIoem9vbSgpLCAyXjEzLCAyXjE0KVxuKSBcbmNvbG9yOiByZ2JhKDI1NSwyNTUsMjU1LDAuMilcbnN0cm9rZUNvbG9yOiByYW1wKHRvcCgkY2F0ZWdvcnksNSksdml2aWQpXG5zdHJva2VXaWR0aDogMSAiLCJmIjp7ImxuZyI6Mi4xOTM2NDY5ODgwNTk0MTMsImxhdCI6NDEuMzkxOTkzMjg4NjcyODl9LCJnIjoxMi41NjY4NDA4NjE1ODU1MjYsImgiOiJEYXJrTWF0dGVyIn0=). 

We have things like variables that we can use, but we don't have any guidelines or best practices (even for the team). If we can come up with some guidelines, we can all be sure to follow them throughout the documentation, guides, examples, blog posts, etc. and "teach" them to users through example.

Opening this issue so we can formally discuss!

cc @arianaescobar

**Comment by makella** [comment]
cc @davidmanzanares

**Comment by davidmanzanares** [comment]
Sure! Good idea, we could have something like a limit like 120 characters long, and say that if you are over that limit you should use variables or line breaks. In the case of line breaks, I would do something like this:
```
color: ramp(linear(
                   $wadus,
                   globalPercentile($wadus, 5),
                   globalPercentile($wadus, 95)
            ),
            prism
          )
            
```

**Comment by rochoa** [comment]
Without any further information, we are closing this.

Also, #468 will improve the situation.
