### ISSUE TITLE
Numeric values custom color or CARTOColor schemes

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#645]
*To be done after https://github.com/CartoDB/carto-vl/pull/552*

@elenatorro this is a work in progress! I will finish editing it in the morning and let you know when it is done.

In the meantime,
For testing the scenarios, should I test in the category buckets branch or do you want me to test from Master? 
I'm wondering if it is best in the buckets branch since the color logic for categories is built-in and we will need another set of rules specific for the numeric/sequential.

---

**update**

#### Case 1

* [x] Passed 

When there are less colors than class breaks. In this case, we WILL interpolate.

**Example**
`color: ramp(globalQuantiles($mapcolor13,5),[yellow,turquoise])`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRtYXBjb2xvcjEzLDUpLFt5ZWxsb3csdHVycXVvaXNlXSlcbnN0cm9rZVdpZHRoOiAwXG5cbiIsImYiOnsibG5nIjotNDguODY0MzU1MDgyNzgzNTA0LCJsYXQiOi0yNi40MDE2MTg4Mzg0MTE5NTZ9LCJnIjoyLjc2NDk1NjgxMjQwMzYxNzUsImgiOiJEYXJrTWF0dGVyIn0=

#### Case 2

* [x] Passed 

When there are an equal number of classes and colors. In this case, we will NOT interpolate since there are enough colors for each class break.

**Example**
`color: ramp(globalQuantiles($mapcolor13,5),[blue,turquoise,deeppink,orange,yellow])`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRtYXBjb2xvcjEzLDUpLFtibHVlLHR1cnF1b2lzZSxkZWVwcGluayxvcmFuZ2UseWVsbG93XSlcbnN0cm9rZVdpZHRoOiAwXG5cbiIsImYiOnsibG5nIjotNDguODY0MzU1MDgyNzgzNTA0LCJsYXQiOi0yNi40MDE2MTg4Mzg0MTE5NTZ9LCJnIjoyLjc2NDk1NjgxMjQwMzYxNzUsImgiOiJEYXJrTWF0dGVyIn0=

#### Case 3

* [x] Passed 

When there are more colors than classes. In this case, we WILL interpolate. The first class will get the first color purple and the last class yellow all in-between class breaks will be interpolated between those.

This is different than what we are doing with categories. The reason we should interpolate in this case is because it is numeric data with classification. So a user may define a start and an end color to the scheme and then define additional colors in between to interpolate through.

**Example**
`color: ramp(globalQuantiles($mapcolor13,5),[purple,blue,turquoise,deeppink,orange,yellow])`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRtYXBjb2xvcjEzLDUpLFtwdXJwbGUsYmx1ZSx0dXJxdW9pc2UsZGVlcHBpbmssb3JhbmdlLHllbGxvd10pXG5zdHJva2VXaWR0aDogMFxuXG4iLCJmIjp7ImxuZyI6LTQ4Ljg2NDM1NTA4Mjc4MzUwNCwibGF0IjotMjYuNDAxNjE4ODM4NDExOTU2fSwiZyI6Mi43NjQ5NTY4MTI0MDM2MTc1LCJoIjoiRGFya01hdHRlciJ9

#### Case 1

* [x] Passed 

Linear interpolation across any attribute with >=2 colors defined. In this case, we WILL interpolate.

**Example**
`color: ramp(linear($mapcolor13),[yellow,turquoise])`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAobGluZWFyKCRtYXBjb2xvcjEzKSxbeWVsbG93LHR1cnF1b2lzZV0pXG5zdHJva2VXaWR0aDogMFxuXG4iLCJmIjp7ImxuZyI6LTQ4Ljg2NDM1NTA4Mjc4MzUwNCwibGF0IjotMjYuNDAxNjE4ODM4NDExOTU2fSwiZyI6Mi43NjQ5NTY4MTI0MDM2MTc1LCJoIjoiRGFya01hdHRlciJ9

OR
`color: ramp(linear($mapcolor13),[orange,yellow,green,turquoise])`
`color: ramp(linear($mapcolor13),[red,orange,yellow,green,turquoise,purple])`

etc...

#### Case 2

* [x] Passed 

Equivalent to **Case 1** : >= 2 colors defined. In this case, we WILL interpolate.

**Example**
`color: ramp($mapcolor13,[yellow,turquoise])`

#### Case 1
A user defines custom buckets and custom colors. In this case we WILL interpolate.

**Example**
`color: ramp(buckets($mapcolor13,[1,5,8]),[red,orange,yellow,white])`

#### Case 1

* [x] Passed 

`color: ramp(globalQuantiles($attribute,7),purpor)`
Any time a user uses a CARTOColor scheme between 2-7 class breaks, we **WILL NOT interpolate.**

**Example**
For example, these colors shouldn't be interpolated. Instead, we should use the 3-color sunset version
http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRudW1iZXIsMyksc3Vuc2V0KVxuc3Ryb2tlV2lkdGg6IDBcblxuIiwiZiI6eyJsbmciOi00NS4zMDkwNDExNjQ1NzAwOSwibGF0IjotMjguMjY0NzAzMzI2NzYyNzc4fSwiZyI6Mi4xODUyNjE3NjQzMjEyOTA0LCJoIjoiRGFya01hdHRlciJ9

#### Case 2

* [x] Passed 

If a user has more class breaks (10) than maximum available colors in a sequential scheme (7), then we WILL interpolate.

**Example**
`color: ramp(globalQuantiles($number,13),sunset)`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRudW1iZXIsMTMpLHN1bnNldClcbnN0cm9rZVdpZHRoOiAwXG5cbiIsImYiOnsibG5nIjotNDUuMzA5MDQxMTY0NTcwMDksImxhdCI6LTI4LjI2NDcwMzMyNjc2Mjc3OH0sImciOjIuMTg1MjYxNzY0MzIxMjkwNCwiaCI6IkRhcmtNYXR0ZXIifQ==

#### Case 1

* [x] Passed 

It is equivalent to **Case 2**. 

`color: ramp($mapcolor13,sunset)`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoJG1hcGNvbG9yMTMsc3Vuc2V0KVxuc3Ryb2tlV2lkdGg6IDBcblxuIiwiZiI6eyJsbmciOi00OC44NjQzNTUwODI3ODM1MDQsImxhdCI6LTI2LjQwMTYxODgzODQxMTk1Nn0sImciOjIuNzY0OTU2ODEyNDAzNjE3NSwiaCI6IkRhcmtNYXR0ZXIifQ==

#### Case 2

* [x] Passed 

Linear interpolation with a CARTOColor scheme. In this case, we WILL interpolate the color scheme to account for all of the output values.

**Example**
`color: ramp(linear($mapcolor13),sunset)`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAobGluZWFyKCRtYXBjb2xvcjEzKSxzdW5zZXQpXG5zdHJva2VXaWR0aDogMFxuXG4iLCJmIjp7ImxuZyI6LTQ4Ljg2NDM1NTA4Mjc4MzUwNCwibGF0IjotMjYuNDAxNjE4ODM4NDExOTU2fSwiZyI6Mi43NjQ5NTY4MTI0MDM2MTc1LCJoIjoiRGFya01hdHRlciJ9

### Manual Classification (buckets)

`color: ramp(buckets($pct_obm,[10,20,30,40,50]),reverse(emrld))`

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiZXNjaGJhY2hlcl9lbGVjdGlvbl9yZXN1bHRzXzIwMTJfd2l0aF9wb3BfY29weSIsImIiOiIiLCJjIjoibWFtYXRhYWtlbGxhIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJjb2xvcjogcmFtcChidWNrZXRzKCRwY3Rfb2JtLFsxMCwyMCwzMCw0MCw1MF0pLHJldmVyc2UoZW1ybGQpKVxuXG5zdHJva2VDb2xvcjogcmdiYSgyNTUsMjU1LDI1NSwwLjQpXG5zdHJva2VXaWR0aDogMC41XG5cblxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTkzLjMwNDI3ODM1NzQyMjYyLCJsYXQiOjM1Ljk2NzIxOTc3OTg2NjI4NH0sImciOjMuNjM3NDgyNTUzNTM2NTk1LCJoIjoiRGFya01hdHRlciJ9

#### Case 1

* [x] Passed 

A user defines >=2 or <= 7 custom ranges for each bucket with a CARTOColor sequential scheme. In this case, we WILL NOT interpolate because there are enough colors in the scheme.

**Example**
`color: ramp(buckets($mapcolor13,[1,3,5,8]),sunset)`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoYnVja2V0cygkbWFwY29sb3IxMyxbMSwzLDUsOF0pLHN1bnNldClcbnN0cm9rZVdpZHRoOiAwXG5cbiIsImYiOnsibG5nIjotNDguODY0MzU1MDgyNzgzNTA0LCJsYXQiOi0yNi40MDE2MTg4Mzg0MTE5NTZ9LCJnIjoyLjc2NDk1NjgxMjQwMzYxNzUsImgiOiJEYXJrTWF0dGVyIn0=

**Comment by elenatorro** [comment]
It would be better to test the cases from `519-bucket-color-by-category`, because I am going to create a new branch from this one for these cases. Thanks ✨

**Comment by makella** [comment]
Ok! let me know when the branch is stable... I see that you have some issues in the VL Slack channel

**Comment by elenatorro** [comment]
It is ready :) There are integration tests that are failing, but this is expected since those tests are the ones we are going to fix in this issue 👍

**Comment by makella** [comment]
ok!

**Comment by makella** [comment]
Hi @elenatorro!

I _think_ I covered most cases! Please take a look through and let me know if you see something missing. 

There are definitely cases that we need to talk about. I will schedule our meeting for Thursday (tomorrow is a US holiday).

To make sure I was covering all cases, I organized in the following way:

- Numeric and Custom Colors
  - Classified
  - Interpolation
  - Manual Classification

- Numeric and CARTOColors
  - Classified
  - Interpolation
  - Manual Classification

# Numeric and Custom Colors

## Classified

### Case 1
When there are less colors than class breaks. In this case, we WILL interpolate.

#### Example
`color: ramp(globalQuantiles($mapcolor13,5),[yellow,turquoise])`

#### Passed?
- [x] Yes
- [ ] No
- [ ] Unsure

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRtYXBjb2xvcjEzLDUpLFt5ZWxsb3csdHVycXVvaXNlXSlcbnN0cm9rZVdpZHRoOiAwXG5cbiIsImYiOnsibG5nIjotNDguODY0MzU1MDgyNzgzNTA0LCJsYXQiOi0yNi40MDE2MTg4Mzg0MTE5NTZ9LCJnIjoyLjc2NDk1NjgxMjQwMzYxNzUsImgiOiJEYXJrTWF0dGVyIn0=

### Case 2
When there are an equal number of classes and colors. In this case, we will NOT interpolate since there are enough colors for each class break.

#### Example
_Bad color scheme!! Haha, but just for testing_

`color: ramp(globalQuantiles($mapcolor13,5),[blue,turquoise,deeppink,orange,yellow])`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRtYXBjb2xvcjEzLDUpLFtibHVlLHR1cnF1b2lzZSxkZWVwcGluayxvcmFuZ2UseWVsbG93XSlcbnN0cm9rZVdpZHRoOiAwXG5cbiIsImYiOnsibG5nIjotNDguODY0MzU1MDgyNzgzNTA0LCJsYXQiOi0yNi40MDE2MTg4Mzg0MTE5NTZ9LCJnIjoyLjc2NDk1NjgxMjQwMzYxNzUsImgiOiJEYXJrTWF0dGVyIn0=

#### Passed?
- [x] Yes
- [ ] No
- [ ] Unsure

### Case 3
When there are more colors than classes. In this case, we WILL interpolate. The first class will get the first color `purple` and the last class `yellow` all in-between class breaks will be interpolated between those.

This is different than what we are doing with categories. The reason we should interpolate in this case is because it is numeric data with classification. So a user may define a start and an end color to the scheme and then define additional colors in between to interpolate through.

#### Example
`color: ramp(globalQuantiles($mapcolor13,5),[purple,blue,turquoise,deeppink,orange,yellow])`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRtYXBjb2xvcjEzLDUpLFtwdXJwbGUsYmx1ZSx0dXJxdW9pc2UsZGVlcHBpbmssb3JhbmdlLHllbGxvd10pXG5zdHJva2VXaWR0aDogMFxuXG4iLCJmIjp7ImxuZyI6LTQ4Ljg2NDM1NTA4Mjc4MzUwNCwibGF0IjotMjYuNDAxNjE4ODM4NDExOTU2fSwiZyI6Mi43NjQ5NTY4MTI0MDM2MTc1LCJoIjoiRGFya01hdHRlciJ9

#### Passed?
- [ ] Yes
- [x] No
- [ ] Unsure

## Interpolation

### Case 1
Linear interpolation across any attribute with >2 colors defined. In this case, we WILL interpolate.

#### Example
`color: ramp(linear($mapcolor13),[yellow,turquoise])`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAobGluZWFyKCRtYXBjb2xvcjEzKSxbeWVsbG93LHR1cnF1b2lzZV0pXG5zdHJva2VXaWR0aDogMFxuXG4iLCJmIjp7ImxuZyI6LTQ4Ljg2NDM1NTA4Mjc4MzUwNCwibGF0IjotMjYuNDAxNjE4ODM4NDExOTU2fSwiZyI6Mi43NjQ5NTY4MTI0MDM2MTc1LCJoIjoiRGFya01hdHRlciJ9

OR
`color: ramp(linear($mapcolor13),[orange,yellow,green,turquoise])`
`color: ramp(linear($mapcolor13),[red,orange,yellow,green,turquoise,purple])`

etc...

#### Passed?
- [x] Yes
- [ ] No
- [ ] Unsure

## Manual Class Breaks (buckets)

_@elenatoro we should walk through all possibilities here for both CARTOColor sequential and custom colors_

### Case 1
A user defines custom buckets and custom colors. In this case we WILL interpolate.

#### Example
`color: ramp(buckets($mapcolor13,[1,5,8]),[red,orange,yellow,white])`

# Numeric, CARTOColors

## Classification

### Case 1
`color: ramp(globalQuantiles($attribute,7),purpor)`
Any time a user uses a CARTOColor scheme between **2-7** class breaks, we WILL NOT interpolate.

#### Example
For example, these colors shouldn't be interpolated. Instead, we should use the 3-color `sunset` version
http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRudW1iZXIsMyksc3Vuc2V0KVxuc3Ryb2tlV2lkdGg6IDBcblxuIiwiZiI6eyJsbmciOi00NS4zMDkwNDExNjQ1NzAwOSwibGF0IjotMjguMjY0NzAzMzI2NzYyNzc4fSwiZyI6Mi4xODUyNjE3NjQzMjEyOTA0LCJoIjoiRGFya01hdHRlciJ9

#### Passed?
- [ ] Yes
- [x] No
- [ ] Unsure

### Case 2
If a user has more class breaks (10) than maximum available colors in a sequential scheme (7), then we WILL interpolate.

#### Example

`color: ramp(globalQuantiles($number,13),sunset)`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRudW1iZXIsMTMpLHN1bnNldClcbnN0cm9rZVdpZHRoOiAwXG5cbiIsImYiOnsibG5nIjotNDUuMzA5MDQxMTY0NTcwMDksImxhdCI6LTI4LjI2NDcwMzMyNjc2Mjc3OH0sImciOjIuMTg1MjYxNzY0MzIxMjkwNCwiaCI6IkRhcmtNYXR0ZXIifQ==

#### Passed?
- [x] Yes
- [ ] No
- [ ] Unsure

## Interpolation

### Case 1

**Need to discuss**
`color: ramp($mapcolor13,sunset)`
http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoJG1hcGNvbG9yMTMsc3Vuc2V0KVxuc3Ryb2tlV2lkdGg6IDBcblxuIiwiZiI6eyJsbmciOi00OC44NjQzNTUwODI3ODM1MDQsImxhdCI6LTI2LjQwMTYxODgzODQxMTk1Nn0sImciOjIuNzY0OTU2ODEyNDAzNjE3NSwiaCI6IkRhcmtNYXR0ZXIifQ==

#### Passed?
- [ ] Yes
- [x] No
- [x] Unsure


### Case 2
Linear interpolation with a CARTOColor scheme. In this case, we WILL interpolate the color scheme to account for all of the output values.

#### Example
`color: ramp(linear($mapcolor13),sunset)`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAobGluZWFyKCRtYXBjb2xvcjEzKSxzdW5zZXQpXG5zdHJva2VXaWR0aDogMFxuXG4iLCJmIjp7ImxuZyI6LTQ4Ljg2NDM1NTA4Mjc4MzUwNCwibGF0IjotMjYuNDAxNjE4ODM4NDExOTU2fSwiZyI6Mi43NjQ5NTY4MTI0MDM2MTc1LCJoIjoiRGFya01hdHRlciJ9

#### Passed?
- [x] Yes
- [ ] No
- [ ] Unsure

## Manual Classification (buckets)

**_Let's discuss this in more detail as well_**

From master, I think this is working, but not in the current branch:
`color: ramp(buckets($pct_obm,[10,20,30,40,50]),reverse(emrld))`
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiZXNjaGJhY2hlcl9lbGVjdGlvbl9yZXN1bHRzXzIwMTJfd2l0aF9wb3BfY29weSIsImIiOiIiLCJjIjoibWFtYXRhYWtlbGxhIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJjb2xvcjogcmFtcChidWNrZXRzKCRwY3Rfb2JtLFsxMCwyMCwzMCw0MCw1MF0pLHJldmVyc2UoZW1ybGQpKVxuXG5zdHJva2VDb2xvcjogcmdiYSgyNTUsMjU1LDI1NSwwLjQpXG5zdHJva2VXaWR0aDogMC41XG5cblxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTkzLjMwNDI3ODM1NzQyMjYyLCJsYXQiOjM1Ljk2NzIxOTc3OTg2NjI4NH0sImciOjMuNjM3NDgyNTUzNTM2NTk1LCJoIjoiRGFya01hdHRlciJ9


### Case 1
A user defines >=2 or <= 7 custom ranges for each bucket with a CARTOColor sequential scheme. In this case, we WILL NOT interpolate because there are enough colors in the scheme.

#### Example

`color: ramp(buckets($mapcolor13,[1,3,5,8]),sunset)`

http://127.0.0.1:8080/examples/editor/index.html#eyJhIjoibmVfNTBtX2FkbWluXzBfY291bnRyaWVzX2xha2VzX2NvcHkiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiY29sb3I6IHJhbXAoYnVja2V0cygkbWFwY29sb3IxMyxbMSwzLDUsOF0pLHN1bnNldClcbnN0cm9rZVdpZHRoOiAwXG5cbiIsImYiOnsibG5nIjotNDguODY0MzU1MDgyNzgzNTA0LCJsYXQiOi0yNi40MDE2MTg4Mzg0MTE5NTZ9LCJnIjoyLjc2NDk1NjgxMjQwMzYxNzUsImgiOiJEYXJrTWF0dGVyIn0=

#### Passed?
- [ ] Yes
- [x] No
- [ ] Unsure

**Comment by davidmanzanares** [comment]
Amazing summary @makella!

One small detail:
> Linear interpolation across any attribute with >2 colors defined. In this case, we WILL interpolate.

You meant `>=2` right?

**Comment by makella** [comment]
Yes! `>=2` :)

**Comment by elenatorro** [comment]
Hi, @makella :) 

I updated this PR with some fixes (they need to be reviewed just in case)

1. Regarding **Interpolation** cases, following up what we talked and also after asking @davidmanzanares, now:
    * `color: ramp($mapcolor13, sunset)` is equivalent to `color: ramp(linear($mapcolor13),sunset)`.

2. **Classification**
    * broken cases: fixed
3. **Manual Classification:**
    * broken `reverse` ramps: fixed.
    * **We need to define the different cases here.**

**Comment by makella** [comment]
@elenatorro just wanna check to see, this is complete?

**Comment by elenatorro** [comment]
This one is complete except the `Manual Classification`, which we are discussing in another issue. Is it correct?
