### ISSUE TITLE
Support variables in viewportFeatures

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/carto-vl#647]
Currently all arguments to `viewportFeatures` can only be properties ($xxx). Variables that reference properties should also be supported.

We could also support cluster aggregations as arguments, as commented [here](https://github.com/CartoDB/carto-vl/pull/625#issuecomment-402045227).

**Comment by elenatorro** [comment]
Should this be closed in favor of https://github.com/CartoDB/carto-vl/issues/469? Or does it add anything different?

**Comment by jgoizueta** [comment]
Some changes are needed in viewportFeatures to make sure that the variable is resolved before using it. 
Also, we need to apply `valueOf()` before checking expressions that can be variables with `instanceof`, but that's something for another ticket because it affects a lot of cases.
