### ISSUE TITLE
Apply standard file naming

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/carto-vl#649]
- `PascalCase`: Files that exports something instantiable: `Layer.js`, `Viz.js`
- `camelCase`: Files that exports something that can be used directly: `util.js`, `geometry.js`

- Update developers.md with those rules

**Comment by rochoa** [comment]
Is this consistent with the rest of the frontend stuff?

cc @ivanmalagon

**Comment by ivanmalagon** [comment]
No. In other projects (Builder and CARTO.js) we use kebab case: `layer.js`, `viz.js`, `geometry-helpers.js`, `histogram-dataview-model.js`.

We don't have any clue in the file naming about the chance of instantiability of the content. Is that a new trend because of ES modules?

**Comment by Jesus89** [comment]
What is the status of this ticket?

**Comment by elenatorro** [comment]
Good question @Jesus89. We discussed that the best way to approach this change is to do it little by little in our daily changes. So each time we change a file that does not follow the convention, we should change it, ideally in a separated commit. It is hard to keep track of this issue.

**Comment by rochoa** [comment]
With that plan, I'm closing this issue. 💪
