### ISSUE TITLE
Avoid requiring cartodb_id for some operations

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/carto-vl#652]
Windshaft sources always have a `cartodb_id` unique feature identifier, but other sources may not.

Some operations fail without a `cartodb_id`, for example all viewport aggregations (& feature list) which use the cartodb_id to avoid duplicated features (same feature could appear in several dataframes):

https://github.com/CartoDB/renderer-prototype/blob/025f9d267234609f138755391205d4929eabe08d/src/renderer/Renderer.js#L179-L180

Other places where are using it:
* https://github.com/CartoDB/renderer-prototype/blob/025f9d267234609f138755391205d4929eabe08d/src/interactivity/featureVizProperty.js#L35
* https://github.com/CartoDB/renderer-prototype/blob/025f9d267234609f138755391205d4929eabe08d/src/interactivity/featureVizProperty.js#L57-L58

Interestingly, I see GeoJSON is already generating `cartodb_id` automatically, so the only problem now is with MVT sources.

**Comment by jgoizueta** [comment]
This problem is making two features fail with MVT sources:
* viewport aggregations
* interactivity blends & resets

**Comment by jgoizueta** [comment]
I propose:

Allow users to define a PK property in the MVT source metadata. If passed, it will be used for uniqueness checks, etc (we could even renamed/clone it as `cartodb_id`)

If that's is no specified, I wouldn't bother to try to identify duplicated features among tiles (that would be costly and potentially ambiguous). We could either avoid checks when an id is not present or devise a schema to generate unique ids without collisions between tiles.

**Comment by jgoizueta** [comment]
We have notice the code to avoid dup features was innefective, so we have removed it in
that way, MVTs can be used with viewport functions while we fix this properly. So right now, some features can be duplicated in the viewport aggregations and the viewportFeatures list, which is a bug we already had. 
with reference to #590

**Comment by davidmanzanares** [comment]
Fixed by https://github.com/CartoDB/carto-vl/pull/669
