### ISSUE TITLE
Support to render text labels

### ISSUE THREAD

**Issue by jacknkandy** [CartoDB/carto-vl#674]
It seems like there is a big feature missing from the Carto VL library - namely to be able to render labels alongside any geometry. This feature exists within Carto builder as well as the CARTO.js library.

**Comment by VictorVelarde** [comment]
Hi @jacknkandy 

With the new CARTO VL v1.1.0 we have just released, we added a new method to features called `getRenderedCentroid`. That allows creating a dynamic geojson layer, which then can be used to apply the common Mapbox GL labeling capabilities.

We have prepared a few examples in our Dev Center, such as this one: https://carto.com/developers/carto-vl/examples/#example-point-labels
