### ISSUE TITLE
viewPortFeatures() return empty list after applying filters

### ISSUE THREAD

**Issue by Josmorsot** [CartoDB/carto-vl#676]
I'm using **viewPortFeatures** to count the number of elements in the ViewPort. Everything works fine but when I apply any filter and update the bounding box, this function returns an empty list.

I attached an example:
![filters](https://user-images.githubusercontent.com/7818205/42496744-50f646be-8427-11e8-9c52-160abd0a85a5.gif)

**Comment by davidmanzanares** [comment]
Hi @Josmorsot !

Thank you for the report, I'll look into it.

**Comment by davidmanzanares** [comment]
I found a bug regarding blending to variables while trying to debug this. I didn't found other problems, though.

That problem should be fixed in the `fix-var-blending` branch, could you check if that fixes it?

If not, we would need more details or code to help.

**Comment by davidmanzanares** [comment]
Hi, I think we fixed this with https://github.com/CartoDB/carto-vl/pull/688 but it still requires more testing and work.

**Comment by davidmanzanares** [comment]
Hi @Josmorsot , this should be fixed on `master` already.
