### ISSUE TITLE
Interactivity not working fine with Line's Layers

### ISSUE THREAD

**Issue by Josmorsot** [CartoDB/carto-vl#677]
When I have any layer of lines, the map becomes fully clickable. It's looks like the action area is not calculated correctly in some zoom levels. 

I have pushed an example to: https://github.com/Josmorsot/featureClickCartoVL (Carto-VL has been compiled from master)

GIF: 
![popup](https://user-images.githubusercontent.com/7818205/42501412-fe8f2f64-8433-11e8-8430-f9a26b19adcd.gif)

**Comment by davidmanzanares** [comment]
I think this will be fixed by https://github.com/CartoDB/carto-vl/pull/705

**Comment by davidmanzanares** [comment]
The problem was that some of the points of the line segments were repeated and we didn't manage well that case.

**Comment by davidmanzanares** [comment]
Fixed by https://github.com/CartoDB/carto-vl/pull/705
