### ISSUE TITLE
Change 'reverse' expression

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#683]
Currently, `reverse` expression extends from `Palette` class and it only solves the specific case of reversing palettes.

We should use `reverse` as a generic expression, so we can reverse other values than palettes. We should discuss the behaviour depending on the parameters (palette, array, other expression...)

**Comment by makella** [comment]
ahhhh i actually was thinking about this the other day... when you want to display higher values to lower values vs. the traditional low to high.

for example, `ramp(reverse(linear($attribute)),sunset)`

**Comment by elenatorro** [comment]
exactly ✨

**Comment by VictorVelarde** [comment]
Done! 🚀

**Comment by makella** [comment]
NICE!
