### ISSUE TITLE
Image comparison in render tests does not always work

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#686]
When comparing images in render tests, there are some cases where the test pass if the colors are similar but not identical.

**Example:**

Comparing these two images (there is a slightly but important difference between the central point), the test passes.

![reference_out](https://user-images.githubusercontent.com/3824953/42578134-34557890-8526-11e8-9802-10a85a05590d.png)

![reference](https://user-images.githubusercontent.com/3824953/42578136-348e1272-8526-11e8-8f6b-cbfe694b1aa6.png)

**Comment by Jesus89** [comment]
This is related to MacOS color spaces and it there is no other solution than adjust your color space to match the Linux configuration.
