### ISSUE TITLE
Unimplemented geometry type 'ST_Polygon'

### ISSUE THREAD

**Issue by det-jscott116** [CartoDB/carto-vl#695]
When trying to add geometry which is of an 'ST_Polygon' type, the following error is thrown. On inspection, Carto VL only supports the following geometry types:

```javascript
async getGeometryType(query, conf) {
        const columnListQuery = `SELECT ST_GeometryType(the_geom) AS type FROM ${query} WHERE the_geom IS NOT NULL LIMIT 1;`;
        const response = await getSQL(columnListQuery, conf);
        const json = await response.json();
        const type = json.rows[0].type;
        switch (type) {
            case 'ST_MultiPolygon':
                return 'polygon';
            case 'ST_Point':
                return 'point';
            case 'ST_MultiLineString':
                return 'line';
            default:
                throw new Error(`Unimplemented geometry type ''${type}'`);
        }
    }
```

I'm not actually sure what the reasoning for this is considering that a MultiPolygon is just an array of Polygons anyway.

**Comment by elenatorro** [comment]
Hi :) Could you tell us the version you are using? In `master` branch it seems to be fixed:

https://github.com/CartoDB/carto-vl/blob/ad9e1a4fa7cfd547e90e1d04838dc060972c9cf0/src/client/windshaft.js#L392-L405

**Comment by det-jscott116** [comment]
Hi @elenatorro 

My bad, I was having a bad day on Friday, I didn't double check this. I will close this thread.
