### ISSUE TITLE
Mapbox GL Custom WebGL Layers API integration

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#700]
Depending on the status of https://github.com/mapbox/mapbox-gl-js/issues/6456, we should evaluate if we migrate from our current approach.

**Comment by rochoa** [comment]
Yes, let's use 0.48 or master (if needed).

**Comment by davidmanzanares** [comment]
The performance regression has been mostly fixed by the last merge, see https://github.com/mapbox/mapbox-gl-js/pull/7132

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/carto-vl/pull/886
