### ISSUE TITLE
viewPortFeatures returns no data at a certain zoom level

### ISSUE THREAD

**Issue by Josmorsot** [CartoDB/carto-vl#708]
Hi,
I think that this fix: #705, has caused that viewPortFeatures return 0 features at a certain zoom level

![image](https://user-images.githubusercontent.com/7818205/42732263-7bf1d7c0-881e-11e8-8ecc-0476655cef49.png)

![image](https://user-images.githubusercontent.com/7818205/42732276-c06020e2-881e-11e8-87d8-53de0624fe87.png)

Could you please have a look?
Thanks!

**Comment by davidmanzanares** [comment]
Hi,

I couldn't reproduce the problem with the code provided on https://github.com/CartoDB/carto-vl/issues/677 Could you give me more details or, preferably, some code to test this?

**Comment by Josmorsot** [comment]
Hi @davidmanzanares,
I've tried to reproduce #677 too and I couldn't. I have reviewed my source code and I've just found a bug that was causing the problem, so I'm going to close this issue
Thanks!

**Comment by davidmanzanares** [comment]
You're welcome!
