### ISSUE TITLE
Carto-VL does not work as expected when imported as a NPM package

### ISSUE THREAD

**Issue by det-jscott116** [CartoDB/carto-vl#710]
I have run into a strange issue when using the Carto VL library as an NPM package. When trying to add multiple layers to a mapbox map, I have the issue that if there is a delay in adding multiple layers, the subsequent layers are never fetched (by inspecting the network tab) or rendered. The ``layer.on('loaded')`` callback also never fires for any of these subsequent layers.

I have created a quick and dirty CodeSandbox to demonstrate this issue accessible at https://codesandbox.io/s/rj2om7nw14.

**Scenario 1**
1. Click the "Add Layer 1" button. The first layer will be added and appear as pink dots on the map. An alert window will show to confirm that the ``on('loaded')`` callback is fired.
2. Click the "Add Layer 2" button. The second layer will NOT load. The ``on('loaded')`` callback does not fire. The network tab shows that an OPTIONS request is made to Carto, followed by a POST request to get the number of features. However it can be seen that none of the initial vector tiles are being fetched (which appears to be the case when a layer is added). 

**Scenario 2**
1. Click the "Add Layer 2" button. This layer will be added and appear as purple polygons on the map. As before, an alert window will open to indicate the ``on('loaded')`` callback has been fired.
2. Click the "Add Layer 1" button. As with scenario 2, this layer will not be added to the map and nor will the on load callback fire.

**Scenario 3**
1. Click the "Add Both Layers" button. Both layers should be added to the map. Two alerts should appear in sequence to confirm both of the ``on('loaded')`` callbacks have been fired.

So to me this seems like race condition/timing issue - perhaps a promise is failing to resolve, not sure.

If I swap out using the NPM package with using the pre-built library available via the CDN (e.g. https://libs.cartocdn.com/carto-vl/v0.5.1/carto-vl.min.js) this issue does not occur. Also pointing out I have double checked the version I am using via NPM and its the same version 0.5.1.

I'm not sure what could be different between the two, but could this please be investigated.

Thanks.

**Comment by elenatorro** [comment]
Hi @det-jscott116, this should be fixed now in master branch :) I am closing the issue, if there is any other problem please open a new one. Thank you very much.

**Comment by det-jscott116** [comment]
@elenatorro Awesome work! So impressed with the super fast turn around 👍
