### ISSUE TITLE
Method to interpolate svg style from color to no color?

### ISSUE THREAD

**Issue by ztephm** [CartoDB/carto-vl#718]
cc @makella

### Context

I have an SVG icon that contains multiple colors:

https://s3.amazonaws.com/com.cartodb.users-assets.production/production/stephaniemongon/assets/20180716152627434069.svg

I am using it for a point marker. I want to apply a single color to the svg at low zoom levels, but at high zoom levels I just want the original svg to show without any color applied.

So far I am not able to do this in one style code line, how can we do this?

### Steps to Reproduce

So far I have tried these + symbol property:

1. `color: blend(#93c6ff, rgba(147,198,255,0), linear(zoom(), 2^5, 2^8))`

2. `color: blend(#93c6ff, null, linear(zoom(), 2^5, 2^8))`

Here's my test source code: [index.zip](https://github.com/CartoDB/carto-vl/files/2199064/index.zip)

### Current Result

1. For RGBA param marker disappears at high zoom levels:
![zoom](https://user-images.githubusercontent.com/1779444/42779082-5198474e-890d-11e8-9932-02e777ecbc2f.gif)

2. For null param there's an error:

![screen shot 2018-07-16 at 3 33 07 pm](https://user-images.githubusercontent.com/1779444/42779188-a4b5c690-890d-11e8-9999-9095b96748fa.png)

![screen shot 2018-07-16 at 3 33 26 pm](https://user-images.githubusercontent.com/1779444/42779205-b26fcfa6-890d-11e8-8da3-461d2aad8306.png)

### Expected result

How it should look at low zoom levels:

![screen shot 2018-07-16 at 3 26 51 pm](https://user-images.githubusercontent.com/1779444/42778917-b1073646-890c-11e8-98ab-53027db865e7.png)

How it should look at high zoom levels:

![screen shot 2018-07-16 at 3 19 26 pm](https://user-images.githubusercontent.com/1779444/42778606-adedcd68-890b-11e8-9cc0-5dcd0ab2a9aa.png)

### Browser and version

Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by davidmanzanares** [comment]
Sorry for the late response. This is easy to implement since the main problem is that images are not treated like colors in the type checks.

**Comment by davidmanzanares** [comment]
#920 added supported for this

Example:
```
symbol: blend(@logo, @logo2, linear(zoom(), 5, 6))
@logo:  image('https://s3.amazonaws.com/com.cartodb.users-assets.production/production/stephaniemongon/assets/20180716152627434069.svg')
@logo2: image('https://libs.cartocdn.com/carto-vl/assets/NASA_logo.svg')
```

Keep in mind that the PR has been merged to `master`, but a proper release hasn't been done yet.

**Comment by ztephm** [comment]
Great thank you!
