### ISSUE TITLE
Need to check width ramping with classifiers, numbers, and buckets

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#730]
We need to check ramps for other properties like `width`

For example, 

This works:
`width: ramp(linear($casualty,0,5), [1,24])`

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiY29sbGlzaW9uczE2MDEiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IHJhbXAobGluZWFyKCRjYXN1YWx0eSwwLDUpLCBbMSwyNF0pIiwiZiI6eyJsbmciOi03My45NzI2ODc3OTc0NjM1LCJsYXQiOjQwLjc1MDU1NjExMDEwNDc1fSwiZyI6MTEuODk5MDc3MzE0NTM4NzIyLCJoIjoiUG9zaXRyb24ifQ==

But this doesn't:
`width: ramp(globalQuantiles($casualty,5), [1,24])`

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiY29sbGlzaW9uczE2MDEiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRjYXN1YWx0eSw1KSwgWzEsMjRdKSIsImYiOnsibG5nIjotNzMuOTcyNjg3Nzk3NDYzNSwibGF0Ijo0MC43NTA1NTYxMTAxMDQ3NX0sImciOjExLjg5OTA3NzMxNDUzODcyMiwiaCI6IlBvc2l0cm9uIn0=

What we would expect in the `globalQuantiles` example is similar to what happens in Builder where the first class break is assigned the first value `1` and the last class the last value `24` and we calculate the in-betweens.

cc @davidmanzanares

**Comment by makella** [comment]
@elenatorro let's discuss this when you have a chance!

**Comment by makella** [comment]
another example we'll need to look at:

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibmVfMTBtX3BvcHVsYXRlZF9wbGFjZXNfc2ltcGxlIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogcmFtcChidWNrZXRzKCRmZWF0dXJlY2xhLCBbXCJBZG1pbi0wIGNhcGl0YWxcIixcIkFkbWluLTEgY2FwaXRhbFwiLFwiUG9wdWxhdGVkIHBsYWNlXCJdKSxbMjAsMTAsM10pXG5jb2xvcjogcmFtcChidWNrZXRzKCRmZWF0dXJlY2xhLCBbXCJBZG1pbi0wIGNhcGl0YWxcIixcIkFkbWluLTEgY2FwaXRhbFwiLFwiUG9wdWxhdGVkIHBsYWNlXCJdKSxbcmVkLHR1cnF1b2lzZSxsaW1lZ3JlZW5dKVxuc3Ryb2tlQ29sb3I6IGJsYWNrIiwiZiI6eyJsbmciOi05LjM2NjI2ODI5NTkwMjk1NSwibGF0IjozMC42MDM5MDY0MTgxNzE2NDd9LCJnIjoyLjMzMzc0MzI3MzYzNjk3NDUsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==

In order for each category bucket to get the assigned symbol size, we have to add the `0`:

`width: ramp(buckets($featurecla, ["Admin-0 capital","Admin-1 capital","Populated place"]),[20,10,3,0])`

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibmVfMTBtX3BvcHVsYXRlZF9wbGFjZXNfc2ltcGxlIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogcmFtcChidWNrZXRzKCRmZWF0dXJlY2xhLCBbXCJBZG1pbi0wIGNhcGl0YWxcIixcIkFkbWluLTEgY2FwaXRhbFwiLFwiUG9wdWxhdGVkIHBsYWNlXCJdKSxbMjAsMTAsMywwXSlcbmNvbG9yOiByYW1wKGJ1Y2tldHMoJGZlYXR1cmVjbGEsIFtcIkFkbWluLTAgY2FwaXRhbFwiLFwiQWRtaW4tMSBjYXBpdGFsXCIsXCJQb3B1bGF0ZWQgcGxhY2VcIl0pLFtyZWQsdHVycXVvaXNlLGxpbWVncmVlbl0pXG5zdHJva2VDb2xvcjogYmxhY2siLCJmIjp7ImxuZyI6LTkuMzY2MjY4Mjk1OTAyOTU1LCJsYXQiOjMwLjYwMzkwNjQxODE3MTY0N30sImciOjIuMzMzNzQzMjczNjM2OTc0NSwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoiZGF0YXNldCJ9

Really, we'd want that to be like:

`width: ramp(buckets($featurecla, ["Admin-0 capital","Admin-1 capital","Populated place"]),[20,10,5])`

**Comment by davidmanzanares** [comment]
This `width: ramp(globalQuantiles($casualty,5), [1,24])` is clearly a bug, actually I think it's a regression.

But the need to add the `0` in `width: ramp(buckets($featurecla, ["Admin-0 capital","Admin-1 capital","Populated place"]),[20,10,3,0])` is expected. Without the `0` we go back to an old problem if the dataset changes and a new category is present, what should we do then? We don't have a number specified by the user, we could do interpolation, but that is probably what the user doesn't want and it will be highly implicit, we could choose to not render them, but that would be very dangerous IMO.

**Comment by makella** [comment]
After discussion we came to the following decision for `width` on a category attribute that uses buckets for symbol size.

Examples:

In this case, these two buckets will be assigned the defined symbol width (`20,10`) and all other features will default to VL's defualt marker size of `7`:
`width: ramp(buckets($featurecla, ["Admin-0 capital","Admin-1 capital"]),[20,10])`

To override, the default, a user can add an additional marker size. Where VL's default marker size will be overwritten with that value. In this case, that would be `2`.
`width: ramp(buckets($featurecla, ["Admin-0 capital","Admin-1 capital"]),[20,10,2])`


https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibmVfMTBtX3BvcHVsYXRlZF9wbGFjZXNfc2ltcGxlIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogcmFtcChidWNrZXRzKCRmZWF0dXJlY2xhLCBbXCJBZG1pbi0wIGNhcGl0YWxcIixcIkFkbWluLTEgY2FwaXRhbFwiXSksWzIwLDEwLDJdKVxuY29sb3I6IHJhbXAoYnVja2V0cygkZmVhdHVyZWNsYSwgW1wiQWRtaW4tMCBjYXBpdGFsXCIsXCJBZG1pbi0xIGNhcGl0YWxcIixcIlBvcHVsYXRlZCBwbGFjZVwiXSksW3JlZCx0dXJxdW9pc2UsbGltZWdyZWVuXSlcblxuXG4vL2ZpbHRlcjogSU4oJGZlYXR1cmVjbGEsW1wiQWRtaW4tMCBjYXBpdGFsXCIsXCJBZG1pbi0xIGNhcGl0YWxcIl0pICIsImYiOnsibG5nIjotNzcuNTQwNDk5MDQxODU3NTIsImxhdCI6NDguMTUwMzIxNjAwNDkwOTR9LCJnIjoyLjg1OTI1MDYxNTg1MDU2OTUsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==

**Comment by makella** [comment]
ok, closing checked through the scenarios.
