### ISSUE TITLE
Proposal for zoomRange to drive multi-scale property interpolation 

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#733]
@davidmanzanares and I were discussing multi-scale symbology and how to make it easier for the user.

After going through a variety of options, we have a proposal for an expression `zoomRange`.

If we can make it a separate expression, we will have more control over how it behaves. Right now, when a user wants to do multi-scale styling, it requires a series of `blends` and `linear` interpolation.

In addition, `linear` only accepts 2 arguments. So if you want to add more than 2 "stops", you have to nest a series of `blend`s

For example if someone wants to have marker width "stops" where a symbol size is defined for particular zoom levels and the non-defined zoom levels interpolated between them, they would have to do the following:

```
width: blend(2,
             blend(8, 12, linear(zoom(), 2^14, 2^16))
             linear(zoom(),2^10,2^14)
)
```
With this proposal, the above would become:

`width: ramp(zoomRange(10,14,16), [2,8,12])`

Where at zooms <= z10 the symbol size would be 2, at z14 8, and at >=z16, 12 and the in-betweens (z11 - z13 and z15 would be interpolated).

We could also apply the same logic to other styling properties like `color`:

`color: ramp(zoomRange(7,10,14),[red,orange,yellow]))`

**Comment by davidmanzanares** [comment]
:heart: 

Another possible feature is the combination of ramps (nesting):
```
ramp(linear($population, 1,10000),
          ramp(zoomRange(10,14,16),
                   [1, 10],
                   [2, 20],
                    [4,40]                    
           )
)  

```

**Comment by makella** [comment]
YES!

**Comment by davidmanzanares** [comment]
This was added by #860
