### ISSUE TITLE
Line Rendering

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#738]
## Related to

- https://github.com/CartoDB/carto-vl/issues/185
- https://github.com/CartoDB/carto-vl/issues/400
- https://github.com/CartoDB/carto-vl/issues/506

## Introduction

The current implementation of line rendering has some issues related to huge lines for specific cases. Also, stroke rendering for polygons is very basic. The goal is to provide better solutions for both line and stroke rendering.

Since we will change both decoder and renderer we can take a look at common parameters to be all aligned and also evaluate adding them to the style properties.

- [x] Line: https://github.com/CartoDB/carto-vl/pull/219
- [x] Polygon stroke: https://github.com/CartoDB/carto-vl/pull/791
- [x] StokeJoin: https://github.com/CartoDB/carto-vl/issues/794
- [x] StrokeCap: https://github.com/CartoDB/carto-vl/issues/795

#### Miter

It generates sharp corners by extending the outer edges of the stroke at the tangents of the path segments until they intersect. This is the default join type.

![selection_206](https://user-images.githubusercontent.com/2227572/42938441-921dc978-8b52-11e8-9bf9-ff5af103024c.png)

If the angle of the corner is very small it could produce huge sharp corners (going to infinity for the limit case of 0 degrees).

![selection_209](https://user-images.githubusercontent.com/2227572/42938459-9cbdc7e8-8b52-11e8-9140-2bf336b35298.png)

To avoid that, the `miter-limit` is defined, which is the maximum length of the miter (in units of stroke width). If the miter-limit is exceeded, the line join falls back to bevel.

#### Bevel

It generates bevelled corners by connecting both lines extended with normal vectors of each line.

![selection_208](https://user-images.githubusercontent.com/2227572/42938499-ce3491f8-8b52-11e8-9032-359b2c6a71c8.png)

![selection_210](https://user-images.githubusercontent.com/2227572/42938515-d57873d0-8b52-11e8-9581-23ba633950f6.png)

#### Round

It generates "round" corners by adding triangles in the intersection. The number of the triangles depends on the angle.

![selection_207](https://user-images.githubusercontent.com/2227572/42938543-ef219492-8b52-11e8-93f1-17ce702f055a.png)

#### Butt

The line does not extend beyond the endpoint.

![selection_213](https://user-images.githubusercontent.com/2227572/42938578-097ac7e6-8b53-11e8-8088-d73679830e7c.png)

#### Square

The line extends beyond the endpoint by a rectangle with a width equal to half the width of the stroke and a height equal to the width of the stroke.

![selection_214](https://user-images.githubusercontent.com/2227572/42938586-0f74ce80-8b53-11e8-87d7-62cfd7a9f880.png)

#### Round

The line extends beyond the endpoint by a half circle with a diameter equal to the stroke width. 

![selection_215](https://user-images.githubusercontent.com/2227572/42938594-14e4070a-8b53-11e8-8587-8734151a405f.png)

## Implementation

Regarding joins, I think we should implement miter with proper default miter-limit and bevel. Round is nice to have and maybe it is a good moment to add it. The style property should be something like `line-join`, `stroke-join`, `join`, `join-type`. Since `width` is shared between lines and strokes for polygons we should share the new property too.

Regarding endpoints, I think it has less priority but it is also a nice to have feature.

## Known issues

The current implementation only supports miter joins without `miter-limit`. The following animation (`width: (now() % 9) * 10`) shows that the join grows with the width and also a new big triangle appears in order to preserve the miter length.

![line-width](https://user-images.githubusercontent.com/2227572/42938645-3d837c86-8b53-11e8-95ab-5c24266abed6.gif)

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [ 10, 20 ],
          [ -10, 15 ],
          [ 10, 10 ]
        ]
      }
    }
  ]
}
```

## Tests

We should add more render tests based to cover line rendering features.

| GeoJSON | Render* |
|---|---|
| [ 10, 20 ], [ -10, 15 ], [ 10, 10 ] | ![selection_216](https://user-images.githubusercontent.com/2227572/42938604-1bf08eba-8b53-11e8-83ee-a1f43d6797ee.png) |
|  [ -10, 20 ], [ -10, 10 ],  [ 10, 10 ], [ 10, 20 ] | ![selection_217](https://user-images.githubusercontent.com/2227572/42938612-1f02cd48-8b53-11e8-9128-b7cde69fd645.png) |

**Comment by makella** [comment]
@Jesus89 

> Round is nice to have but maybe it is a good moment to add it.

Do you mean that we won't add round, or will? I think round joins are super useful but are they hard to implement technically?

In addition to line joins, are we considering anything for line caps?

Since this is for lines and polygon _stroke_, I think we should use `strokeJoin` since `strokeWidth` is associated with polygon outlines.

**Comment by Jesus89** [comment]
Sorry,  @makella , better
> Round is nice to have and maybe it is a good moment to add it.

So, yes. I think we can add it for the public release. Since we are going to work on that we can take a look also at line caps.

OK. We can use `strokeJoin` now.

**Comment by makella** [comment]
and what about line caps?

**Comment by Jesus89** [comment]
Hi @makella. I think we can use `strokeCap` for the caps that I mentioned in the description.

**Comment by makella** [comment]
ohhh sorry! missed that heading! ok, great! 

Let me know if I can help with any testing, etc.

**Comment by Jesus89** [comment]
Hi, I have implemented strokeJoin and strokeCap. I have a question about naming.

Since we are sharing properties for different geometries we have some issues regarding these properties:
- strokeCap is applicable only in lines (no polygons) so maybe `lineCap` is a better name for that.
- strokeJoin is applicable to both lines and polygon stroke. It is natural to use this in strokes, but is not nice for lines.

My proposal, as always, is to be explicit to make things easier for the user:

For lines:
```js
const s = carto.expressions;
const viz = new carto.Viz({
  width: 10, (lineWidth would be awesome :D)
  lineJoin: s.joins.MITER,
  lineCap: s.caps.SQUARE
});
```

For polygons
```js
const s = carto.expressions;
const viz = new carto.Viz({
  strokeWidth: 10,
  strokeJoin: s.joins.BEVEL,
  strokeCap: s.caps.BUTT
});
```

I have another question regarding namespaces. I am using plural for `carto.expression.joins` and `carto.expressions.caps` as we do for `carto.expression.palettes` for example. However, we are using singular for sources namespace: `carto.sources.GeoJSON`. IMO we should unify this criterion to have consistent namespaces.

**Comment by makella** [comment]
@Jesus89 I'm definitely in agreement with you about being more explicit about geometry types in styling.

I agree that having things like `lineWidth`, `lineJoin`, `lineCap`, etc. would be really helpful and also avoid some of the pitfalls associated with knowing (or rather not knowing) which properties are available for which geometries.

Thinking further down the road, would we then have `markerWidth` for points? Seems like with this pattern that having `width` alone without a geometry-type prefix could also become confusing. And then you start to think about all the other things like `color`... how would we differentiate between a marker stroke and polygon stroke?

>strokeJoin is applicable to both lines and polygon stroke. It is natural to use this in strokes, but is not nice for lines.

I should test this out! In my experience (particularly with segmented lines) `lineJoin` is a common styling property that is used for better, "rendered" connectivity of roads at least in basemap/raster-based design.

**Comment by davidmanzanares** [comment]
Is there some reason to keep this open?

Thx!

**Comment by Jesus89** [comment]
This is not part of the public release, so it could be closed and recovered in the future.
