### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by Josmorsot** [CartoDB/carto-vl#750]
Hi,
I've been researching the cause of the performance issues we currently have in Traffico. At first I thought the root of the problem was that we were using several layers, but after doing some tests I've realised that the problem continues even with a single layer (even with a simple line layer with approx. 30 lines)

I've prepared an example in this [branch](https://github.com/Josmorsot/featureClickCartoVL/tree/ivan/performance-test ) with a single line layer, with an empty VIZ and without interactivity or variables. Performance issues are quite apparent in Chrome (I've tested this example in both MacOS and Windows), but it looks like they are better in Safari (MacOS)

In Chrome I continuously get this warning:
- [Violation] 'requestAnimationFrame' handler took \<N>ms  [worker.js:197]

Whereas I don't get any warnings at all in Safari.

The performance in Chrome also falls for every added layer.

Could you please have a look?

Thanks

CC: @davidmanzanares

**Comment by davidmanzanares** [comment]
Hi,

I couldn't reproduce the issue. I don't get those warnings and the performance is in the 30-60 fps range. In fact, if I disable the basemaps (which are rendered by Mapbox GL) the performance stays at 60fps almost everytime.

Could you provide us with the `.json` profile of the application generated by Chrome?

Could you give us more information about your hardware and software (computer model, OS version and Chrome version)?

Regarding having many layers, we haven't optimized for that use-case, feel free to open a new issue with that, but, of course, the recommendation is to try to reduce the layer count.

**Comment by Josmorsot** [comment]
Hi @davidmanzanares,

Thanks for your response. I'm going to open a separate issue to optimise the multilayer use case.

I have exported two profiles in Chrome, find both attached. Please let me know if you need anything else.
[profiles.zip](https://github.com/CartoDB/carto-vl/files/2223819/profiles.zip)

Thanks!

**Comment by davidmanzanares** [comment]
I've taken a look at the profiles and I don't see many CARTO VL traces. The main hot spot seems to be `Ba.receive` which I think it is a Mapbox GL method unrelated to CARTO VL, the `fetch` function, which is invoked by CARTO VL for each tile which is related to https://github.com/CartoDB/carto-vl/issues/413 and DOM operations which I hope are triggered by some UI.

Feel free to re-open this issue with more information, but I don't apart from #413 I don't think we have many options to improve things in this example.
