### ISSUE TITLE
Zoom using trackpad on Macbook

### ISSUE THREAD

**Issue by rutgerhofste** [CartoDB/carto-vl#751]
I am new to Carto VL so maybe this feature is currently disabled on my maps but I can't use my trackpad to zoom in and out. Normal behavior in similar mapping apps use scroll or pitch fingers to do so. The only way I can currently zoom in is to double click. There is no way to zoom out.

**Comment by elenatorro** [comment]
Hi

When creating the map, the option `scrollZoom` is by default `true`. If you set it to `false`, then the scroll will not be enabled.

```js
    const map = new mapboxgl.Map({
      container: 'map',
      style: 'https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json',
      center: [-105.048, 39.749],
      zoom: 15,
      scrollZoom: false
});
```

If the problem remains, could you please send us an example?

Thanks.

**Comment by rutgerhofste** [comment]
that works. closing this issue
