### ISSUE TITLE
Zoom and Pan not smooth 

### ISSUE THREAD

**Issue by rutgerhofste** [CartoDB/carto-vl#756]
I'm using Carto-VL for the first time and looking for ways to improve the performance of my test app.  When I zoom in and out the performance is not smooth. 

My code can be found [here](https://github.com/rutgerhofste/carto_qa/tree/1d7369124092332d15a04c16d2b3eb2fa5aa5a70) in index.html

I'm combining several elements in Carto VL including SQL Join, Style and tooltip and I am wondering what is causing the slow performance. I'm on a windows machine with 16GB RAM and using Chrome. Chrome is using >1 GB RAM.

**Comment by davidmanzanares** [comment]
Hi @rutgerhofste ,

We have found some of the performance problems on your example and at least some of the optimizations will be available on the next CARTO VL release (version `0.6.0`).

Thank you!

**Comment by rutgerhofste** [comment]
Thank you, 

Looking forward to use Carto VL and CartoFrames.contrib.vector in more of our internal apps for quality assurance.

**Comment by davidmanzanares** [comment]
Hi @rutgerhofste !

We just released CARTO VL version `0.6.0`. It comes with multiple optimizations, and some of them have an important impact on your example. We've tested your example again and we saw meaningful improvements. We still think that some optimizations are possible (https://github.com/CartoDB/carto-vl/issues/771) though.

Thank you for your feedback!

**Comment by rutgerhofste** [comment]
Just updated the version to 0.6.0 and unfortunately I get an error:
https://rutgerhofste.github.io/carto_qa/

[rutgerhofste.github.io-1533225201237.log](https://github.com/CartoDB/carto-vl/files/2254182/rutgerhofste.github.io-1533225201237.log)

**Comment by davidmanzanares** [comment]
Agh, sorry, could you try again with version `0.6.2`?

**Comment by elenatorro** [comment]
Hi @rutgerhofste, is it still happening to you? Thanks!
