### ISSUE TITLE
Add built-in image list to documentation

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#761]
As outlined [here](https://github.com/CartoDB/carto-vl/issues/535#issuecomment-402489433), we have a set of built-in images for use with VL. We refer to this "built-in" set in the guides and examples.

It would be good to have them listed somewhere in the documentation.

Any ideas where a good place would be?

**Comment by elenatorro** [comment]
Maybe we could add it after the [Palettes section](https://carto.com/developers/carto-vl/reference/#cartoexpressionscartoexpressionspalettes) in the reference.

I think we should also include a link to this reference at [Built In Images Guide] (https://carto.com/developers/carto-vl/guides/introduction-to-image-files/#built-in-images)

About showing the icons... I think it would be better to have the icon list in the Guides. Something like:

* <img src="https://user-images.githubusercontent.com/3824953/43185037-00058718-8feb-11e8-8285-0341a427d927.png" data-canonical-src="https://user-images.githubusercontent.com/3824953/43185037-00058718-8feb-11e8-8285-0341a427d927.png" width="20" height="15" />   bicycle

* <img src="https://user-images.githubusercontent.com/3824953/43185236-98b0426e-8feb-11e8-8769-7f9e703dd3d0.png" data-canonical-src="https://user-images.githubusercontent.com/3824953/43185236-98b0426e-8feb-11e8-8769-7f9e703dd3d0.png" width="15" height="25" />   building

* <img src="https://user-images.githubusercontent.com/3824953/43185240-99d67956-8feb-11e8-9dcd-8f0a794f9c34.png" data-canonical-src="https://user-images.githubusercontent.com/3824953/43185240-99d67956-8feb-11e8-9dcd-8f0a794f9c34.png" width="20" height="15" />   car

What do you think?

**Comment by makella** [comment]
I like the idea of having the icons showing! 

Instead of a list, can we do something more like this: https://www.nps.gov/maps/tools/symbol-library/

And when you hover over you see the name?

**Comment by elenatorro** [comment]
Yes, a table looks really nice! 

However, instead of showing the name when overing, I would include the name above or below the icon, so it can be seen at first glance and also it is easier to copy paste. What do you think?

**Comment by makella** [comment]
I think that sounds perfect! Let me know if there is anything I can do to help!!

**Comment by elenatorro** [comment]
Related issue: https://github.com/CartoDB/developers/issues/419

**Comment by elenatorro** [comment]
🚀

**Comment by makella** [comment]
nice work!
