### ISSUE TITLE
`in` String API syntax sugar

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#770]
Allow
`filter: $cat in ['a', 'b', 'c']`

**Comment by davidmanzanares** [comment]
I created this issue since @makella expected similar behavior and I think this is consistent with previous syntax sugar of the String API, but this opens up the issue of syntax sugar for the similar functions: `NIN` and `Between`.

Those 2 are much more problematic:

`filter: $cat nin ['a', 'b', 'c']` Using `nin` seems like a bad name here

`filter: $cat not in ['a', 'b', 'c']` This is difficult to parse with our current parser
`filter: $num between 10 30` This is difficult to parse with our current parser

What do you think?

cc: @rochoa

**Comment by Jesus89** [comment]
I think in this case `filter: $cat nin ['a', 'b', 'c']` has perfect sense, since it has the same sematics than the Function API `filter: nin($cat, ['a', 'b', 'c'])`. So I vote for this option.

As you say, other options are more difficult to parse or not very consistent with our current types. NOTE: I think for `between($num, 10, 30)` the better simple approach is using `10 < $num < 30`.

**Comment by makella** [comment]
Some thoughts:


> Using `nin` seems like a bad name here

Regarding this, are there other options? I realize that we are using logical operators but just throwing out some comparison ones too :)  
    - `notIN`
    - `notin`
    - `<>`
    - `!=`

>`filter: $num between 10 30` This is difficult to parse with our current parser
>`filter: $cat nin ['a', 'b', 'c']`

Is there a reason that numbers and category notation would be different? 

Could we simplify and do something like:

`filter: between($num, [10, 30])` 
  - where we would know in the background that it is values > 10 and < 30?
  - for ranges of numbers, I feel like this is similar to `width: ramp($num,[2,25])`

And for categories:

`filter: notin($cat, ['a','b','c'])`

> the better simple approach is using 10 < $num < 30

Not sure I totally agree that it is a simpler approach!

**Comment by davidmanzanares** [comment]
> Is there a reason that numbers and category notation would be different?

Well, between always takes 2 arguments, therefore, I think it's normal to don't pass a list with "[" and "]". However, `in` takes a list of categories.

**Comment by rochoa** [comment]
Always have in mind that the more different the syntax is between String vs JS APIs, the more difficult is to move between them.

**Comment by makella** [comment]
> Well, between always takes 2 arguments, therefore, I think it's normal to don't pass a list with "[" and "]". However, in takes a list of categories.

Yeah, I see but wouldn't anything more than 1 be considered a list? Also, `width: ramp($num,[2,25])` would not accept a third number, right? So based off of this that should be `width: ramp($num,2,25)`?


> Always have in mind that the more different the syntax is between String vs JS APIs, the more difficult is to move between them.

Please tell me more. What would the JS syntax look like?

**Comment by davidmanzanares** [comment]
As discussed off-channel we decided to add:
`$prop IN ['a', 'b', 'c']`
`$prop NIN ['a', 'b', 'c']`

**Comment by makella** [comment]
and between would look like?

`$prop between 10, 30`?

**Comment by Jesus89** [comment]
Hi @makella.

> $prop between 10, 30

We do not support this type of pseudo-arrays `10, 30` and IMO is it not a very intuitive syntax. I think for this case we should use the following expression, which allows also to include endpoints:

```
10 <= $prop < 30
```
