### ISSUE TITLE
Optimize `decodePolygon`

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#771]
It's one of the hot spots on many apps, sometimes even the main one.

I think that it could be optimized by removing the usage of the temporal `vertices` and `normals` arrays.

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/carto-vl/pull/799.

**Comment by davidmanzanares** [comment]
Please, close the issue when the fix comes to `master`

**Comment by Jesus89** [comment]
Right! Closing now by https://github.com/CartoDB/carto-vl/pull/791
