### ISSUE TITLE
Render resolution bug

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#774]
There is an issue in the render regarding resolution. In the following examples I use [this geojson](https://raw.githubusercontent.com/mapbox/mapbox-gl-js/master/docs/pages/assets/hike.geojson). Blue line is rendered with MGL, red line with VL.

![line-resolution issue](https://user-images.githubusercontent.com/2227572/43309248-8c37776a-9184-11e8-8398-9dcf77c97c2e.gif)

I have uploaded the example in `debug/lines-geojson.html` in [this branch](https://github.com/CartoDB/carto-vl/tree/lines-resolution).

**Comment by davidmanzanares** [comment]
This could be caused by the lack of precision in the GPU (FP32). We should adjust the GeoJSON's dataframe to its geometry bounding box to fix the problem for datasets like this.
