### ISSUE TITLE
Create guide on color by category and color by numbers

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#787]
When we have all of the color by category and color by number logic done, we should have a guide that walks through the scenarios using both CARTOColors and custom color buckets.

**Comment by rochoa** [comment]
This is superseded by https://github.com/CartoDB/carto-vl/issues/973, https://github.com/CartoDB/carto-vl/issues/970, and https://github.com/CartoDB/carto-vl/issues/969.
