### ISSUE TITLE
Polygon stroke not properly clipped

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#793]
### [Example](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibW5tYXBwbHV0byIsImIiOiIiLCJjIjoiZG1hbnphbmFyZXMiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6ImNvbG9yOiByYW1wKGxpbmVhcihsb2coJG51bWZsb29ycyksIDEsIDQpLCBbYmx1ZV0pXG5zdHJva2VDb2xvcjogb3BhY2l0eSh3aGl0ZSwgMC41KVxuc3Ryb2tlV2lkdGg6IDIwIiwiZiI6eyJsbmciOi03My45ODc2NTY4NDA2MzA1LCJsYXQiOjQwLjczMDQ1ODE5NjE5ODN9LCJnIjoxNS4xODc3ODY4NzA5Mjg5LCJoIjoiRGFya01hdHRlciIsImkiOiJkYXRhc2V0In0=)

![selection_243](https://user-images.githubusercontent.com/2227572/43570881-c8d94462-963b-11e8-87c8-591de2b4825b.png)

**Comment by Algunenano** [comment]
Just a heads up: this is normal if the size of the stroke is bigger than the `Buffer size` in the MVT request. Also, unless you want to clip twice, the stroke should be applied before clipping (I don't know if that's being done now).

**Comment by davidmanzanares** [comment]
I think this may need a really high effort (and time) to be fixed, and common width values don't show this artifact.

There are a lot of involved pieces here:
- Backend tiling
- CARTO VL clipping
- CARTO VL line generation
- CARTO VL tile-by-tile rendering

Reducing the number of tiles in common scenarios would fix this in those cases and that would imply many other advantages.

**Comment by rochoa** [comment]
For now, we don't plan on tackling this. I'm closing the issue. Let's review this decision if we find there is more demand for this to be supported.
