### ISSUE TITLE
Fix examples that relied on saturated point size

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#798]
After the point size limitation of 128 pixels was replaced by one with 1024 pixels, many of our examples show enormous sizes.

We should review every example.

Right now there is no easy way to limit the size on purpose, but we could easily add the `min` function to do so if necessary.

cc: @makella

**Comment by makella** [comment]
ahhh, let's talk about this tomorrow!

**Comment by makella** [comment]
after looking at this with @davidmanzanares we realized that on both my monitor and laptop, the `window.devicePixelRatio` is 2 and I was not able to see the saturated point sizes that david is seeing. He is going to make a fix and once that is implemented, I will revisit the examples.

**Comment by davidmanzanares** [comment]
Yes, I created an issue: https://github.com/CartoDB/carto-vl/issues/820

**Comment by davidmanzanares** [comment]
Hey, @makella it seems that the problem wasn't related to your high-dpi screen, it seems related to my desktop PC with Linux and a Nvidia GPU. Therefore, this is not blocked for that.

I don't know the current status of the examples (I know there were some changes with `zoom()`), but, since we plan to change that too, we may want to wait for that. Your call 100% :slightly_smiling_face:

**Comment by makella** [comment]
that makes sense! we can do a bulk update to all the examples.

buuut why am i not seeing the big sizes on the examples, but do on jeff's map? (https://zingbot.github.io/vectoria/locations_explore.html)

>it seems that the problem wasn't related to your high-dpi screen, it seems related to my desktop PC with Linux and a Nvidia GPU. Therefore, this is not blocked for that

does this mean you were artificially seeing large sizes?

**Comment by davidmanzanares** [comment]
I don't know about Jeff map, I took a closer look a while ago and I saw some suspicious application code.

The Nvidia Linux problem is fixed, but maybe we could review the examples once the scale/zoom issue is fixed: https://github.com/CartoDB/carto-vl/issues/690

**Comment by rochoa** [comment]
Is this still blocked?

**Comment by davidmanzanares** [comment]
No, all the proposed changes related to multi-scale cartography has been implemented.

**Comment by makella** [comment]
ok, so this seems now to be part of the overall dev center review. before going too far, should we figure out which examples we want to keep and the ones that we don't?

**Comment by davidmanzanares** [comment]
Sure! There is no point in fixing bad examples!

**Comment by rochoa** [comment]
As we are already doing an effort on the documentation: guides and examples in particular. I'm closing this issue and, if something arises, we should be able to solve it in https://github.com/CartoDB/carto-vl/issues/950 or https://github.com/CartoDB/carto-vl/issues/978.
