### ISSUE TITLE
Test minified build

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#805]
After having problems with the minification configuration (the minification produced invalid code), I think we may add some form of testing at some level.

**Comment by Jesus89** [comment]
Now we are using the non-minified bundle to pass the tests. We could use the minified bundle for the tests or even pass the tests with both bundle files.

**Comment by Jesus89** [comment]
Hi. I have created a PR with this approach: https://github.com/CartoDB/carto-vl/pull/812

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/carto-vl/pull/812
