### ISSUE TITLE
Linux and Nvidia drivers display larger points

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#820]
~High-dpi screens show different result compared to regular screens. With points at least, every geometry should be checked~

The problem can be seen here: https://cartodb.github.io/carto-vl/examples/interactivity/interactive-based-styling.html

**Comment by makella** [comment]
@davidmanzanares even though I couldn't see the large sizes with the maps we were looking at, I can see them on this map:
https://zingbot.github.io/vectoria/locations_explore.html

**Comment by davidmanzanares** [comment]
Fixed by #854
