### ISSUE TITLE
Set default image to circle when using buckets

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#821]
@elenatorro @davidmanzanares 

as we discussed a couple of weeks ago, we need to implement the default image to circle when images are used with buckets in order for all of the data to be displayed.

For example:

`symbol: ramp(buckets($featurecla, ["Admin-0 capital","Admin-1 capital"]),imageList([star,square]))`

All other features would default to the circle marker.

If a user wanted to override the default they could add another image file to the list.

**Comment by elenatorro** [comment]
🚀 in #935
