### ISSUE TITLE
Create example for offset properties

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#822]
Create an example showing how to use `offset: placement()`. Dependant on a couple of outstanding issues:

https://github.com/CartoDB/carto-vl/issues/819
https://github.com/CartoDB/carto-vl/issues/361

**Update**

`offset` property is going to be renamed to `transform`, more info in this issue: https://github.com/CartoDB/carto-vl/issues/934

**Comment by elenatorro** [comment]
Closing in favor of https://github.com/CartoDB/carto-vl/issues/969
