### ISSUE TITLE
Using a variable to define a color ramp does not work

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#839]
Related with https://github.com/CartoDB/carto-vl/issues/555#issuecomment-411888652

## Description

When we define a variable as a color array and pass it to a `ramp` expression, it does not work.

Examples:

```js
    const viz = new carto.Viz(`
        @category_colors: [#FF0066, #0055AA, #99BB99]
        color: ramp(linear($popCount, 0, 200), @category_colors)
    `);
```

```js
    const viz = new carto.Viz(`
        @category_colors: [pink, red, darkRed]
        color: ramp(linear($popCount, 0, 200), @category_colors)
    `);
```

## Expected behaviour

Above examples should work without errors.

**Comment by davidmanzanares** [comment]
Fixed by #917
