### ISSUE TITLE
Layer updated event never stops being launched.

### ISSUE THREAD

**Issue by padawannn** [CartoDB/carto-vl#842]
Has started to happen with the latest code in master
Take any example and add:

`layer.on('updated', ()=> {
      console.log('updated');
    });
`
The updated event never stops being launched.

This is very important for us because we use this event to get the features that are on the screen every time the map changes.

**Comment by elenatorro** [comment]
As we have talked, it has already being solved in https://github.com/CartoDB/carto-vl/pull/836. Thanks for reporting the error! :)
