### ISSUE TITLE
Review variables API

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#849]
In a feature, to access the value of a variable you need to execute `.value`, for example `feature.variables.price.value` at the end of it. This is counter-intuitive and not very nice so IMO we should replace it by:

- Using directly the variable name: `feature.variables.price`
- Using a method for accessing the value: `feature.getVariable('price')`

**Comment by elenatorro** [comment]
What if the variable is an expression that needs to calculate the value? Would it be something like `feature.variables.price({ featName: 'whatever'})` ? (now we use `eval({ ...})`)

I have mixed feelings about this issue, I think it is ok the way it is now, but it is true that we have been asked how to get the variable value. Maybe we need to add more examples and improve the documentation.

**Comment by rochoa** [comment]
I was wondering if somehow we could make `feature.variables.price` to return the `.value` and proxy to other methods when needed, but I don't know how to do that.

I find really useful to define a variable and, later, use the `blendTo` method associated with it. Example:

```js
const viz = new carto.Viz(`
  @maxfloors: 10
  color: ramp(linear($numfloors, 0, 20), temps)
  filter: $numfloors < @maxfloors
`);

// ...

viz.variables.maxfloors.blendTo(50);
```

**Comment by Jesus89** [comment]
Maybe we could use a getter for the variable/property to get a copy of the value, and a setter that uses `blendTo` internally.

```
let mf = viz.variables.maxfloors;
viz.variables.maxfloors = 50;
```

Even

```
viz.variables.maxfloors = '50'; // String API
viz.variables.maxfloors = s.number(50); // JS API
```

We could define the blend duration in other place. Is there any extra method I'm missing?

**Comment by rochoa** [comment]
> We could define the blend duration in other place.

I don't see a good solution for that.

**Comment by rochoa** [comment]
@Jesus89, do you have any solution to the problems presented? Otherwise, I will close this issue as won't fix.

**Comment by Jesus89** [comment]
For me, using getters and setters with the variable would be the best solution. As I said:

```
let mf = viz.variables.maxfloors;  // Runs eval()
viz.variables.maxfloors = 50;      // Runs blendTo(50)
```

I would define a constant value for animations (100, 200, ...) so you don't need to specify it every time. But if you want to change the duration in each set. I would use a function, something like:

```
viz.variables.maxfloors = anim(50, 300);  // Runs blendTo(50, 300)
```

**Comment by rochoa** [comment]
Closing, reasons:
 - That `.eval()` requires a feature. The `.value` is a different thing. Imagine a `ramp` computed based on a property. It won't work in all the cases.
 - Having a global function like `anim` is not aligned with the rest of the API.
 - Exposing as a proxy or getter/setter restrict us to introduce new functionality in the variables.

**Comment by Jesus89** [comment]
OK. Just a few comments.
- Generally, the getter value calls eval() without the feature.
- `Anim` should be an expression, added in `carto.expressions`, not a global function.
