### ISSUE TITLE
Create guides for multi-scale cartography techniques

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#871]
Include:

- `zoomRange` (basics)
- `zoomRange` to introduce thematic styling at a given zoom (example link uses deprecated `blend` but for the idea)
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidHhfMDEyNV9jb3B5X2NvcHkiLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBibGVuZCgxLFxuICAgICAgICAgICAgYmxlbmQoMTAsIDUwKmxpbmVhcigkYW1vdW50LHZpZXdwb3J0TUlOKCRhbW91bnQpLHZpZXdwb3J0TUFYKCRhbW91bnQpKSwgbGluZWFyKHpvb20oKSwgMl4xNCwgXG4gICAgICAgICAgICAyXjE2KSksXG4gICAgICAgICAgICBsaW5lYXIoem9vbSgpLCAyXjEzLCAyXjE0KVxuKSBcbmNvbG9yOiByZ2JhKDI1NSwyNTUsMjU1LDAuMilcbnN0cm9rZUNvbG9yOiByYW1wKHRvcCgkY2F0ZWdvcnksNSksdml2aWQpXG5zdHJva2VXaWR0aDogMSAiLCJmIjp7ImxuZyI6Mi4xOTM2NDY5ODgwNTk0MTMsImxhdCI6NDEuMzkxOTkzMjg4NjcyODl9LCJnIjoxMi41NjY4NDA4NjE1ODU1MjYsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==

These examples from @davidmanzanares are really good to show how to turn layer and/or category visibility using a filter:

- layer visibility w/ filter
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoic3BlbmRfZGF0YSIsImIiOiIiLCJjIjoiY2FydG92bCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IHNxcnQoJGFtb3VudC81MDAwKSoyMCooem9vbSgpLzQwMDArMC4wMSkqMS41XG5jb2xvcjogcmFtcCgkY2F0ZWdvcnksIFBSSVNNKVxuc3Ryb2tlQ29sb3I6ICAgICAgIHJnYmEoMCwwLDAsMC43KVxuc3Ryb2tlV2lkdGg6ICAgICAgMip6b29tKCkvNTAwMDBcblxuZmlsdGVyOiBiZXR3ZWVuKHpvb20oKSwgMl4xMiwgMl4xNSkgIiwiZiI6eyJsbmciOjIuMTg2NjgwODExOTg0OTU2NiwibGF0Ijo0MS4zOTI4MDQwOTEzNzAwMX0sImciOjE0Ljc3NTc5OTUzNzEwOTY5MSwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoiZGF0YXNldCJ9

- multi-condition w/ filter
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoic3BlbmRfZGF0YSIsImIiOiIiLCJjIjoiY2FydG92bCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IHNxcnQoJGFtb3VudC81MDAwKSoyMCooem9vbSgpLzQwMDArMC4wMSkqMS41XG5jb2xvcjogcmFtcCgkY2F0ZWdvcnksIFBSSVNNKVxuc3Ryb2tlQ29sb3I6ICAgICAgIHJnYmEoMCwwLDAsMC43KVxuc3Ryb2tlV2lkdGg6ICAgICAgMip6b29tKCkvNTAwMDBcblxuZmlsdGVyOiB6b29tKCk+Ml4xMiBvciAkY2F0ZWdvcnk9PVwiU2FsdWRcIiIsImYiOnsibG5nIjoyLjM0NzI3MDM1ODMyNjIyNzMsImxhdCI6NDEuMjgwMTIyMzQwMTQ1Nzk1fSwiZyI6OS4zODgyNDA2MTQwMTU1NjUsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==

slack help convo:
https://cartoteam.slack.com/archives/CARGX2FU4/p1534778975000100

**Comment by davidmanzanares** [comment]
:+1:

Keep in mind that for the last two cases we plan to make more breaking changes to `zoom`

**Comment by makella** [comment]
Yep! Just to keep track of some good ones :) turning symbology on and off through zoom like you have filtered will be good examples.

**Comment by elenatorro** [comment]
Moving this issue to https://github.com/CartoDB/carto-vl/issues/973
