### ISSUE TITLE
Some CDN for the 0.6.2 version are broken (including npm)

### ISSUE THREAD

**Issue by Captain-Oski** [CartoDB/carto-vl#887]
Hello everyone,

Working with CARTO-VL is a great pleasure, just to let you know.

I am currently working on the latest version 0.6.2. 

It seems that globalMax (and all global methods) in the carto.Viz are broken. 

Issue :  They always return 0.

Viewports methods in the carto.Viz are working fine.

I tried it on different CDN (instead of npm) some are working some don't 

Are you able to help please ?

**Working version :** 
  `<script src="https://cartodb.github.io/carto-vl/dist/carto-vl.js"></script>`

**Broken version :** 
`<script src="https://libs.cartocdn.com/carto-vl/v0.6.2/carto-vl.js"></script>`
`npm i @carto/carto-vl`

**Comment by Jesus89** [comment]
Hi @Captain-Oski,

Thanks for the feedback. Could you attach a brief example to add context about the current bug?

NOTE: the bundle hosted in GitHub Pages contains unstable versions from master, equal or greater than the current stable version. In this case, this version has changes respect to `v0.6.2`. We have in mind to release `v0.7.0` on Friday (that should be supposed to work for you). However, it would be nice to find exactly the bug and where it was solved.

Regards.

**Comment by Captain-Oski** [comment]
Thank your for answering that fast, looking forward to 0.7.0.
Snippet will follow

Context : 
I need to attach to the current carto.Viz some data to power one or two widgets of my own that will show Maximum value of the layer (polygons) and Average value of the layer, then compare this Max and  Avg value against the viewport Max and Avg to let the user know if they are in a Strong or Weak area.

See attached picture.

When I deploy that process on the npm version carto.Viz global methods are always returning 0 when I make a one page html app with the GitHub Pages bundle the methods are returning good values.

Working example : [https://gyazo.com/8bfa1c44a144fe62414565a1d65005e5](url)
Non working example : [https://gyazo.com/56320cf71b1409f925c7f3113ed26d7b](url)

Below my carto.Viz config (Vue.js framework)
`
const viz = new carto.Viz(
`
@${data.id}: $${data.id}
@globalMAX: globalMax($${data.id})
@globalAVG: globalMAvg($${data.id})    
@vpPopAVG: viewportAvg($${data.id})
@vpPopSUM: viewportSum($${data.id})
@da_PCT: ($${data.id}/$r1)*100
@da_TOT : $r1
@da_DIST: viewportHistogram($${data.id}, 1, 10)
color: ramp(linear($r1, 0, globalMax($${data.id})), PRISM)
strokeWidth: 0
      `
`)

**Comment by Jesus89** [comment]
Hi. We have just released 0.7.0. Please check if it works for you.

Closing this ticket. (Feel free to re-open the issue if you find another bug)

**Comment by Captain-Oski** [comment]
Hi ! 
Thank you so much for your efforts ! Well appreciated ! 

I'm confirming that version 0.7.0 (and mapbox 0.48.0) are sovling my issue about the global methods.

I am specifying mapbox version because I was working with @carto/mapbox-gl.0.45.0 and the stack was broken. 

With full updates it works like a charm ! 

Thank you again , the Anagraph team
