### ISSUE TITLE
Fix `ramp` eval with colors

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#895]
`ramp` eval doesn't compute the right colors. Although its result is close.

I found two problems:
- It doesn't interpolate within the color array of 256 colors, while GLSL does.
- The access to the color array is wrong due to a miscalculation of the index which is done with `Math.round(m * MAX_BYTE_VALUE);` I think this is wrong and that it should be `clamp(floor(m*COLOR_ARRAY_LENGTH), 0, COLOR_ARRAY_LENGTH-1))`. See the following image for my reasoning.

![20180827_114410](https://user-images.githubusercontent.com/1692175/44653631-982a7f80-a9ef-11e8-9c8b-1fad8d8af0b7.jpg)

**Comment by elenatorro** [comment]
Blocked by https://github.com/CartoDB/carto-vl/issues/572

**Comment by elenatorro** [comment]
🚀 in #935
