### ISSUE TITLE
Make documentation available for different versions

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#898]
Steps:

* [x] Have different versions of the documentation available at https://carto.com/developers/carto-vl/
* [x] Add hook to have a CDN per branch (we would need to modify the `copy` task in the developer center)

**Comment by elenatorro** [comment]
🚀special thanks to @csubira, awesome work! 💪

**Comment by rochoa** [comment]
Thanks, @elenatorro and @csubira. ❤️ 

Having documentation for different versions is the way to go. 💪
