### ISSUE TITLE
Cannot import carto-vl from npm package (ES6)

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#900]
After installing the package from npm, it can not be imported using the `import` syntax:

```js
import carto from '@carto/carto-vl';
console.log(carto); // undefined
```

However, it works OK using the `require` function:

```js
const carto = require('@carto/carto-vl');
console.log(carto); // Module {...}
```

UPDATE: works with `import * as carto from '@carto/carto-vl';`

**Comment by VictorVelarde** [comment]
Does `import * as carto from '@carto/carto-vl';` works?
Do we want a default export in our index.js?

**Comment by Jesus89** [comment]
Yes, an `export default` is missing in the main index.js file

**Comment by VictorVelarde** [comment]
Included for the next (public) release
