### ISSUE TITLE
Export CARTO MGL styles

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#905]
Enable the following usage:
```
const map = new mapboxgl.Map({
    style: carto.basemaps.voyager
})
```

This would allow in the future to embed our basemap styles in the CARTO VL library avoiding extra requests and reducing loading time.

**Comment by davidmanzanares** [comment]
Yes, I think there are 3 ways of implementing it:
- Storing just the URL
- Storing the JSON
- Storing the JSONs. Each JSON actually points to other JSONs. We could also remove this level of indirection.

I'd prefer the third option, but I don't know how difficult is to remove that level of indirection, and if the bundle size is increased by much.

Maybe @rochoa has more input.

**Comment by VictorVelarde** [comment]
This is ready in the PR. 
@davidmanzanares and @rochoa It would be great if you could check it, cause there are a lot of examples updated there (just replacing old url with new constant)

**Comment by VictorVelarde** [comment]
This has been merged 🚀
