### ISSUE TITLE
Dealing with undefined IDs in MVTs

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#914]
Currently, undefined IDs silently pass the MVT decoder. Once styling interactivity is used this cause an error that doesn't show any reference to the ID problem of the data.

**Comment by VictorVelarde** [comment]
ping @davidmanzanares 
can you please confirm this ?

**Comment by davidmanzanares** [comment]
Sorry, for the late response. I no longer remember how to repeoduce it. The code you pointed out seems good. I think we can close the issue since it's possible that I was seeing the problem in an old CVL version. Sorry for the noise
