### ISSUE TITLE
Symbol color interactivity not working properly

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#929]
When the color of a symbol is not set and the color is changed in an interactivity event it produces weird results.

```js
const DURATION = 10;
interactivity.on('featureEnter', (event) => {
  event.features.forEach((feature) => {
    feature.color.blendTo('yellow', DURATION);
  });
});
interactivity.on('featureLeave', (event) => {
  event.features.forEach((feature) => {
    feature.color.reset(DURATION);
  });
});
```

**Color: red**

![symbol-interactivity-ok](https://user-images.githubusercontent.com/2227572/45043796-83dd2700-b06e-11e8-8864-d507cf3069f6.gif)

**Color: default**

![symbol-interactivity-error](https://user-images.githubusercontent.com/2227572/45043826-93f50680-b06e-11e8-87c8-9d4b8c522a2f.gif)

**Comment by VictorVelarde** [comment]
Just merged into master (not in v0.8 though, but next release)
