### ISSUE TITLE
Allow to change symbol in a feature

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#932]
Now the symbol property is not added in the feature so it can not be changed whith hover or click. It would be nice to have this feature available in the API.

```js
const viz = new carto.Viz(`
  width: 30
  symbol: image('${marker}')
`);

[...]

feature.symbol.blendTo(`image('${markerSelected}')`);
feature.symbol.reset();
```

**Comment by davidmanzanares** [comment]
I think this can be done by modifyng https://github.com/CartoDB/carto-vl/blob/master/src/interactivity/feature.js

After supporting blending betweem images, which is an existing issue that is already under development.
