### ISSUE TITLE
Add syntax sugar for offset/placement

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#934]
Related with https://github.com/CartoDB/carto-vl/pull/919 and https://github.com/CartoDB/carto-vl/issues/361

Add `transform` property and `translate` expression as syntax sugar of `offset` and `placement` respectively. 

```
offset: placement(0, 1)
```

```
transform: translate(0, 1)
```

**Comment by elenatorro** [comment]
I have some concerns  / question about this issue:

* What happens if there are both offset and transform property in the viz?
* Should we create a new `translate` expression, or only use it as 'syntax sugar' of placement?
* If we create a new expression, should `translate` expression type be 'transform' or 'transformation', so future transform expressions use the same type?
* Should we add in the documentation that both properties are now equivalent?

**Comment by elenatorro** [comment]
After talking with @davidmanzanares, we have to do the following:

1. Create a new Translate expression with the same code of Placement (changing the 'type')
2. Change 'offset' name to 'transform'.

**Comment by davidmanzanares** [comment]
Fixed by #938
