### ISSUE TITLE
Add timestamp to animation control example

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#936]
The [animation controls](https://carto.com/developers/carto-vl/examples/#example-animation-controls) example we have is great! One thing that I think we could add is how to get the timestamp to show as well.

A lot of people want to display the timestamp of their animations (makes sense!) so it would be super helpful to enhance the current example to include that as well.

**Comment by rochoa** [comment]
Solved via https://github.com/CartoDB/carto-vl/pull/1155.
