### ISSUE TITLE
debug/animation_sql is broken

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#943]
After debugging I saw that the continue on https://github.com/CartoDB/carto-vl/blob/master/src/sources/MVTWorker.js#L141 is being executed every time.

I think this is because the points are on the equator. Keep in mind that there is a `y` axis inversion just before that line, that's my best guess. In any case, the points are on the MVT tiles.

**Comment by rochoa** [comment]
Is this still a thing?

**Comment by VictorVelarde** [comment]
It is working now
