### ISSUE TITLE
Mention to our fork of MapboxGL

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto-vl#949]
A customer told me that he spent quite a few time because he didn't realize that we were talking not about the original MapboxGL but our forked one. He tried to install `npm -i mapbox-gl en` and getting an error.

I know that the examples uses our fork but it'd be great to be more explicit in the getting started guide about the need of using our own fork.

**Comment by VictorVelarde** [comment]
This has been explained in more detail in the updated `Getting Started` guide 🚀 (currently in master).
