### ISSUE TITLE
The expression viewportFeatures should return features as in interactivity

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#954]
The name of this expression is confusing because you expect to obtain an array of features, like this one from the interactivity: https://carto.com/developers/carto-vl/reference/#feature.

However, the usage of this expression indicates that you get a list of metadata associated with a feature instead.

```js
viewportFeatures($value, $category) -> array of {value, category}
```

So IMO it should be renamed to something like `viewportMetadata` or `viewportFeaturesData` to clarify what this expression does.

**Comment by elenatorro** [comment]
IMO, `viewportFeaturesData` or even `viewportFeaturesMetadata` sounds great. Should keep having a `viewportFeatures` expression that does what you expect, obtaining an array of features?

**Comment by davidmanzanares** [comment]
We could return the same "smart" features we are returning on Interactivity, I think the implementation could re-use most parts of the Interactivity one.

**Comment by VictorVelarde** [comment]
We have just merged the new approach to master 🚀
