### ISSUE TITLE
Wrong symbol image if set after init

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#956]
When the symbol is set in the viz it shows the correct image colors:

```js
const viz = new carto.Viz(`
  width: 40
  symbol: image('${marker}')
`);
```
![](https://user-images.githubusercontent.com/2227572/45614460-e3253900-ba69-11e8-9ace-4cd31c7965dc.png)

But, when it is set after the viz initialization it picks the default color instead of using the correct image colors.

```js
const viz = new carto.Viz(`
  width: 40
`);
viz.symbol.blendTo(`image('${marker}')`);
```
![](https://user-images.githubusercontent.com/2227572/45614449-db659480-ba69-11e8-9f49-105c428cce2b.png)

I think the expected behaviour in the second case should be the same as the first one.

**Comment by VictorVelarde** [comment]
What version are you using @Jesus89 ?
I think that should be already fixed after the work on https://github.com/CartoDB/carto-vl/issues/929, which is in master but not released yet
