### ISSUE TITLE
Filter not working for symbols

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#957]
### Filter 0

- Symbols are shown (they shouldn't be rendered)
- Interactivity is disabled

```js
const viz = new carto.Viz(`
  symbol: car
  filter: 0
`);
```

### Filter >0

- Symbols are shown (they should be rendered with opacity)
- Interactivity is enabled

```js
const viz = new carto.Viz(`
  symbol: car
  filter: 0.5
`);
```

**Comment by rochoa** [comment]
This is already fixed.
