### ISSUE TITLE
Guides – Getting started

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#966]
This is the proposed structure for the guide:
  1. Introduction
  1. Basic set up (link to advanced set up in "Advanced Tips" section)
  1. Define the basemap
  4. Define the user
  1. Define the source
  1. Define the Viz object
  1. Define the Layer
  1. Style the Viz object
  1. All together

**Comment by VictorVelarde** [comment]
This has just been merged to master 🚀

**Comment by rochoa** [comment]
VAMOS! 💪
