### ISSUE TITLE
Guides – Styling your visualization using Expressions

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#969]
Recommendation: if possible, reuse content from _Introduction to expressions, interpolation, styling and image files_.
Note: add a visual example for each section.

## Proposed structure 
1. What's a visualization property? (link to reference)
1. What's an expression? (link to reference)
1. Playing with colors
    * Chaning color
        - Color spaces
    * Stroke property  
1. Understanding Opacity
    (link to advanced section)
    * Adding opacity
        - Opacity vs RGBA color
1. Using images as markers (link to advanced)
    * Images as symbols
    * Built-in icons
1. Transformation and Placement (better name) related: https://github.com/CartoDB/carto-vl/issues/822
    * Translating the geometry (link to examples)
    * Placing images
1. Changing the resolution
    (only mention the property, link to advanced) 
1. Filtering data
    (only mention the property, link to advanced)
1. Defining variables
    (only mention the property, link to advanced)
1. Ordering
    (only mention the property, link to advanced)

**Comment by davidmanzanares** [comment]
If this is one of the first guides, I think that images and transformations are too advanced for it. Although I agree we should mention and link them.

**Comment by davidmanzanares** [comment]
Fixed by #1005
