### ISSUE TITLE
Guides – Data-driven visualizations

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#970]
## Proposed structure

1. What's a ramp? (example with a simple categorical property)
1. Using input expressions
    * Using another expression in a ramp
    * Nesting expressions (link to advanced "the power of nested expressions")
1. Thematic visualizations (all the examples must use only _colors_ as output)
    * Visualizing Numeric Data
      * Classification
      * Interpolation
    * Visualizing Categorical Data
      * Top
      * Buckets
1. Using color palettes, numbers and images
    * CartoColor and custom colors
    * Numbers
    * Images
1. Getting ramp information
    * Using legends## Proposed structure
1. What's a ramp? (example with a simple categorical property)
1. Using input expressions
    * Using another expression in a ramp
    * Nesting expressions (link to advanced "the power of nested expressions")
1. Thematic visualizations (all the examples must use only _colors_ as output)
    * Visualizing Numeric Data
      * Classification
      * Interpolation
    * Visualizing Categorical Data
      * Top
      * Buckets
1. Using color palettes, numbers and images
    * CartoColor and custom colors
    * Numbers
    * Images

~~Getting ramp information~~
    ~~* Using legends~~ --> Moved to a separated guide

**Comment by davidmanzanares** [comment]
Fixed by https://github.com/CartoDB/carto-vl/pull/1005
