### ISSUE TITLE
Guides – Visualizing big datasets: aggregations and clustering

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#971]
## Proposed structure
1. Global aggregation
1. Viewport Aggregation
1. Resolution
1. Clustering

**Comment by VictorVelarde** [comment]
Add a note regarding to resolution as a way to improve rendering when a lot of points overlap

**Comment by VictorVelarde** [comment]
New guide has been merged to master 🚀

**Comment by rochoa** [comment]
VAMOS! 💪
