### ISSUE TITLE
Guides – Zoom-based styling with multiscale expressions

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#973]
Note: review guide naming.

Related issue https://github.com/CartoDB/carto-vl/issues/871

## Proposed structure
1. Zoom
1. Zoomrange
1. Scale

**Comment by davidmanzanares** [comment]
I made some examples to show the functionality:

Zoom:
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibmVfMTBtX3BvcHVsYXRlZF9wbGFjZXNfc2ltcGxlIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiIvLyBVc2luZyB6b29tKCkgdG8gb25seSBzaG93IGxhcmdlc3QgY2l0aWVzIGF0IGxvdyB6b29tIGxldmVsc1xuY29sb3I6IHJhbXAoZ2xvYmFsUXVhbnRpbGVzKCRwb3BfbWF4LCA1KSwgdGVtcHMpXG5zdHJva2VXaWR0aDogMFxuZmlsdGVyOiB6b29tKCk+MyBvciAkcG9wX21heD4xMDAwMDAwXG4iLCJmIjp7ImxuZyI6NzQuNjQ4NTY2MDIyMTUwMjUsImxhdCI6MjUuNTkyMDI5NTE0MzYyNzV9LCJnIjoxLjYxOTQ1NTI1OTIyNzEzNzIsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==

Scale:
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibmVfMTBtX3BvcHVsYXRlZF9wbGFjZXNfc2ltcGxlIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogc2NhbGVkKDIpXG5jb2xvcjogcmFtcChnbG9iYWxRdWFudGlsZXMoJHBvcF9tYXgsIDcpLCB0ZW1wcylcbnN0cm9rZVdpZHRoOiAwXG5cbiIsImYiOnsibG5nIjotMTAuNjcxNTIxMzI4NTAyOTksImxhdCI6NS42ODQzNDE4ODYwODA4MDJlLTE0fSwiZyI6MS4wNTUyODI0MTUwNDMxOTg4LCJoIjoiRGFya01hdHRlciIsImkiOiJkYXRhc2V0In0=

Zoomrange + scale:
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoibmVfMTBtX3BvcHVsYXRlZF9wbGFjZXNfc2ltcGxlIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogc2NhbGVkKDIpXG5jb2xvcjogcmFtcChnbG9iYWxRdWFudGlsZXMoJHBvcF9tYXgsIDcpLCB0ZW1wcylcbnN0cm9rZVdpZHRoOiAwXG5cbi8vIFNob3cgbGFyZ2VzdCAoZ3JlYXRlciB0aGFuIHBlcmNlbnRpbGUgOTl0aCkgY2l0aWVzIG9uIHpvb20gbGV2ZWwgMFxuLy8gU2hvdyBsYXJnZSAoZ3JhdGVyIHRoYW4gcGVyY2VudGlsZSA2MHRoKSBjaXRpZXMgb24gem9vbSBsZXZlbCAzXG4vLyBTaG93IGV2ZXJ5IGNpdHkgb24gdGhlIGRhdGFzZXQgYXQgem9vbSBsZXZlbCA2XG5maWx0ZXI6IHJhbXAoem9vbXJhbmdlKFswLCAzLCA2XSksXG4gICAgICAgICAgICAgWyRwb3BfbWF4Pmdsb2JhbFBlcmNlbnRpbGUoJHBvcF9tYXgsIDk5KSxcbiAgICAgICAgICAgICAgJHBvcF9tYXg+Z2xvYmFsUGVyY2VudGlsZSgkcG9wX21heCwgNjApLFxuICAgICAgICAgICAgICB0cnVlXSlcbiIsImYiOnsibG5nIjoxNDEuODgxMjQwMzg2NjM4NTIsImxhdCI6NS42ODQzNDE4ODYwODA4MDJlLTE0fSwiZyI6MS4wNTUyODI0MTUwNDMxOTg4LCJoIjoiRGFya01hdHRlciIsImkiOiJkYXRhc2V0In0=

**Comment by makella** [comment]
this is great, thank you @davidmanzanares !

**Comment by makella** [comment]
@davidmanzanares not done yet, but working draft is here:
https://docs.google.com/document/d/1oT8qvx-jKRGSb5eOLTHEpdCcorhHu8Xo7__v8L-d1QM/edit?usp=sharing

**Comment by makella** [comment]
and my branch (text is slightly different as I've been editing as I go)
https://github.com/CartoDB/carto-vl/tree/975-zoom-based-style-guide

**Comment by makella** [comment]
thinking of this for final map shows a good example to show how to combine each higher level concept (minus `zoom()` but i could add a filter)

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidmFuY291dmVyX3RyZWVzIiwiYiI6IiIsImMiOiJjYXJ0b3ZsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJcblxud2lkdGg6IHJhbXAoem9vbVJhbmdlKFsxMCwxNF0pLFswLjUsc2NhbGVkKHNxcnQoJGRpYW1ldGVyKSoyLDE1KV0pXG5jb2xvcjogcmFtcCh6b29tUmFuZ2UoWzEwLDE0XSksW3JnYigwLDI1NSwzMCksb3BhY2l0eShyYW1wKCRjb21tb25fbmFtZSxwcmlzbSksMC44KV0pXG5zdHJva2VXaWR0aDogcmFtcCh6b29tUmFuZ2UoWzExLDE0XSksWzAsMC41XSlcbnN0cm9rZUNvbG9yOiByYW1wKHpvb21SYW5nZShbMTEsMTRdKSxbYmxhY2sscmFtcCgkY29tbW9uX25hbWUscHJpc20pXSkiLCJmIjp7ImxuZyI6LTEyMy4wOTg3MzE0MTk1ODQwNiwibGF0Ijo0OS4yMzUyODE1NjYzODg0NjZ9LCJnIjoxMCwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoiZGF0YXNldCJ9

**Comment by VictorVelarde** [comment]
Merged to master 🚀
