### ISSUE TITLE
Guides – User interactions with your visualization: pop-ups and legends

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#975]
Note: review guide title.
Note: reuse _"Introduction to Interactivity"_.

## Proposed structure
1. Using variables
1. Feature Events
1. Map Events
1. Adding pop ups
1. Interactive based styling
    * Interactive Classification (link to 'ramp' classification guide)
    * Interactive Global Aggregation (link to 'Global Aggregation' guide)
    * Interactive Viewport Aggregation (link to 'Viewport Aggregation' guide)
    * Blend (note: just mention and link to reference)
    * Updating legends

**Comment by VictorVelarde** [comment]
I have modified a bit the structure, reordering some sections (from more general to more specific) and dropping most of the last one. The result is:

1. Map events
2. Layer events
3. Using dynamic variables
4. Feature events
5. Adding pop-ups
6. Interactive-based styling (just a small demo of `blendTo` applied to featureEnter-featureLeave)

**Comment by VictorVelarde** [comment]
Merged to master 🚀
Contents on legends and widgets will be accommodated in a new guide
