### ISSUE TITLE
Reference – review structure

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#977]
Reference [WIP]: Proposed structure (1)

* Carto
  * Sources
      * Dataset
      * GeoJSON
      * SQL
      * MVT
        * MVTMetadata
        * MVTOptions
        * MVTProperty
  * Viz

  * Layer
    * LayerEvent

  * Expressions (+palette, +icons)

  * Expression Types
    * Color
    * Category
    * Date
    * Number
    * Image

  * Features
  * Interactivity
    * Events

* Errors

**Comment by elenatorro** [comment]
🚀
