### ISSUE TITLE
Create a cheatsheet/glossary

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#979]
It will help to define some concepts and basic naming.

## General vs CARTO VL specific glossary

 - **General terms that are relevant for the whole CARTO ecosystem**: we're going to reuse the [Help Glossary](https://carto.com/help/glossary/). We should open an issue or PR in this [repository](https://github.com/CartoDB/help) to submit new terms.
 - **CARTO VL specific topics**: we are gonna use the [docs/guides/0x-glossary.md](https://github.com/CartoDB/carto-vl/blob/0710750a4f9c90d16087e4eea1db754b861592a5/docs/guides/0x-glossary.md) file in this repository.

## Glossary

* CDN
* CORS
* expression
* GeoJSON
* GIS
* JSON
* SQL
* viz property

**Comment by davidmanzanares** [comment]
I think we can close this since we have already created it and populated as needed when creating the new guides.

Do you agree?
