### ISSUE TITLE
Remove the stand-alone map from the bundle

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#989]
It is included in the bundle, but it is only useful for the tests.

(file `Map.js`)

cc: @rochoa @VictorVelarde

**Comment by davidmanzanares** [comment]
Blocked for https://github.com/CartoDB/carto-vl/pull/984

**Comment by VictorVelarde** [comment]
@davidmanzanares I have removed `carto.Map` from the library in the PR #986, moving it as `CartoMap` to the tests folder, so everything should be working.

We can try to merge that one after #984

**Comment by VictorVelarde** [comment]
This has been merged to master 🚀 🚀
