### ISSUE TITLE
Marker allow overlap property

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/carto-vl#993]
Even in higher zoom levels, it would be nice to have something similar like [CartoCSS `marker-allow-overlap`](https://carto.com/developers/styling/cartocss/#marker-allow-overlap-boolean)

**Comment by rochoa** [comment]
What is the most prominent use-case in Vector you want to support with that feature?

**Comment by ramiroaznar** [comment]
Sorry @rochoa, I missed this. After giving a 2nd though, this feature request only makes sense at higher zoom levels. And in these zoom levels, the overlapping should not be a problem...

In lower zoom levels, the new smart aggregation could return a `count` and then it could be styled based on it.

**Comment by rochoa** [comment]
Thanks, Ramiro. I was about to do a follow-up in this conversation because we are trying to clarify feature requests like this. 😄 

As per your comment, I'm closing it for now.
