### ISSUE TITLE
Clustering with viewport agg doesn't work

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#994]
A quick research showed that it may be related to the lack of a name (of the clustered property) when generating the feature that is passed in the `accum` methods

**Comment by davidmanzanares** [comment]
You can take a look at `file:///home/dv/github/renderer-prototype/examples/editor/index.html#eyJhIjoic3BlbmRfZGF0YSIsImIiOiIiLCJjIjoiY2FydG92bCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoiQGE6IGNsdXN0ZXJBdmcoJGFtb3VudClcbkBjOiBjbHVzdGVyTWF4KCRhbW91bnQpXG53aWR0aDogQGEvMTAwXG5jb2xvcjogcmdiKDIwNCwwLDApXG5AYjogdmlld3BvcnRBdmcoY2x1c3RlckF2ZygkYW1vdW50KSkiLCJmIjp7ImxuZyI6Mi4xNjA4NzY4MTg3ODQ0NTksImxhdCI6NDEuMzk1OTIzNDMxNzQwNDR9LCJnIjoxMi43MzI2OTIzNzA4MjM5NTcsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==`

and put `layer.viz.variables.b.value` on Chrome's console to debug it.

The issue happens when things like `viewportAvg(clusterAvg($amount))` are used, but this is not the only problem, for example, Interactivity with `@b: (clusterAvg($amount))` is broken too, and for the same reason.

The problem happens on Dataframe.js, method `_genFeatureClass`. In it, there is a loop over the **Metadata** properties to retrieve (later) the properties from the Dataframe. This logic is wrong because a Metadata property may have multiple Dataframe properties due to multiple aggregations (avg and min for example).

This also fails when there is only one clustering in use because the name on the Dataframe includes the aggregation, but the name on the Metadata is just the original name of the column.

`viewportFeatures` suffers a similar problem, and in this case I think that an API change is the only possible way to solve it.

**Comment by davidmanzanares** [comment]
`viewportFeatures` should be fixed with the time aggregation PR of @jgoizueta 

The rest should be fixed by #1071

**Comment by VictorVelarde** [comment]
@jgoizueta It would be great if you could merge master into your branch, now that #1085 has been merged (related to `viewportFeatures`) to check if this issue is still relevant and up-to-date

**Comment by davidmanzanares** [comment]
Already fixed (not sure by who, by #1085  or by #551 )!
