### ISSUE TITLE
isNaN filter doesn't work on windows

### ISSUE THREAD

**Issue by padawannn** [CartoDB/carto-vl#997]
The example:
[index_nan.html.zip](https://github.com/CartoDB/carto-vl/files/2414512/index_nan.html.zip)

You can test this example on Chrome in Windows and Mac (or Linux) and you will get different results. In the example there are 3 points. The first point has these properties `"properties": {"value": 10 }` and the other two points have these properties `"properties": {}`. The filter is `filter: isNaN($value)`

Screenshot on Mac:
<img width="1438" alt="captura de pantalla 2018-09-25 a las 10 58 21" src="https://user-images.githubusercontent.com/7164554/46004907-57885980-c0b4-11e8-9dc9-6099f66e2449.png">

This behavior is correct

Screenshot on windows:
<img width="1574" alt="captura de pantalla 2018-09-25 a las 10 58 28" src="https://user-images.githubusercontent.com/7164554/46004984-83a3da80-c0b4-11e8-9628-0c96bf66ab25.png">

No point is shown

You can also try this filter `filter: not(isNaN($value))`

This bug causes strange behavior in the Mastercard project on windows because we have many values at NaN

**Comment by alissarose** [comment]
Hey team - just want to ping on this for priority

adding @CartoDB/rt-managers because this is a Windows 🐛 and Mastercard <3 Windows 😬

**Comment by alissarose** [comment]
Hi hi,

Any status on this? It's a pretty big blocker from our side -- so if you need more info or have any suggestions on how to make this work in Windows I can help get whatever you need. Thaaanks!

**Comment by ramiroaznar** [comment]
@elenatorro did https://github.com/CartoDB/carto-vl/pull/1016 fix this issue?
