### ISSUE TITLE
Extract bounds information from a Maps API Source

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#998]
Currently, there is no automatic way to set the map's center and zoom level to fit the bounds of a dataset. Which is a really common use.

We could add that to the Maps API metadata and expose it in CVL Maps API sources, with some examples of usage.

cc: @andy-esch

**Comment by rochoa** [comment]
This kind-of duplicates #999. I recommend using the very same technique proposed there.

If we want to add this feature, we have to do it for every different source. Using metadata from Maps API will only cover the SQL/Dataset sources.

I'm closing this for now. Let's revisit this in the future.

**Comment by andy-esch** [comment]
The techniques I see listed there are for carto.js. Does that mean to import carto.js and use the sql client there to pass the information to carto vl's map object for the centering?

**Comment by rochoa** [comment]
Yes, they are for CARTO.js, but the same applies to CARTO VL. And no, you don't need to include CARTO.js. Actually, if you are targetting modern browsers—you are if you are using CARTO VL—you can rely on [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).
